// MARK: - Desktop Groups

const embedDesktopGroups_Player = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الاقتراحات في نهاية الفيديو",
            "ca": "Amaga els suggeriments al final del vídeo",
            "zh-CN": "在视频末尾隐藏建议",
            "zh-TW": "在影片末尾隱藏建議",
            "hr": "Sakrij prijedloge na kraju videozapisa",
            "cs": "Skrýt návrhy na konci videa",
            "da": "Skjul forslag i videoenden",
            "nl": "Suggesties verbergen in het video-einde",
            "en": "Hide Suggestions in the Video End",
            "fi": "Piilota ehdotukset videon lopussa",
            "fr": "Masquer les suggestions à la fin de la vidéo",
            "de": "Vorschläge am Ende des Videos ausblenden",
            "el": "Απόκρυψη προτάσεων στο τέλος βίντεο",
            "he": "הסתר הצעות בקצה הסרטון",
            "hi": "वीडियो के अंत में सुझाव छिपाएँ",
            "hu": "Javaslatok elrejtése a videó végén",
            "id": "Sembunyikan Saran di Akhir Video",
            "it": "Nascondi suggerimenti alla fine del video",
            "ja": "ビデオの最後に提案を非表示にする",
            "ko": "비디오 끝에서 제안 숨기기",
            "ms": "Sembunyikan Cadangan dalam Penghujung Video",
            "nb": "Skjul forslag i videoenden",
            "pl": "Ukryj sugestie na końcu filmu",
            "pt": "Ocultar sugestões no final do vídeo",
            "ro": "Ascundeți sugestiile la finalul videoclipului",
            "ru": "Скрыть предложения в конце видео",
            "sk": "Skryť návrhy na konci videa",
            "es": "Ocultar sugerencias al final del vídeo",
            "sv": "Dölj förslag i videoslutet",
            "th": "ซ่อนคำแนะนำในส่วนท้ายของวิดีโอ",
            "tr": "Videonun Sonundaki Önerileri Gizle",
            "uk": "Приховати пропозиції в кінці відео",
            "vi": "Ẩn đề xuất ở cuối video"
          },
        id: "untrap_embed_hide_end_screen_suggestions",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء البطاقات في نهاية الفيديو",
            "ca": "Amaga les targetes al final del vídeo",
            "zh-CN": "隐藏视频末尾的卡片",
            "zh-TW": "隱藏影片末尾的卡片",
            "hr": "Sakrij kartice na kraju videa",
            "cs": "Skrýt karty na konci videa",
            "da": "Skjul kort i videoenden",
            "nl": "Kaarten verbergen in het video-einde",
            "en": "Hide Cards in the Video End",
            "fi": "Piilota kortit videon lopussa",
            "fr": "Masquer les cartes à la fin de la vidéo",
            "de": "Karten am Ende des Videos ausblenden",
            "el": "Απόκρυψη καρτών στο τέλος βίντεο",
            "he": "הסתר כרטיסים בקצה הווידאו",
            "hi": "वीडियो के अंत में कार्ड छिपाएँ",
            "hu": "Kártyák elrejtése a videó végén",
            "id": "Sembunyikan Kartu di Akhir Video",
            "it": "Nascondi le carte alla fine del video",
            "ja": "ビデオエンドでカードを非表示にする",
            "ko": "비디오 끝에서 카드 숨기기",
            "ms": "Sembunyikan Kad dalam Penghujung Video",
            "nb": "Skjul kort i videoenden",
            "pl": "Ukryj karty na końcu wideo",
            "pt": "Ocultar cartões no final do vídeo",
            "ro": "Ascunde cardurile la finalul video",
            "ru": "Скрыть карточки в конце видео",
            "sk": "Skryť karty na konci videa",
            "es": "Ocultar tarjetas al final del vídeo",
            "sv": "Göm kort i videoslutet",
            "th": "ซ่อนการ์ดในส่วนท้ายวิดีโอ",
            "tr": "Videonun Sonundaki Kartları Gizle",
            "uk": "Сховати картки в кінці відео",
            "vi": "Ẩn thẻ ở cuối video"
          },
        id: "untrap_embed_hide_end_screen_infos",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الظل المتدرج لشريط مشغل الفيديو",
            "ca": "Amaga l'ombra del degradat de la barra del reproductor de vídeo",
            "zh-CN": "隐藏视频播放器栏渐变阴影",
            "zh-TW": "隱藏影片播放器列漸層陰影",
            "hr": "Sakrij sjenku trake video playera",
            "cs": "Skrýt stín přechodu na liště přehrávače videa",
            "da": "Skjul Video Player Bar Gradient Shadow",
            "nl": "Verberg schaduw van de balk van de videospelerbalk",
            "en": "Hide Video Player Bar Gradient Shadow",
            "fi": "Piilota videosoittimen kaltevuusvarjo",
            "fr": "Masquer l'ombre du dégradé de la barre du lecteur vidéo",
            "de": "Verlaufsschatten der Video-Player-Leiste ausblenden",
            "el": "Απόκρυψη σκιάς διαβάθμισης γραμμής προγράμματος αναπαραγωγής βίντεο",
            "he": "הסתר סרגל צל של נגן וידאו",
            "hi": "वीडियो प्लेयर बार ग्रेडिएंट शैडो छिपाएँ",
            "hu": "Videolejátszó sáv színátmenet-árnyékának elrejtése",
            "id": "Sembunyikan Bayangan Gradien Bilah Pemutar Video",
            "it": "Nascondi l'ombra sfumata della barra del lettore video",
            "ja": "ビデオプレーヤーバーのグラデーションシャドウを非表示にする",
            "ko": "비디오 플레이어 막대 그라데이션 그림자 숨기기",
            "ms": "Sembunyikan Bayang Kecerunan Bar Pemain Video",
            "nb": "Skjul Videospiller Bar Gradient Shadow",
            "pl": "Ukryj cień gradientowy paska odtwarzacza wideo",
            "pt": "Ocultar sombra gradiente da barra do player de vídeo",
            "ro": "Ascunde umbra degradată a barei playerului video",
            "ru": "Скрыть градиентную тень панели видеоплеера",
            "sk": "Skryť tieň prechodu na paneli prehrávača videa",
            "es": "Ocultar sombra degradada de barra de reproductor de vídeo",
            "sv": "Dölj videospelarens fält Gradient Shadow",
            "th": "ซ่อนเงาไล่ระดับสีของแถบเครื่องเล่นวิดีโอ",
            "tr": "Video Oynatıcı Çubuğu Degrade Gölgesini Gizle",
            "uk": "Сховати градієнтну тінь панелі відеопрогравача",
            "vi": "Ẩn bóng chuyển màu của thanh trình phát video"
          },
        id: "untrap_embed_hide_shadow_around_player_bar",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء أعلى الظل التدرج",
            "ca": "Amaga l'ombra del degradat superior",
            "zh-CN": "隐藏顶部渐变阴影",
            "zh-TW": "隱藏頂部漸層陰影",
            "hr": "Sakrij gornju gradijentnu sjenu",
            "cs": "Skryjte stín horního přechodu",
            "da": "Skjul Top Gradient Shadow",
            "nl": "Schaduw bovenste verloop verbergen",
            "en": "Hide Top Gradient Shadow",
            "fi": "Piilota Top Gradient Shadow",
            "fr": "Masquer l'ombre du dégradé supérieur",
            "de": "Oberen Verlaufsschatten ausblenden",
            "el": "Απόκρυψη σκιάς κορυφαίας κλίσης",
            "he": "הסתר את הצללית העליונה",
            "hi": "शीर्ष ग्रेडियेंट छाया छुपाएं",
            "hu": "Top Gradiens Shadow elrejtése",
            "id": "Sembunyikan Bayangan Gradien Atas",
            "it": "Nascondi ombra sfumata superiore",
            "ja": "上部のグラデーションシャドウを非表示にする",
            "ko": "상단 그라데이션 그림자 숨기기",
            "ms": "Sembunyikan Bayang Kecerunan Teratas",
            "nb": "Skjul Top Gradient Shadow",
            "pl": "Ukryj górny cień gradientowy",
            "pt": "Ocultar sombra do gradiente superior",
            "ro": "Ascunde umbra gradată de sus",
            "ru": "Скрыть верхнюю градиентную тень",
            "sk": "Hide Top Gradient Shadow",
            "es": "Ocultar sombra de degradado superior",
            "sv": "Dölj toppgradientskugga",
            "th": "ซ่อนเงาไล่ระดับบนสุด",
            "tr": "Üst Degrade Gölgesini Gizle",
            "uk": "Приховати верхню градієнтну тінь",
            "vi": "Ẩn bóng đổ trên cùng"
          },
        id: "untrap_embed_hide_top_shadow",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء التوصيات بشأن الإيقاف المؤقت",
            "ca": "Amaga les recomanacions en pausa",
            "zh-CN": "暂停时隐藏建议",
            "zh-TW": "暫停時隱藏建議",
            "hr": "Sakrij preporuke prilikom pauze",
            "cs": "Skrýt doporučení při pozastavení",
            "da": "Skjul anbefalinger ved pause",
            "nl": "Aanbevelingen bij pauze verbergen",
            "en": "Hide Recommendations on Pause",
            "fi": "Piilota suositukset keskeytyksestä",
            "fr": "Masquer les recommandations en pause",
            "de": "Empfehlungen bei Pause ausblenden",
            "el": "Απόκρυψη Προτάσεων για Παύση",
            "he": "הסתר המלצות בהשהיה",
            "hi": "विराम पर सिफ़ारिशें छिपाएँ",
            "hu": "Javaslatok elrejtése a szüneteltetésnél",
            "id": "Sembunyikan Rekomendasi saat Jeda",
            "it": "Nascondi consigli in pausa",
            "ja": "一時停止時に推奨事項を非表示にする",
            "ko": "일시 중지 시 권장 사항 숨기기",
            "ms": "Sembunyikan Pengesyoran pada Jeda",
            "nb": "Skjul anbefalinger ved pause",
            "pl": "Ukryj zalecenia dotyczące wstrzymania",
            "pt": "Ocultar recomendações em pausa",
            "ro": "Ascundeți recomandările la pauză",
            "ru": "Скрыть рекомендации на паузе",
            "sk": "Skryť odporúčania pri pozastavení",
            "es": "Ocultar recomendaciones en pausa",
            "sv": "Dölj rekommendationer vid paus",
            "th": "ซ่อนคำแนะนำในการหยุดชั่วคราว",
            "tr": "Duraklatmayla İlgili Önerileri Gizle",
            "uk": "Приховати рекомендації під час паузи",
            "vi": "Ẩn đề xuất khi tạm dừng"
          },
        id: "untrap_embed_player_hide_pause_recommenndations",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء عنوان الفيديو",
            "ca": "Amaga el títol del vídeo",
            "zh-CN": "隐藏视频标题",
            "zh-TW": "隱藏影片標題",
            "hr": "Sakrij naslov videa",
            "cs": "Skrýt název videa",
            "da": "Skjul videotitel",
            "nl": "Videotitel verbergen",
            "en": "Hide Video Title",
            "fi": "Piilota videon nimi",
            "fr": "Masquer le titre de la vidéo",
            "de": "Videotitel ausblenden",
            "el": "Απόκρυψη τίτλου βίντεο",
            "he": "הסתר את כותרת הסרטון",
            "hi": "वीडियो शीर्षक छिपाएँ",
            "hu": "Videó címének elrejtése",
            "id": "Sembunyikan Judul Video",
            "it": "Nascondi titolo video",
            "ja": "ビデオタイトルを隠す",
            "ko": "비디오 제목 숨기기",
            "ms": "Sembunyikan Tajuk Video",
            "nb": "Skjul videotittel",
            "pl": "Ukryj tytuł wideo",
            "pt": "Ocultar título do vídeo",
            "ro": "Ascundeți titlul videoclipului",
            "ru": "Скрыть название видео",
            "sk": "Skryť názov videa",
            "es": "Ocultar título del vídeo",
            "sv": "Dölj videotitel",
            "th": "ซ่อนชื่อวิดีโอ",
            "tr": "Video Başlığını Gizle",
            "uk": "Приховати назву відео",
            "vi": "Ẩn tiêu đề video"
          },
        id: "untrap_embed_player_hide_video_title",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء وقت الفيديو",
            "ca": "Amaga el temps del vídeo",
            "zh-CN": "隐藏视频时间",
            "zh-TW": "隱藏影片時間",
            "hr": "Sakrij vrijeme videa",
            "cs": "Skrýt čas videa",
            "da": "Skjul videotid",
            "nl": "Videotijd verbergen",
            "en": "Hide Video Time",
            "fi": "Piilota videon aika",
            "fr": "Masquer l'heure de la vidéo",
            "de": "Videozeit ausblenden",
            "el": "Απόκρυψη ώρας βίντεο",
            "he": "הסתר זמן וידאו",
            "hi": "वीडियो का समय छिपाएँ",
            "hu": "Videóidő elrejtése",
            "id": "Sembunyikan Waktu Video",
            "it": "Nascondi durata video",
            "ja": "ビデオ時間を隠す",
            "ko": "비디오 시간 숨기기",
            "ms": "Sembunyikan Masa Video",
            "nb": "Skjul videotid",
            "pl": "Ukryj czas wideo",
            "pt": "Ocultar tempo de vídeo",
            "ro": "Ascundeți timpul video",
            "ru": "Скрыть время видео",
            "sk": "Skryť čas videa",
            "es": "Ocultar tiempo de vídeo",
            "sv": "Dölj videotid",
            "th": "ซ่อนเวลาวิดีโอ",
            "tr": "Video Zamanını Gizle",
            "uk": "Приховати час відео",
            "vi": "Ẩn thời gian video"
          },
        id: "untrap_embed_player_hide_video_time",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الصورة الرمزية للقناة",
            "ca": "Amaga l'avatar del canal",
            "zh-CN": "隐藏频道头像",
            "zh-TW": "隱藏頻道頭像",
            "hr": "Sakrij avatar kanala",
            "cs": "Skrýt avatara kanálu",
            "da": "Skjul kanalsavatar",
            "nl": "Kanaalavatar verbergen",
            "en": "Hide Channel Avatar",
            "fi": "Piilota kanavan avatar",
            "fr": "Masquer l'avatar de la chaîne",
            "de": "Kanal-Avatar ausblenden",
            "el": "Απόκρυψη Avatar καναλιού",
            "he": "הסתר את אוואטר הערוץ",
            "hi": "चैनल अवतार छिपाएँ",
            "hu": "Csatorna Avatar elrejtése",
            "id": "Sembunyikan Avatar Saluran",
            "it": "Nascondi l'avatar del canale",
            "ja": "チャンネルアバターを隠す",
            "ko": "채널 아바타 숨기기",
            "ms": "Sembunyikan Avatar Saluran",
            "nb": "Skjul kanalavatar",
            "pl": "Ukryj awatar kanału",
            "pt": "Ocultar avatar do canal",
            "ro": "Ascundeți avatarul canalului",
            "ru": "Скрыть аватар канала",
            "sk": "Skryť avatara kanála",
            "es": "Ocultar avatar del canal",
            "sv": "Dölj kanalavatar",
            "th": "ซ่อนอวตารของช่อง",
            "tr": "Kanal Avatarını Gizle",
            "uk": "Приховати аватар каналу",
            "vi": "Ẩn hình đại diện kênh"
          },
        id: "untrap_embed_player_hide_channel_avatar",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء العلامة المائية",
            "ca": "Amaga la marca d'aigua",
            "zh-CN": "隐藏水印",
            "zh-TW": "隱藏浮水印",
            "hr": "Sakrij vodeni žig",
            "cs": "Skrýt vodoznak",
            "da": "Skjul vandmærke",
            "nl": "Watermerk verbergen",
            "en": "Hide Watermark",
            "fi": "Piilota vesileima",
            "fr": "Masquer le filigrane",
            "de": "Wasserzeichen ausblenden",
            "el": "Απόκρυψη υδατογραφήματος",
            "he": "הסתר סימן מים",
            "hi": "वॉटरमार्क छिपाएँ",
            "hu": "Vízjel elrejtése",
            "id": "Sembunyikan Tanda Air",
            "it": "Nascondi filigrana",
            "ja": "透かしを隠す",
            "ko": "워터마크 숨기기",
            "ms": "Sembunyikan Tera Air",
            "nb": "Skjul vannmerke",
            "pl": "Ukryj znak wodny",
            "pt": "Ocultar marca d’água",
            "ro": "Ascunde filigran",
            "ru": "Скрыть водяной знак",
            "sk": "Skryť vodoznak",
            "es": "Ocultar marca de agua",
            "sv": "Dölj vattenstämpel",
            "th": "ซ่อนลายน้ำ",
            "tr": "Filigranı Gizle",
            "uk": "Приховати водяний знак",
            "vi": "Ẩn hình mờ"
          },
        id: "untrap_embed_player_hide_video_watermark",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'المشاهدة على اليوتيوب'",
            "ca": "Amaga el botó 'Mira a YouTube'",
            "zh-CN": "隐藏“在 YouTube 上观看”按钮",
            "zh-TW": "隱藏「在 YouTube 上觀看」按鈕",
            "hr": "Sakrij gumb 'Gledaj na YouTubeu'",
            "cs": "Skrýt tlačítko „Sledovat na YouTube“",
            "da": "Skjul knappen 'Se på YouTube'",
            "nl": "Verberg de knop 'Bekijken op YouTube'",
            "en": "Hide 'Watch on YouTube' Button",
            "fi": "Piilota Katso YouTubessa -painike",
            "fr": "Masquer le bouton « Regarder sur YouTube »",
            "de": "Schaltfläche „Auf YouTube ansehen“ ausblenden",
            "el": "Απόκρυψη του κουμπιού 'Παρακολούθηση στο YouTube'",
            "he": "הסתר את הלחצן 'צפה ב-YouTube'",
            "hi": "'यूट्यूब पर देखें' बटन छुपाएं",
            "hu": "A „Megtekintés a YouTube-on” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Tonton di YouTube'",
            "it": "Nascondi il pulsante 'Guarda su YouTube'",
            "ja": "「YouTube で見る」ボタンを非表示にする",
            "ko": "'YouTube에서 보기' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Tonton di YouTube'",
            "nb": "Skjul 'Se på YouTube'-knappen",
            "pl": "Ukryj przycisk „Oglądaj na YouTube”",
            "pt": "Ocultar o botão 'Assistir no YouTube'",
            "ro": "Ascundeți butonul „Vizionați pe YouTube”",
            "ru": "Скрыть кнопку «Смотреть на YouTube»",
            "sk": "Skryť tlačidlo „Pozerať na YouTube“",
            "es": "Ocultar el botón 'Ver en YouTube'",
            "sv": "Dölj 'Titta på YouTube'-knappen",
            "th": "ซ่อนปุ่ม 'ดูบน YouTube'",
            "tr": "'YouTube'da İzle' Düğmesini Gizle",
            "uk": "Сховати кнопку «Дивитися на YouTube»",
            "vi": "Ẩn nút 'Xem trên YouTube'"
          },
        id: "untrap_embed_player_hide_watch_on_youtube_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'يوتيوب'",
            "ca": "Amaga el botó 'YouTube'",
            "zh-CN": "隐藏“YouTube”按钮",
            "zh-TW": "隱藏“YouTube”按鈕",
            "hr": "Sakrij gumb 'YouTube'",
            "cs": "Skrýt tlačítko „YouTube“",
            "da": "Skjul knappen 'YouTube'",
            "nl": "Knop 'YouTube' verbergen",
            "en": "Hide 'YouTube' Button",
            "fi": "Piilota 'YouTube'-painike",
            "fr": "Masquer le bouton « YouTube »",
            "de": "„YouTube“-Schaltfläche ausblenden",
            "el": "Απόκρυψη κουμπιού 'YouTube'",
            "he": "הסתר את כפתור 'YouTube'",
            "hi": "'यूट्यूब' बटन छुपाएं",
            "hu": "A „YouTube” gomb elrejtése",
            "id": "Sembunyikan Tombol 'YouTube'",
            "it": "Nascondi il pulsante 'YouTube'",
            "ja": "「YouTube」ボタンを隠す",
            "ko": "'YouTube' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'YouTube'",
            "nb": "Skjul 'YouTube'-knappen",
            "pl": "Ukryj przycisk „YouTube”",
            "pt": "Ocultar botão 'YouTube'",
            "ro": "Ascundeți butonul „YouTube”",
            "ru": "Скрыть кнопку «YouTube»",
            "sk": "Skryť tlačidlo „YouTube“",
            "es": "Ocultar el botón 'YouTube'",
            "sv": "Dölj 'YouTube'-knappen",
            "th": "ซ่อนปุ่ม 'YouTube'",
            "tr": "'YouTube' Düğmesini Gizle",
            "uk": "Приховати кнопку 'YouTube'",
            "vi": "Ẩn nút 'YouTube'"
          },
        id: "untrap_embed_player_hide_button_youtube",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'تشغيل / إيقاف مؤقت / إعادة التشغيل'",
            "ca": "Amaga el botó 'Reprodueix / Pausa / Reprodueix'",
            "zh-CN": "隐藏“播放/暂停/重播”按钮",
            "zh-TW": "隱藏“播放/暫停/重播”按鈕",
            "hr": "Sakrij gumb 'Reprodukcija / Pauza / Ponovno reproduciraj'",
            "cs": "Skrýt tlačítko 'Přehrát / Pozastavit / Přehrát znovu'",
            "da": "Skjul knappen 'Afspil / Pause / Afspil igen'",
            "nl": "Knop 'Afspelen / Pauzeren / Opnieuw afspelen' verbergen",
            "en": "Hide 'Play / Pause / Replay' Button",
            "fi": "Piilota 'Toista / Tauko / Toista' -painike",
            "fr": "Masquer le bouton « Lecture/Pause/Relecture »",
            "de": "Schaltfläche „Wiedergabe/Pause/Wiederholung“ ausblenden",
            "el": "Απόκρυψη του κουμπιού 'Αναπαραγωγή / Παύση / Επανάληψη'",
            "he": "הסתר את לחצן 'הפעל/השהה/הפעל מחדש'",
            "hi": "'चलाएँ/रोकें/पुनः चलाएँ' बटन छिपाएँ",
            "hu": "A 'Lejátszás / Szünet / Ismétlés' gomb elrejtése",
            "id": "Sembunyikan Tombol 'Putar / Jeda / Putar Ulang'",
            "it": "Nascondi il pulsante 'Riproduci/Pausa/Ripeti'",
            "ja": "「再生/一時停止/再生」ボタンを非表示にする",
            "ko": "'재생/일시정지/재생' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Main / Jeda / Main Semula'",
            "nb": "Skjul 'Spill av / Pause / Replay'-knappen",
            "pl": "Ukryj przycisk „Odtwórz/Wstrzymaj/Powtórz”",
            "pt": "Ocultar o botão 'Reproduzir/Pausar/Reproduzir'",
            "ro": "Ascundeți butonul „Redare/Pauză/Reluare”",
            "ru": "Скрыть кнопку «Воспроизведение/Пауза/Воспроизведение»",
            "sk": "Skryť tlačidlo „Prehrať / Pozastaviť / Prehrať znova“",
            "es": "Ocultar el botón 'Reproducir/Pausar/Reproducir'",
            "sv": "Dölj 'Spela / Pausa / Spela om'-knappen",
            "th": "ซ่อนปุ่ม 'เล่น / หยุดชั่วคราว / เล่นซ้ำ'",
            "tr": "'Oynat / Duraklat / Tekrar Oynat' Düğmesini Gizle",
            "uk": "Сховати кнопку «Відтворити / Пауза / Повторити»",
            "vi": "Ẩn nút 'Phát/Tạm dừng/Phát lại'"
          },
        id: "untrap_embed_player_hide_play_pause_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'مستوى الصوت'",
            "ca": "Amaga el botó 'Volum'",
            "zh-CN": "隐藏“音量”按钮",
            "zh-TW": "隱藏“音量”按鈕",
            "hr": "Sakrij gumb 'Glasnoća'",
            "cs": "Skrýt tlačítko 'Hlasitost'",
            "da": "Skjul knappen 'Lydstyrke'",
            "nl": "Knop 'Volume' verbergen",
            "en": "Hide 'Volume' Button",
            "fi": "Piilota Äänenvoimakkuus-painike",
            "fr": "Masquer le bouton 'Volume'",
            "de": "Schaltfläche „Lautstärke“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Volume'",
            "he": "הסתר את כפתור 'עוצמת הקול'",
            "hi": "'वॉल्यूम' बटन छुपाएं",
            "hu": "A „Hangerő” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Volume'",
            "it": "Nascondi il pulsante 'Volume'",
            "ja": "「音量」ボタンを隠す",
            "ko": "'볼륨' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Volume'",
            "nb": "Skjul 'Volum'-knappen",
            "pl": "Ukryj przycisk „Głośność”",
            "pt": "Ocultar botão 'Volume'",
            "ro": "Ascundeți butonul „Volum”",
            "ru": "Скрыть кнопку «Громкость»",
            "sk": "Skryť tlačidlo 'Hlasitosť'",
            "es": "Ocultar el botón 'Volumen'",
            "sv": "Dölj 'Volym'-knappen",
            "th": "ซ่อนปุ่ม 'ระดับเสียง'",
            "tr": "'Ses Düzeyi' Düğmesini Gizle",
            "uk": "Сховати кнопку «Гучність»",
            "vi": "Ẩn nút 'Âm lượng'"
          },
        id: "untrap_embed_player_hide_volume_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'التسميات التوضيحية'",
            "ca": "Amaga el botó 'Subtítols'",
            "zh-CN": "隐藏“字幕”按钮",
            "zh-TW": "隱藏“字幕”按鈕",
            "hr": "Sakrij gumb 'Titlovi'",
            "cs": "Skrýt tlačítko 'Titulky'",
            "da": "Skjul knappen 'Billedtekster'",
            "nl": "Knop 'Onderschriften' verbergen",
            "en": "Hide 'Captions' Button",
            "fi": "Piilota Tekstitykset-painike",
            "fr": "Masquer le bouton « Légendes »",
            "de": "Schaltfläche „Untertitel“ ausblenden",
            "el": "Απόκρυψη του κουμπιού 'Υπότιτλοι'",
            "he": "הסתר את לחצן 'כתוביות'",
            "hi": "'कैप्शन' बटन छिपाएँ",
            "hu": "A „Feliratok” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Keterangan'",
            "it": "Nascondi il pulsante 'Sottotitoli'",
            "ja": "「キャプション」ボタンを非表示にする",
            "ko": "'캡션' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Kapsyen'",
            "no": "Skjul 'Teksting'-knappen",
            "pl": "Ukryj przycisk „Napisy”",
            "pt": "Ocultar botão 'Legendas'",
            "ro": "Ascunde butonul „Sutitrări”",
            "ru": "Скрыть кнопку «Подписи»",
            "sk": "Skryť tlačidlo „Titulky“",
            "es": "Ocultar el botón 'Subtítulos'",
            "sv": "Dölj 'Texttext'-knappen",
            "th": "ซ่อนปุ่ม 'คำบรรยาย'",
            "tr": "'Altyazılar' Düğmesini Gizle",
            "uk": "Сховати кнопку «Підписи»",
            "vi": "Ẩn nút 'Chú thích'"
          },
        id: "untrap_embed_player_hide_subtitles_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'الإعدادات'",
            "ca": "Amaga el botó 'Configuració'",
            "zh-CN": "隐藏“设置”按钮",
            "zh-TW": "隱藏“設定”按鈕",
            "hr": "Sakrij gumb 'Postavke'",
            "cs": "Skrýt tlačítko 'Nastavení'",
            "da": "Skjul knappen 'Indstillinger'",
            "nl": "Knop 'Instellingen' verbergen",
            "en": "Hide 'Settings' Button",
            "fi": "Piilota 'Asetukset' -painike",
            "fr": "Masquer le bouton « Paramètres »",
            "de": "Schaltfläche „Einstellungen“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Ρυθμίσεις'",
            "he": "הסתר את לחצן 'הגדרות'",
            "hi": "'सेटिंग्स' बटन छुपाएं",
            "hu": "A 'Beállítások' gomb elrejtése",
            "id": "Sembunyikan Tombol 'Pengaturan'",
            "it": "Nascondi il pulsante 'Impostazioni'",
            "ja": "「設定」ボタンを非表示にする",
            "ko": "'설정' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Tetapan'",
            "nb": "Skjul 'Innstillinger'-knappen",
            "pl": "Ukryj przycisk „Ustawienia”",
            "pt": "Ocultar botão 'Configurações'",
            "ro": "Ascundeți butonul „Setări”",
            "ru": "Скрыть кнопку «Настройки»",
            "sk": "Skryť tlačidlo „Nastavenia“",
            "es": "Ocultar el botón 'Configuración'",
            "sv": "Dölj knappen 'Inställningar'",
            "th": "ซ่อนปุ่ม 'การตั้งค่า'",
            "tr": "'Ayarlar' Düğmesini Gizle",
            "uk": "Приховати кнопку «Налаштування»",
            "vi": "Ẩn nút 'Cài đặt'"
          },
        id: "untrap_embed_player_hide_settings_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'ملء الشاشة'",
            "ca": "Amaga el botó 'Pantalla completa'",
            "zh-CN": "隐藏“全屏”按钮",
            "zh-TW": "隱藏「全螢幕」按鈕",
            "hr": "Sakrij gumb 'Cijeli zaslon'",
            "cs": "Skrýt tlačítko „Celá obrazovka“",
            "da": "Skjul knappen 'Fuld skærm'",
            "nl": "Knop 'Volledig scherm' verbergen",
            "en": "Hide 'Full Screen' Button",
            "fi": "Piilota 'Koko näyttö' -painike",
            "fr": "Masquer le bouton 'Plein écran'",
            "de": "Schaltfläche „Vollbild“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Πλήρης οθόνη'",
            "he": "הסתר את כפתור 'מסך מלא'",
            "hi": "'पूर्ण स्क्रीन' बटन छिपाएँ",
            "hu": "A „Teljes képernyő” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Layar Penuh'",
            "it": "Nascondi il pulsante 'Schermo intero'",
            "ja": "「全画面」ボタンを非表示にする",
            "ko": "'전체 화면' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Skrin Penuh'",
            "nb": "Skjul 'Fullskjerm'-knappen",
            "pl": "Ukryj przycisk „Pełny ekran”",
            "pt": "Ocultar o botão 'Tela inteira'",
            "ro": "Ascundeți butonul „Ecran complet”",
            "ru": "Скрыть кнопку «Полный экран»",
            "sk": "Skryť tlačidlo „Celá obrazovka“",
            "es": "Ocultar el botón 'Pantalla completa'",
            "sv": "Dölj knappen 'Helskärm'",
            "th": "ซ่อนปุ่ม 'เต็มหน้าจอ'",
            "tr": "'Tam Ekran' Düğmesini Gizle",
            "uk": "Сховати кнопку «На весь екран»",
            "vi": "Ẩn nút 'Toàn màn hình'"
          },
        id: "untrap_embed_player_hide_full_screen_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'المشاركة'",
            "ca": "Amaga el botó 'Comparteix'",
            "zh-CN": "隐藏“分享”按钮",
            "zh-TW": "隱藏「分享」按鈕",
            "hr": "Sakrij gumb 'Dijeli'",
            "cs": "Skrýt tlačítko 'Sdílet'",
            "da": "Skjul knappen 'Del'",
            "nl": "Knop 'Delen' verbergen",
            "en": "Hide 'Share' Button",
            "fi": "Piilota 'Jaa' -painike",
            "fr": "Masquer le bouton « Partager »",
            "de": "Schaltfläche „Teilen“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Κοινή χρήση'",
            "he": "הסתר את כפתור 'שתף'",
            "hi": "'शेयर' बटन छिपाएँ",
            "hu": "A „Megosztás” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Bagikan'",
            "it": "Nascondi il pulsante 'Condividi'",
            "ja": "「共有」ボタンを非表示にする",
            "ko": "'공유' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Kongsi'",
            "nb": "Skjul 'Del'-knappen",
            "pl": "Ukryj przycisk „Udostępnij”",
            "pt": "Ocultar o botão 'Compartilhar'",
            "ro": "Ascundeți butonul „Partajare”",
            "ru": "Скрыть кнопку «Поделиться»",
            "sk": "Skryť tlačidlo 'Zdieľať'",
            "es": "Ocultar el botón 'Compartir'",
            "sv": "Dölj 'Dela'-knappen",
            "th": "ซ่อนปุ่ม 'แชร์'",
            "tr": "'Paylaş' Düğmesini Gizle",
            "uk": "Сховати кнопку «Поділитися»",
            "vi": "Ẩn nút 'Chia sẻ'"
          },
        id: "untrap_embed_hide_button_share",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'المزيد من'",
            "ca": "Amaga el botó 'Més de'",
            "zh-CN": "隐藏“更多来自”按钮",
            "zh-TW": "隱藏“更多來自”按鈕",
            "hr": "Sakrij gumb 'Više od'",
            "cs": "Skrýt tlačítko „Více z“",
            "da": "Skjul knappen 'Mere fra'",
            "nl": "Knop 'Meer van' verbergen",
            "en": "Hide 'More from' Button",
            "fi": "Piilota Lisää kohteesta -painike",
            "fr": "Masquer le bouton « Plus de »",
            "de": "Schaltfläche „Mehr von“ ausblenden",
            "el": "Απόκρυψη του κουμπιού 'Περισσότερα από'",
            "he": "הסתר את כפתור 'עוד מ'",
            "hi": "'इससे अधिक' बटन छिपाएँ",
            "hu": "A „Továbbiak innen” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Lainnya dari'",
            "it": "Nascondi il pulsante 'Altro da'",
            "ja": "「もっと見る」ボタンを非表示にする",
            "ko": "'더 보기' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Lagi daripada'",
            "nb": "Skjul 'Mer fra'-knappen",
            "pl": "Ukryj przycisk „Więcej od”",
            "pt": "Ocultar o botão 'Mais de'",
            "ro": "Ascundeți butonul „Mai multe de la”",
            "ru": "Скрыть кнопку «Больше от»",
            "sk": "Skryť tlačidlo „Viac z“",
            "es": "Ocultar el botón 'Más de'",
            "sv": "Dölj 'Mer från'-knappen",
            "th": "ซ่อนปุ่ม 'เพิ่มเติมจาก'",
            "tr": "'Daha Fazla' Düğmesini Gizle",
            "uk": "Сховати кнопку 'Більше від'",
            "vi": "Ẩn nút 'Thêm từ'"
          },
        id: "untrap_embed_hide_button_more_from",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'الإجراءات'",
            "ca": "Amaga el botó 'Accions'",
            "zh-CN": "隐藏“操作”按钮",
            "zh-TW": "隱藏“操作”按鈕",
            "hr": "Sakrij gumb 'Akcije'",
            "cs": "Skrýt tlačítko 'Akce'",
            "da": "Skjul knappen 'Handlinger'",
            "nl": "Knop 'Acties' verbergen",
            "en": "Hide 'Actions' Button",
            "fi": "Piilota 'Toiminnot'-painike",
            "fr": "Masquer le bouton « Actions »",
            "de": "Schaltfläche „Aktionen“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Ενέργειες'",
            "he": "הסתר את כפתור 'פעולות'",
            "hi": "'कार्यवाहियाँ' बटन छिपाएँ",
            "hu": "A 'Műveletek' gomb elrejtése",
            "id": "Sembunyikan Tombol 'Tindakan'",
            "it": "Nascondi il pulsante 'Azioni'",
            "ja": "「アクション」ボタンを非表示にする",
            "ko": "'작업' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Tindakan'",
            "nb": "Skjul 'Handlinger'-knappen",
            "pl": "Ukryj przycisk „Akcje”",
            "pt": "Ocultar botão 'Ações'",
            "ro": "Ascundeți butonul „Acțiuni”",
            "ru": "Скрыть кнопку «Действия»",
            "sk": "Skryť tlačidlo „Akcie“",
            "es": "Ocultar el botón 'Acciones'",
            "sv": "Dölj 'Åtgärder'-knappen",
            "th": "ซ่อนปุ่ม 'การกระทำ'",
            "tr": "'Eylemler' Düğmesini Gizle",
            "uk": "Приховати кнопку «Дії»",
            "vi": "Ẩn nút 'Hành động'"
          },
        id: "untrap_embed_hide_button_action_dots",
        defaultValue: false
    }
];

// MARK: - Builder

// Desktop

const embedDesktopGroups = [
    {
        groupName: {
            "ar": "مشغل فديوهات",
            "ca": "Reproductor de vídeo",
            "zh-CN": "视频播放器",
            "zh-TW": "影片播放器",
            "hr": "Video player",
            "cs": "Video přehrávač",
            "da": "Videoafspiller",
            "nl": "Video speler",
            "en": "Video Player",
            "fi": "Videosoitin",
            "fr": "Lecteur vidéo",
            "de": "Videoplayer",
            "el": "Βίντεο",
            "he": "נגן וידאו",
            "hi": "वीडियो प्लेयर",
            "hu": "Videó lejátszó",
            "id": "Pemutar video",
            "it": "Lettore video",
            "ja": "ビデオプレーヤー",
            "ko": "비디오 플레이어",
            "ms": "Pemain video",
            "nb": "Videospiller",
            "pl": "Odtwarzacz wideo",
            "pt": "Reprodutor de vídeo",
            "ro": "Video player",
            "ru": "Видео проигрыватель",
            "sk": "Video prehrávač",
            "es": "Reproductor de video",
            "sv": "Videospelare",
            "th": "เครื่องเล่นวีดีโอ",
            "tr": "Video oynatıcı",
            "uk": "Відеоплеєр",
            "vi": "Trình phát video"
          },
        groupId: "player",
        parentCategoryId: "embed",
        options: embedDesktopGroups_Player
    }
];
