// MARK: - Desktop Groups

const homePageDesktopGroups_Redirects = [
    {
        type: "select",
        
        name: {
                "ar": "الصفحة الرئيسية هي",
                "ca": "La pàgina d'inici és",
                "zh-CN": "主页是",
                "zh-TW": "主頁是",
                "hr": "Početna stranica je",
                "cs": "Domovská stránka je",
                "da": "Hjemmesiden er",
                "nl": "Startpagina is",
                "en": "Home Page is",
                "fi": "Kotisivu on",
                "fr": "La page d'accueil est",
                "de": "Startseite ist",
                "el": "Η αρχική σελίδα είναι",
                "he": "דף הבית הוא",
                "hi": "होम पेज है",
                "hu": "A kezdőlap az",
                "id": "Halaman Beranda adalah",
                "it": "La pagina iniziale è",
                "ja": "ホームページは",
                "ko": "홈 페이지는 다음과 같습니다.",
                "ms": "Laman Utama ialah",
                "nb": "Hjemmesiden er",
                "pl": "Strona główna jest",
                "pt": "A página inicial é",
                "ro": "Pagina de pornire este",
                "ru": "Домашняя страница",
                "sk": "Domovská stránka je",
                "es": "La página de inicio es",
                "sv": "Hemsidan är",
                "th": "หน้าแรกคือ",
                "tr": "Ana Sayfa:",
                "uk": "Домашня сторінка є",
                "vi": "Trang chủ là"
              },
        
        id: "untrap_redirect_home_to",
        defaultValue: "home",
        selects: [
            {
                name: {
                        "ar": "الصفحة الرئيسية",
                        "ca": "Pàgina d'inici",
                        "zh-CN": "主页",
                        "zh-TW": "首頁",
                        "hr": "Početna stranica",
                        "cs": "Domovská stránka",
                        "da": "Hjemmeside",
                        "nl": "Startpagina",
                        "en": "Home Page",
                        "fi": "Kotisivu",
                        "fr": "Page d'accueil",
                        "de": "Startseite",
                        "el": "Αρχική Σελίδα",
                        "he": "דף הבית",
                        "hi": "होम पेज",
                        "hu": "Kezdőlap",
                        "id": "Halaman Beranda",
                        "it": "Pagina iniziale",
                        "ja": "ホームページ",
                        "ko": "홈 페이지",
                        "ms": "Halaman Utama",
                        "nb": "Hjemmeside",
                        "pl": "Strona główna",
                        "pt": "Pagina inicial",
                        "ro": "Pagina principala",
                        "ru": "Домашняя страница",
                        "sk": "Domovská stránka",
                        "es": "Página de inicio",
                        "sv": "Hemsida",
                        "th": "หน้าแรก",
                        "tr": "Ana Sayfa",
                        "uk": "Домашня сторінка",
                        "vi": "Trang chủ"
                  },
                id: "home"
            },
            {
                name: {
                    "ar": "صفحة الاشتراكات",
                    "ca": "Pàgina de subscripcions",
                    "zh-CN": "订阅页面",
                    "zh-TW": "訂閱頁面",
                    "hr": "Stranica pretplata",
                    "cs": "Stránka odběrů",
                    "da": "Side med abonnementer",
                    "nl": "Abonnementenpagina",
                    "en": "Subscriptions Page",
                    "fi": "Tilaukset-sivu",
                    "fr": "Page d'abonnements",
                    "de": "Seite „Abonnements“.",
                    "el": "Σελίδα συνδρομών",
                    "he": "עמוד מנויים",
                    "hi": "सदस्यता पृष्ठ",
                    "hu": "Előfizetések oldal",
                    "id": "Halaman Langganan",
                    "it": "Pagina Abbonamenti",
                    "ja": "定期購入ページ",
                    "ko": "구독 페이지",
                    "ms": "Halaman Langganan",
                    "nb": "Abonnementsside",
                    "pl": "Strona subskrypcji",
                    "pt": "Página de assinaturas",
                    "ro": "Pagina de abonamente",
                    "ru": "Страница подписок",
                    "sk": "Stránka odberov",
                    "es": "Página de suscripciones",
                    "sv": "Prenumerationssida",
                    "th": "หน้าสมัครสมาชิก",
                    "tr": "Abonelikler Sayfası",
                    "uk": "Сторінка підписки",
                    "vi": "Trang đăng ký"
                  },
                id: "subscriptions"
            },
            {
                name: {
                    "ar": "مشاهدة الصفحة لاحقا",
                    "ca": "Veure la pàgina més tard",
                    "zh-CN": "稍后观看页面",
                    "zh-TW": "稍後觀看頁面",
                    "hr": "Stranica Gledaj kasnije",
                    "cs": "Stránka Přehrát později",
                    "da": "Se senere side",
                    "nl": "Bekijk de latere pagina",
                    "en": "Watch Later Page",
                    "fi": "Katso myöhemmin -sivu",
                    "fr": "Page à regarder plus tard",
                    "de": "Seite „Später ansehen“",
                    "el": "Παρακολούθηση Σελίδας αργότερα",
                    "he": "צפה בעמוד מאוחר יותר",
                    "hi": "बाद वाला पेज देखें",
                    "hu": "Nézd később oldal",
                    "id": "Tonton Halaman Nanti",
                    "it": "Guarda la pagina successiva",
                    "ja": "後で見るページ",
                    "ko": "나중에 볼 페이지",
                    "ms": "Tonton Halaman Kemudian",
                    "nb": "Se senere side",
                    "pl": "Obejrzyj późniejszą stronę",
                    "pt": "Assistir mais tarde página",
                    "ro": "Vizionați pagina mai târziu",
                    "ru": "Страница просмотра позже",
                    "sk": "Stránka Pozrieť neskôr",
                    "es": "Ver página más tarde",
                    "sv": "Titta senare sida",
                    "th": "ดูหน้าภายหลัง",
                    "tr": "Daha Sonra İzle Sayfası",
                    "uk": "Сторінка 'Переглянути пізніше'.",
                    "vi": "Xem trang sau"
                  },
                id: "watch_later"
            },
            {
                name: {
                    "ar": "صفحة البحث",
                    "ca": "Pàgina de cerca",
                    "zh-CN": "搜索页",
                    "zh-TW": "搜尋頁",
                    "hr": "Stranica za pretraživanje",
                    "cs": "Stránka vyhledávání",
                    "da": "Søgeside",
                    "nl": "Zoekpagina",
                    "en": "Search Page",
                    "fi": "Hakusivu",
                    "fr": "Page de recherche",
                    "de": "Suchseite",
                    "el": "Αναζήτηση σελίδας",
                    "he": "דף חיפוש",
                    "hi": "पृष्ठ खोजें",
                    "hu": "Keresés oldal",
                    "id": "Halaman Pencarian",
                    "it": "Pagina di ricerca",
                    "ja": "検索ページ",
                    "ko": "검색 페이지",
                    "ms": "Halaman Carian",
                    "nb": "Søkeside",
                    "pl": "Strona wyszukiwania",
                    "pt": "Página de pesquisa",
                    "ro": "Pagina de căutare",
                    "ru": "Страница поиска",
                    "sk": "Stránka vyhľadávania",
                    "es": "Página de búsqueda",
                    "sv": "Söksida",
                    "th": "หน้าการค้นหา",
                    "tr": "Arama Sayfası",
                    "uk": "Сторінка пошуку",
                    "vi": "Trang tìm kiếm"
                  },
                id: "search"
            },
            {
                name: {
                    "ar": "الصفحة الشائعة",
                    "ca": "Pàgina de tendències",
                    "zh-CN": "热门页面",
                    "zh-TW": "熱門頁面",
                    "hr": "Stranica u trendu",
                    "cs": "Trendová stránka",
                    "da": "Trending side",
                    "nl": "Trending-pagina",
                    "en": "Trending Page",
                    "fi": "Trendaavat sivut",
                    "fr": "Page tendance",
                    "de": "Trendseite",
                    "el": "Τάσεις σελίδας",
                    "he": "עמוד פופולרי",
                    "hi": "ट्रेंडिंग पेज",
                    "hu": "Felkapott oldal",
                    "id": "Halaman Tren",
                    "it": "Pagina di tendenza",
                    "ja": "トレンドページ",
                    "ko": "인기 페이지",
                    "ms": "Halaman Arah Aliran",
                    "nb": "Trendende side",
                    "pl": "Strona z trendami",
                    "pt": "Página de tendências",
                    "ro": "Pagina de tendințe",
                    "ru": "Популярная страница",
                    "sk": "Populárna stránka",
                    "es": "Página de tendencias",
                    "sv": "Trendig sida",
                    "th": "เพจที่กำลังมาแรง",
                    "tr": "Trend Sayfası",
                    "uk": "Популярна сторінка",
                    "vi": "Trang thịnh hành"
                  },
                id: "trending"
            },
            {
                name: {
                    "ar": "صفحة التاريخ",
                    "ca": "Pàgina d'història",
                    "zh-CN": "历史页面",
                    "zh-TW": "歷史頁面",
                    "hr": "Stranica povijesti",
                    "cs": "Stránka historie",
                    "da": "Historie side",
                    "nl": "Geschiedenispagina",
                    "en": "History Page",
                    "fi": "Historia-sivu",
                    "fr": "Page d'historique",
                    "de": "Geschichtsseite",
                    "el": "Σελίδα Ιστορίας",
                    "he": "עמוד היסטוריה",
                    "hi": "इतिहास पृष्ठ",
                    "hu": "Történelem oldal",
                    "id": "Halaman Sejarah",
                    "it": "Pagina della storia",
                    "ja": "履歴ページ",
                    "ko": "역사 페이지",
                    "ms": "Halaman Sejarah",
                    "nb": "Historieside",
                    "pl": "Strona historii",
                    "pt": "Página de histórico",
                    "ro": "Pagina de istorie",
                    "ru": "Страница истории",
                    "sk": "Stránka histórie",
                    "es": "Página de historia",
                    "sv": "Historik sida",
                    "th": "หน้าประวัติศาสตร์",
                    "tr": "Geçmiş Sayfası",
                    "uk": "Сторінка історії",
                    "vi": "Trang lịch sử"
                  },
                id: "history"
            },
            {
                name: {
                    "ar": "الصفحة التي تم الإعجاب بها",
                    "ca": "Pàgina M'agrada",
                    "zh-CN": "喜欢的页面",
                    "zh-TW": "喜歡的頁面",
                    "hr": "Svidjela mi se stranica",
                    "cs": "Stránka, která se vám líbí",
                    "da": "Synes godt om side",
                    "nl": "Pagina leuk gevonden",
                    "en": "Liked Page",
                    "fi": "Tykkää sivusta",
                    "fr": "Page aimée",
                    "de": "Gefällt mir Seite",
                    "el": "Σελίδα που άρεσε",
                    "he": "עמוד לייק",
                    "hi": "पेज पसंद आया",
                    "hu": "Kedvelt oldal",
                    "id": "Halaman yang Disukai",
                    "it": "Pagina piaciuta",
                    "ja": "気に入ったページ",
                    "ko": "좋아요를 누른 페이지",
                    "ms": "Halaman Suka",
                    "nb": "Likte siden",
                    "pl": "Polubiona strona",
                    "pt": "Página curtida",
                    "ro": "Pagină apreciată",
                    "ru": "Понравившаяся страница",
                    "sk": "Stránka, ktorá sa vám páči",
                    "es": "Página que me gustó",
                    "sv": "Gillade sidan",
                    "th": "ถูกใจเพจ",
                    "tr": "Beğenilen Sayfa",
                    "uk": "Сподобалася сторінка",
                    "vi": "Trang đã thích"
                  },
                id: "liked"
            },
            {
                name: {
                    "ar": "صفحة المكتبة",
                    "ca": "Pàgina de la Biblioteca",
                    "zh-CN": "图书馆页面",
                    "zh-TW": "圖書館頁面",
                    "hr": "Stranica knjižnice",
                    "cs": "Stránka knihovny",
                    "da": "Biblioteksside",
                    "nl": "Bibliotheekpagina",
                    "en": "Library Page",
                    "fi": "Kirjaston sivu",
                    "fr": "Page de la bibliothèque",
                    "de": "Bibliotheksseite",
                    "el": "Σελίδα βιβλιοθήκης",
                    "he": "עמוד ספריה",
                    "hi": "लाइब्रेरी पेज",
                    "hu": "Könyvtár oldala",
                    "id": "Halaman Perpustakaan",
                    "it": "Pagina della biblioteca",
                    "ja": "ライブラリページ",
                    "ko": "도서관 페이지",
                    "ms": "Halaman Perpustakaan",
                    "nb": "Bibliotekside",
                    "pl": "Strona Biblioteki",
                    "pt": "Página da Biblioteca",
                    "ro": "Pagina Bibliotecii",
                    "ru": "Страница библиотеки",
                    "sk": "Stránka knižnice",
                    "es": "Página de la biblioteca",
                    "sv": "Bibliotekssida",
                    "th": "หน้าห้องสมุด",
                    "tr": "Kütüphane Sayfası",
                    "uk": "Сторінка бібліотеки",
                    "vi": "Trang thư viện"
                  },
                id: "library"
            }
        ]
    }
]

const homePageDesktopGroups_Suggestions = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الاقتراحات",
            "ca": "Amaga suggeriments",
            "zh-CN": "隐藏建议",
            "zh-TW": "隱藏建議",
            "hr": "Sakrij prijedloge",
            "cs": "Skrýt návrhy",
            "da": "Skjul forslag",
            "nl": "Suggesties verbergen",
            "en": "Hide Suggestions",
            "fi": "Piilota ehdotukset",
            "fr": "Masquer les suggestions",
            "de": "Vorschläge ausblenden",
            "el": "Απόκρυψη προτάσεων",
            "he": "הסתר הצעות",
            "hi": "सुझाव छिपाएँ",
            "hu": "Javaslatok elrejtése",
            "id": "Sembunyikan Saran",
            "it": "Nascondi suggerimenti",
            "ja": "提案を非表示にする",
            "ko": "제안 숨기기",
            "ms": "Sembunyikan Cadangan",
            "nb": "Skjul forslag",
            "pl": "Ukryj sugestie",
            "pt": "Ocultar sugestões",
            "ro": "Ascundeți sugestiile",
            "ru": "Скрыть предложения",
            "sk": "Skryť návrhy",
            "es": "Ocultar sugerencias",
            "sv": "Dölj förslag",
            "th": "ซ่อนคำแนะนำ",
            "tr": "Önerileri Gizle",
            "uk": "Приховати пропозиції",
            "vi": "Ẩn đề xuất"
          },
        id: "untrap_home_hide_suggestions",
        defaultValue: false,
        childOffOptions: [
            {
                type: "select",
                name: {
                    "ar": "الصفوف",
                    "ca": "Files",
                    "zh-CN": "行数",
                    "zh-TW": "行數",
                    "hr": "Redovi",
                    "cs": "Řádky",
                    "da": "Rækker",
                    "nl": "Rijen",
                    "en": "Rows",
                    "fi": "Rivit",
                    "fr": "Lignes",
                    "de": "Reihen",
                    "el": "Σειρές",
                    "he": "שורות",
                    "hi": "पंक्तियों",
                    "hu": "Sorok",
                    "id": "Baris",
                    "it": "Righe",
                    "ja": "行",
                    "ko": "행",
                    "ms": "Baris",
                    "no": "Rader",
                    "pl": "Wydziwianie",
                    "pt": "Linhas",
                    "ro": "Rânduri",
                    "ru": "Строки",
                    "sk": "Riadky",
                    "es": "Filas",
                    "sv": "Rader",
                    "th": "แถว",
                    "tr": "Satırlar",
                    "uk": "Рядки",
                    "vi": "Hàng"
                  },
                id: "untrap_home_suggestions_rows_count",
                defaultValue: "default",
                selects: [
                    {
                        name: {
                            "ar": "تقصير",
                            "ca": "Per defecte",
                            "zh-CN": "默认",
                            "zh-TW": "預設",
                            "hr": "Zadano",
                            "cs": "Výchozí",
                            "da": "Standard",
                            "nl": "Standaard",
                            "en": "Default",
                            "fi": "Oletus",
                            "fr": "Défaut",
                            "de": "Standard",
                            "el": "Προκαθορισμένο",
                            "he": "בְּרִירַת מֶחדָל",
                            "hi": "गलती करना",
                            "hu": "Alapértelmezett",
                            "id": "Bawaan",
                            "it": "Predefinito",
                            "ja": "デフォルト",
                            "ko": "기본",
                            "ms": "Lalai",
                            "nb": "Misligholde",
                            "pl": "Domyślny",
                            "pt": "Padrão",
                            "ro": "Mod implicit",
                            "ru": "По умолчанию",
                            "sk": "Predvolené",
                            "es": "Por defecto",
                            "sv": "Standard",
                            "th": "ค่าเริ่มต้น",
                            "tr": "Varsayılan",
                            "uk": "За замовчуванням",
                            "vi": "Mặc định"
                          },
                        id: "default"
                    },
                    {
                        name: {
                            "ar": "تعطيل التمرير اللانهائي",
                            "ca": "Desactiva el desplaçament infinit",
                            "zh-CN": "禁用无限滚动",
                            "zh-TW": "禁用無限滾動",
                            "hr": "Onemogući beskonačno pomicanje",
                            "cs": "Zakázat nekonečné posouvání",
                            "da": "Deaktiver uendelig rulning",
                            "nl": "Schakel Oneindig scrollen uit",
                            "en": "Disable Infinite Scrolling",
                            "fi": "Poista ääretön vieritys käytöstä",
                            "fr": "Désactiver le défilement infini",
                            "de": "Deaktivieren Sie das unendliche Scrollen",
                            "el": "Απενεργοποιήστε την άπειρη κύλιση",
                            "he": "השבת את הגלילה האינסופית",
                            "hi": "अनंत स्क्रॉलिंग अक्षम करें",
                            "hu": "A végtelen görgetés letiltása",
                            "id": "Nonaktifkan Pengguliran Tak Terbatas",
                            "it": "Disabilita lo scorrimento infinito",
                            "ja": "無限スクロールを無効にする",
                            "ko": "무한 스크롤 비활성화",
                            "ms": "Lumpuhkan Tatal Infinite",
                            "nb": "Deaktiver uendelig rulling",
                            "pl": "Wyłącz nieskończone przewijanie",
                            "pt": "Desativar rolagem infinita",
                            "ro": "Dezactivați derularea infinită",
                            "ru": "Отключить бесконечную прокрутку",
                            "sk": "Zakázať nekonečné posúvanie",
                            "es": "Desactivar el desplazamiento infinito",
                            "sv": "Inaktivera oändlig rullning",
                            "th": "ปิดการใช้งานการเลื่อนแบบไม่มีที่สิ้นสุด",
                            "tr": "Sonsuz Kaydırmayı Devre Dışı Bırak",
                            "uk": "Вимкніть нескінченне прокручування",
                            "vi": "Vô hiệu hóa cuộn vô hạn"
                          },
                        id: "preloadedRows"
                    },
                    {
                        name: {
                            "ar": "1 صف",
                            "ca": "1 fila",
                            "zh-CN": "1 行",
                            "zh-TW": "1 行",
                            "hr": "1 red",
                            "cs": "1 řádek",
                            "da": "1 række",
                            "nl": "1 rij",
                            "en": "1 Row",
                            "fi": "1 rivi",
                            "fr": "1 rangée",
                            "de": "1 Reihe",
                            "el": "1 Σειρά",
                            "he": "1 שורה",
                            "hi": "1 पंक्ति",
                            "hu": "1 sor",
                            "id": "1 baris",
                            "it": "1 riga",
                            "ja": "1列",
                            "ko": "1행",
                            "ms": "1 Baris",
                            "nb": "1 rad",
                            "pl": "1 rząd",
                            "pt": "1 linha",
                            "ro": "1 rând",
                            "ru": "1 ряд",
                            "sk": "1 riadok",
                            "es": "1 fila",
                            "sv": "1 rad",
                            "th": "1 แถว",
                            "tr": "1 Sıra",
                            "uk": "1 ряд",
                            "vi": "1 hàng"
                          },
                        id: "row_1"
                    },
                    {
                        name: {
                            "ar": "2 صفوف",
                            "ca": "2 files",
                            "zh-CN": "2 行",
                            "zh-TW": "2 行",
                            "hr": "2 reda",
                            "cs": "2 řádky",
                            "da": "2 rækker",
                            "nl": "2 rijen",
                            "en": "2 Rows",
                            "fi": "2 riviä",
                            "fr": "2 rangées",
                            "de": "2 Reihen",
                            "el": "2 σειρές",
                            "he": "2 שורות",
                            "hi": "2 पंक्तियाँ",
                            "hu": "2 sor",
                            "id": "2 Baris",
                            "it": "2 righe",
                            "ja": "2列",
                            "ko": "2줄",
                            "ms": "2 Baris",
                            "nb": "2 rader",
                            "pl": "2 rzędy",
                            "pt": "2 linhas",
                            "ro": "2 rânduri",
                            "ru": "2 ряда",
                            "sk": "2 riadky",
                            "es": "2 filas",
                            "sv": "2 rader",
                            "th": "2 แถว",
                            "tr": "2 Sıra",
                            "uk": "2 рядки",
                            "vi": "2 hàng"
                          },
                        id: "row_2"
                    }
                ]
            },
            
            {
                type: "select",
                name: {
                    "ar": "أعمدة",
                    "ca": "Columnes",
                    "zh-CN": "专栏",
                    "zh-TW": "專欄",
                    "hr": "Stupci",
                    "cs": "Sloupce",
                    "da": "Kolonner",
                    "nl": "Kolommen",
                    "en": "Columns",
                    "fi": "Sarakkeet",
                    "fr": "Colonnes",
                    "de": "Spalten",
                    "el": "Στήλες",
                    "he": "עמודות",
                    "hi": "कॉलम",
                    "hu": "Oszlopok",
                    "id": "Kolom",
                    "it": "Colonne",
                    "ja": "コラム",
                    "ko": "열",
                    "ms": "Lajur",
                    "no": "Kolonner",
                    "pl": "Kolumny",
                    "pt": "Colunas",
                    "ro": "Coloane",
                    "ru": "Столбцы",
                    "sk": "Stĺpce",
                    "es": "Columnas",
                    "sv": "Kolumner",
                    "th": "คอลัมน์",
                    "tr": "Sütunlar",
                    "uk": "Стовпці",
                    "vi": "Cột"
                  },
                id: "untrap_home_suggestions_columns_count",
                defaultValue: "default",
                selects: [
                    {
                        name: "1",
                        id: "1"
                    },
                    {
                        name: "2",
                        id: "2"
                    },
                    {
                        name: "3",
                        id: "3"
                    },
                    {
                        name: "4",
                        id: "4"
                    },
                    {
                        name: "5",
                        id: "5"
                    },
                    {
                        name: "6",
                        id: "6"
                    },
                    {
                        name: "7",
                        id: "7"
                    },
                    {
                        name: "8",
                        id: "8"
                    },
                    {
                        name: "9",
                        id: "9"
                    },
                    {
                        name: "10",
                        id: "10"
                    },
                    {
                        name: "11",
                        id: "11"
                    },
                    {
                        name: "12",
                        id: "12"
                    },
                    {
                        name: "13",
                        id: "13"
                    },
                    {
                        name: "14",
                        id: "14"
                    },
                    {
                        name: "15",
                        id: "15"
                    }
                ]
            },
            
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء فئات الاقتراحات",
                    "ca": "Amaga les categories de suggeriments",
                    "zh-CN": "隐藏建议类别",
                    "zh-TW": "隱藏建議類別",
                    "hr": "Sakrij kategorije prijedloga",
                    "cs": "Skrýt kategorie návrhů",
                    "da": "Skjul forslagskategorier",
                    "nl": "Suggestiecategorieën verbergen",
                    "en": "Hide Suggestions Categories",
                    "fi": "Piilota ehdotuskategoriat",
                    "fr": "Masquer les catégories de suggestions",
                    "de": "Vorschlagskategorien ausblenden",
                    "el": "Απόκρυψη κατηγοριών προτάσεων",
                    "he": "הסתר קטגוריות הצעות",
                    "hi": "सुझाव श्रेणियाँ छिपाएँ",
                    "hu": "Javaslatok kategóriák elrejtése",
                    "id": "Sembunyikan Kategori Saran",
                    "it": "Nascondi le categorie dei suggerimenti",
                    "ja": "提案のカテゴリを非表示にする",
                    "ko": "제안 카테고리 숨기기",
                    "ms": "Sembunyikan Kategori Cadangan",
                    "nb": "Skjul forslagskategorier",
                    "pl": "Ukryj kategorie sugestii",
                    "pt": "Ocultar categorias de sugestões",
                    "ro": "Ascundeți categoriile de sugestii",
                    "ru": "Скрыть категории предложений",
                    "sk": "Skryť kategórie návrhov",
                    "es": "Ocultar categorías de sugerencias",
                    "sv": "Dölj förslagskategorier",
                    "th": "ซ่อนหมวดหมู่คำแนะนำ",
                    "tr": "Öneri Kategorilerini Gizle",
                    "uk": "Приховати категорії пропозицій",
                    "vi": "Ẩn danh mục đề xuất"
                  },
                id: "untrap_home_hide_header_with_categories",
                defaultValue: false
            },
            
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء مقاطع الفيديو التي تمت مشاهدتها",
                    "ca": "Amaga els vídeos vists",
                    "zh-CN": "隐藏观看过的视频",
                    "zh-TW": "隱藏觀看過的視頻",
                    "hr": "Sakrij gledane videozapise",
                    "cs": "Skrýt sledovaná videa",
                    "da": "Skjul sete videoer",
                    "nl": "Verberg bekeken video's",
                    "en": "Hide Watched Videos",
                    "fi": "Piilota katsotut videot",
                    "fr": "Masquer les vidéos regardées",
                    "de": "Angesehene Videos ausblenden",
                    "el": "Απόκρυψη βίντεο που παρακολουθήσατε",
                    "he": "הסתר סרטונים שנצפו",
                    "hi": "देखे गए वीडियो छुपाएं",
                    "hu": "Megtekintett videók elrejtése",
                    "id": "Sembunyikan Video yang Ditonton",
                    "it": "Nascondi i video guardati",
                    "ja": "視聴したビデオを非表示にする",
                    "ko": "시청한 동영상 숨기기",
                    "ms": "Sembunyikan Video yang Ditonton",
                    "nb": "Skjul sett videoer",
                    "pl": "Ukryj oglądane filmy",
                    "pt": "Ocultar vídeos assistidos",
                    "ro": "Ascunde videoclipurile vizionate",
                    "ru": "Скрыть просмотренные видео",
                    "sk": "Skryť sledované videá",
                    "es": "Ocultar vídeos vistos",
                    "sv": "Dölj sedda videor",
                    "th": "ซ่อนวิดีโอที่ดู",
                    "tr": "İzlenen Videoları Gizle",
                    "uk": "Приховати переглянуті відео",
                    "vi": "Ẩn video đã xem"
                  },
                id: "untrap_home_hide_watched_videos",
                defaultValue: false
            },
            
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء قوائم التشغيل والمزج",
                    "ca": "Amaga llistes de reproducció i mescles",
                    "zh-CN": "隐藏播放列表和混音",
                    "zh-TW": "隱藏播放清單和混音",
                    "hr": "Sakrij popise za reprodukciju i mikseve",
                    "cs": "Skrýt seznamy skladeb a mixy",
                    "da": "Skjul afspilningslister og mix",
                    "nl": "Verberg afspeellijsten en mixen",
                    "en": "Hide Playlists and Mixes",
                    "fi": "Piilota soittolistat ja sekoitukset",
                    "fr": "Masquer les listes de lecture et les mixages",
                    "de": "Playlists und Mixe ausblenden",
                    "el": "Απόκρυψη λιστών αναπαραγωγής και μίξης",
                    "he": "הסתר רשימות השמעה ומיקסים",
                    "hi": "प्लेलिस्ट और मिक्स छिपाएँ",
                    "hu": "Lejátszási listák és keverékek elrejtése",
                    "id": "Sembunyikan Daftar Putar dan Campuran",
                    "it": "Nascondi playlist e mix",
                    "ja": "プレイリストとミックスを非表示にする",
                    "ko": "재생 목록 및 믹스 숨기기",
                    "ms": "Sembunyikan Senarai Main dan Campuran",
                    "nb": "Skjul spillelister og mikser",
                    "pl": "Ukryj playlisty i składanki",
                    "pt": "Ocultar listas de reprodução e mixagens",
                    "ro": "Ascunde listele de redare și mixuri",
                    "ru": "Скрыть плейлисты и миксы",
                    "sk": "Skryť zoznamy skladieb a mixy",
                    "es": "Ocultar listas de reproducción y mezclas",
                    "sv": "Dölj spellistor och mixar",
                    "th": "ซ่อนเพลย์ลิสต์และมิกซ์",
                    "tr": "Çalma Listelerini ve Karışımları Gizle",
                    "uk": "Приховати списки відтворення та мікси",
                    "vi": "Ẩn danh sách phát và bản phối"
                  },
                id: "untrap_home_hide_suggestion_mixes",
                defaultValue: false
            },
            
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء السراويل القصيرة والمتداولة وما إلى ذلك.",
                    "ca": "Amaga pantalons curts, tendències, etc.",
                    "zh-CN": "隐藏短裤、趋势等。",
                    "zh-TW": "隱藏短褲、趨勢等。",
                    "hr": "Sakrij Shorts, U trendu itd.",
                    "cs": "Skrýt šortky, Trendy atd.",
                    "da": "Skjul shorts, trending osv.",
                    "nl": "Verberg shorts, trends, etc.",
                    "en": "Hide Shorts, Trending, etc.",
                    "fi": "Piilota shortsit, Trendaavat jne.",
                    "fr": "Masquer les shorts, les tendances, etc.",
                    "de": "Shorts, Trends usw. ausblenden",
                    "el": "Απόκρυψη Shorts, Trending, κ.λπ.",
                    "he": "הסתר מכנסיים קצרים, טרנדים וכו'.",
                    "hi": "शॉर्ट्स, ट्रेंडिंग आदि छुपाएं।",
                    "hu": "Rövidnadrágok, Felkapott stb. elrejtése.",
                    "id": "Sembunyikan Celana Pendek, Trending, dll.",
                    "it": "Nascondi Shorts, Tendenze, ecc.",
                    "ja": "ショートパンツ、トレンドなどを非表示にします。",
                    "ko": "Shorts, 인기 급상승 동영상 등 숨기기",
                    "ms": "Sembunyikan Seluar Pendek, Arah Aliran, dsb.",
                    "nb": "Skjul shorts, trending osv.",
                    "pl": "Ukryj szorty, trendy itp.",
                    "pt": "Ocultar Shorts, Tendências, etc.",
                    "ro": "Ascunde pantaloni scurți, tendințe etc.",
                    "ru": "Скрыть шорты, тренды и т. д.",
                    "sk": "Skryť šortky, Trendy atď.",
                    "es": "Ocultar pantalones cortos, tendencias, etc.",
                    "sv": "Göm shorts, trender osv.",
                    "th": "ซ่อนวิดีโอสั้น กำลังมาแรง ฯลฯ",
                    "tr": "Kısaları, Trend Olanları vb. gizleyin.",
                    "uk": "Сховати шорти, популярні тощо.",
                    "vi": "Ẩn video ngắn, Thịnh hành, v.v."
                  },
                id: "untrap_home_hide_extra_rows",
                defaultValue: false
            },
            
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء الشعارات - الجديد بالنسبة لك، Premium، Survey، إلخ.",
                    "ca": "Amaga els bàners: nou per a tu, Premium, Enquesta, etc.",
                    "zh-CN": "隐藏横幅 - 对您来说是新的、高级的、调查等。",
                    "zh-TW": "隱藏橫幅 - 對您來說是新的、高級的、調查等。",
                    "hr": "Sakrij bannere - Novo za vas, Premium, Anketa itd.",
                    "cs": "Skrýt bannery – novinka pro vás, Premium, průzkum atd.",
                    "da": "Skjul bannere - Nyt for dig, Premium, Survey osv.",
                    "nl": "Banners verbergen - Nieuw voor u, Premium, Enquête, etc.",
                    "en": "Hide Banners - New to you, Premium, Survey, etc.",
                    "fi": "Piilota bannerit - Uutta sinulle, Premium, Survey jne.",
                    "fr": "Masquer les bannières - Nouveau pour vous, Premium, Enquête, etc.",
                    "de": "Banner ausblenden – Neu für Sie, Premium, Umfrage usw.",
                    "el": "Απόκρυψη Banners - Νέο για εσάς, Premium, Survey κ.λπ.",
                    "he": "הסתר באנרים - חדש לך, פרימיום, סקר וכו'.",
                    "hi": "बैनर छिपाएँ - आपके लिए नया, प्रीमियम, सर्वेक्षण, आदि।",
                    "hu": "Bannerek elrejtése – Újdonságok, prémium, felmérés stb.",
                    "id": "Sembunyikan Spanduk - Baru bagi Anda, Premium, Survei, dll.",
                    "it": "Nascondi banner: Nuovo per te, Premium, Sondaggio, ecc.",
                    "ja": "バナーを非表示にする - 新規、プレミアム、アンケートなど。",
                    "ko": "배너 숨기기 - 새로운 기능, 프리미엄, 설문조사 등",
                    "ms": "Sembunyikan Sepanduk - Baru kepada anda, Premium, Tinjauan, dsb.",
                    "nb": "Skjul bannere – Nytt for deg, Premium, Survey, etc.",
                    "pl": "Ukryj banery - Nowość dla Ciebie, Premium, Ankieta itp.",
                    "pt": "Ocultar Banners - Novo para você, Premium, Pesquisa, etc.",
                    "ro": "Ascunde bannere - Nou pentru tine, Premium, Sondaj etc.",
                    "ru": "Скрыть баннеры — «Новое для вас», «Премиум», «Опрос» и т. д.",
                    "sk": "Skryť bannery – novinka pre vás, Premium, prieskum atď.",
                    "es": "Ocultar banners: nuevos para usted, premium, encuesta, etc.",
                    "sv": "Dölj banners - Nytt för dig, Premium, Survey, etc.",
                    "th": "ซ่อนแบนเนอร์ - ใหม่สำหรับคุณ พรีเมียม แบบสำรวจ ฯลฯ",
                    "tr": "Banner'ları Gizle - Yenilikler, Premium, Anket vb.",
                    "uk": "Приховати банери - нові для вас, преміум, опитування тощо.",
                    "vi": "Ẩn biểu ngữ - Mới đối với bạn, Premium, Khảo sát, v.v."
                  },
                id: "untrap_home_hide_banners_with_close",
                defaultValue: false
            },
            
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء الإعلانات في الاقتراحات",
                    "ca": "Amaga els anuncis als suggeriments",
                    "zh-CN": "隐藏建议中的广告",
                    "zh-TW": "隱藏建議中的廣告",
                    "hr": "Sakrij oglase u prijedlozima",
                    "cs": "Skrýt reklamy v návrzích",
                    "da": "Skjul annoncer i forslag",
                    "nl": "Verberg advertenties in suggesties",
                    "en": "Hide Ads in Suggestions",
                    "fi": "Piilota mainokset ehdotuksista",
                    "fr": "Masquer les annonces dans les suggestions",
                    "de": "Anzeigen in Vorschlägen ausblenden",
                    "el": "Απόκρυψη διαφημίσεων στις Προτάσεις",
                    "he": "הסתר מודעות בהצעות",
                    "hi": "सुझावों में विज्ञापन छिपाएँ",
                    "hu": "Hirdetések elrejtése a Javaslatokban",
                    "id": "Sembunyikan Iklan di Saran",
                    "it": "Nascondi annunci nei suggerimenti",
                    "ja": "候補内の広告を非表示にする",
                    "ko": "제안에서 광고 숨기기",
                    "ms": "Sembunyikan Iklan dalam Cadangan",
                    "nb": "Skjul annonser i forslag",
                    "pl": "Ukryj reklamy w sugestiach",
                    "pt": "Ocultar anúncios em sugestões",
                    "ro": "Ascundeți anunțurile în sugestii",
                    "ru": "Скрыть рекламу в предложениях",
                    "sk": "Skryť reklamy v návrhoch",
                    "es": "Ocultar anuncios en sugerencias",
                    "sv": "Dölj annonser i förslag",
                    "th": "ซ่อนโฆษณาในคำแนะนำ",
                    "tr": "Önerilerdeki Reklamları Gizle",
                    "uk": "Приховати рекламу в пропозиціях",
                    "vi": "Ẩn quảng cáo trong đề xuất"
                  },
                id: "untrap_home_hide_ads_first_slot",
                defaultValue: true
            }
        ]
    }
]

// MARK: - Mobile Groups

const homePageMobileGroups_Redirects = [
    {
        type: "select",
        name: {
            "ar": "الصفحة الرئيسية هي",
            "ca": "La pàgina d'inici és",
            "zh-CN": "主页是",
            "zh-TW": "主頁是",
            "hr": "Početna stranica je",
            "cs": "Domovská stránka je",
            "da": "Hjemmesiden er",
            "nl": "Startpagina is",
            "en": "Home Page is",
            "fi": "Kotisivu on",
            "fr": "La page d'accueil est",
            "de": "Startseite ist",
            "el": "Η αρχική σελίδα είναι",
            "he": "דף הבית הוא",
            "hi": "होम पेज है",
            "hu": "A kezdőlap az",
            "id": "Halaman Beranda adalah",
            "it": "La pagina iniziale è",
            "ja": "ホームページは",
            "ko": "홈 페이지는 다음과 같습니다.",
            "ms": "Laman Utama ialah",
            "nb": "Hjemmesiden er",
            "pl": "Strona główna jest",
            "pt": "A página inicial é",
            "ro": "Pagina de pornire este",
            "ru": "Домашняя страница",
            "sk": "Domovská stránka je",
            "es": "La página de inicio es",
            "sv": "Hemsidan är",
            "th": "หน้าแรกคือ",
            "tr": "Ana Sayfa:",
            "uk": "Домашня сторінка є",
            "vi": "Trang chủ là"
          },
        id: "untrap_redirect_home_to",
        defaultValue: "home",
        selects: [
            {
                name: {
                    "ar": "الصفحة الرئيسية",
                    "ca": "Pàgina d'inici",
                    "zh-CN": "主页",
                    "zh-TW": "首頁",
                    "hr": "Početna stranica",
                    "cs": "Domovská stránka",
                    "da": "Hjemmeside",
                    "nl": "Startpagina",
                    "en": "Home Page",
                    "fi": "Kotisivu",
                    "fr": "Page d'accueil",
                    "de": "Startseite",
                    "el": "Αρχική Σελίδα",
                    "he": "דף הבית",
                    "hi": "होम पेज",
                    "hu": "Kezdőlap",
                    "id": "Halaman Beranda",
                    "it": "Pagina iniziale",
                    "ja": "ホームページ",
                    "ko": "홈 페이지",
                    "ms": "Halaman Utama",
                    "nb": "Hjemmeside",
                    "pl": "Strona główna",
                    "pt": "Pagina inicial",
                    "ro": "Pagina principala",
                    "ru": "Домашняя страница",
                    "sk": "Domovská stránka",
                    "es": "Página de inicio",
                    "sv": "Hemsida",
                    "th": "หน้าแรก",
                    "tr": "Ana Sayfa",
                    "uk": "Домашня сторінка",
                    "vi": "Trang chủ"
              },
                id: "home"
            },
            {
                name: {
                    "ar": "صفحة الاشتراكات",
                    "ca": "Pàgina de subscripcions",
                    "zh-CN": "订阅页面",
                    "zh-TW": "訂閱頁面",
                    "hr": "Stranica pretplata",
                    "cs": "Stránka odběrů",
                    "da": "Side med abonnementer",
                    "nl": "Abonnementenpagina",
                    "en": "Subscriptions Page",
                    "fi": "Tilaukset-sivu",
                    "fr": "Page d'abonnements",
                    "de": "Seite „Abonnements“.",
                    "el": "Σελίδα συνδρομών",
                    "he": "עמוד מנויים",
                    "hi": "सदस्यता पृष्ठ",
                    "hu": "Előfizetések oldal",
                    "id": "Halaman Langganan",
                    "it": "Pagina Abbonamenti",
                    "ja": "定期購入ページ",
                    "ko": "구독 페이지",
                    "ms": "Halaman Langganan",
                    "nb": "Abonnementsside",
                    "pl": "Strona subskrypcji",
                    "pt": "Página de assinaturas",
                    "ro": "Pagina de abonamente",
                    "ru": "Страница подписок",
                    "sk": "Stránka odberov",
                    "es": "Página de suscripciones",
                    "sv": "Prenumerationssida",
                    "th": "หน้าสมัครสมาชิก",
                    "tr": "Abonelikler Sayfası",
                    "uk": "Сторінка підписки",
                    "vi": "Trang đăng ký"
                  },
                id: "subscriptions"
            },
            {
                name: {
                    "ar": "مشاهدة الصفحة لاحقا",
                    "ca": "Veure la pàgina més tard",
                    "zh-CN": "稍后观看页面",
                    "zh-TW": "稍後觀看頁面",
                    "hr": "Stranica Gledaj kasnije",
                    "cs": "Stránka Přehrát později",
                    "da": "Se senere side",
                    "nl": "Bekijk de latere pagina",
                    "en": "Watch Later Page",
                    "fi": "Katso myöhemmin -sivu",
                    "fr": "Page à regarder plus tard",
                    "de": "Seite „Später ansehen“",
                    "el": "Παρακολούθηση Σελίδας αργότερα",
                    "he": "צפה בעמוד מאוחר יותר",
                    "hi": "बाद वाला पेज देखें",
                    "hu": "Nézd később oldal",
                    "id": "Tonton Halaman Nanti",
                    "it": "Guarda la pagina successiva",
                    "ja": "後で見るページ",
                    "ko": "나중에 볼 페이지",
                    "ms": "Tonton Halaman Kemudian",
                    "nb": "Se senere side",
                    "pl": "Obejrzyj późniejszą stronę",
                    "pt": "Assistir mais tarde página",
                    "ro": "Vizionați pagina mai târziu",
                    "ru": "Страница просмотра позже",
                    "sk": "Stránka Pozrieť neskôr",
                    "es": "Ver página más tarde",
                    "sv": "Titta senare sida",
                    "th": "ดูหน้าภายหลัง",
                    "tr": "Daha Sonra İzle Sayfası",
                    "uk": "Сторінка 'Переглянути пізніше'.",
                    "vi": "Xem trang sau"
                  },
                id: "watch_later"
            },
            {
                name: {
                    "ar": "الصفحة الشائعة",
                    "ca": "Pàgina de tendències",
                    "zh-CN": "热门页面",
                    "zh-TW": "熱門頁面",
                    "hr": "Stranica u trendu",
                    "cs": "Trendová stránka",
                    "da": "Trending side",
                    "nl": "Trending-pagina",
                    "en": "Trending Page",
                    "fi": "Trendaavat sivut",
                    "fr": "Page tendance",
                    "de": "Trendseite",
                    "el": "Τάσεις σελίδας",
                    "he": "עמוד פופולרי",
                    "hi": "ट्रेंडिंग पेज",
                    "hu": "Felkapott oldal",
                    "id": "Halaman Tren",
                    "it": "Pagina di tendenza",
                    "ja": "トレンドページ",
                    "ko": "인기 페이지",
                    "ms": "Halaman Arah Aliran",
                    "nb": "Trendende side",
                    "pl": "Strona z trendami",
                    "pt": "Página de tendências",
                    "ro": "Pagina de tendințe",
                    "ru": "Популярная страница",
                    "sk": "Populárna stránka",
                    "es": "Página de tendencias",
                    "sv": "Trendig sida",
                    "th": "เพจที่กำลังมาแรง",
                    "tr": "Trend Sayfası",
                    "uk": "Популярна сторінка",
                    "vi": "Trang thịnh hành"
                  },
                
                id: "trending"
            },
            {
                name: {
                    "ar": "صفحة التاريخ",
                    "ca": "Pàgina d'història",
                    "zh-CN": "历史页面",
                    "zh-TW": "歷史頁面",
                    "hr": "Stranica povijesti",
                    "cs": "Stránka historie",
                    "da": "Historie side",
                    "nl": "Geschiedenispagina",
                    "en": "History Page",
                    "fi": "Historia-sivu",
                    "fr": "Page d'historique",
                    "de": "Geschichtsseite",
                    "el": "Σελίδα Ιστορίας",
                    "he": "עמוד היסטוריה",
                    "hi": "इतिहास पृष्ठ",
                    "hu": "Történelem oldal",
                    "id": "Halaman Sejarah",
                    "it": "Pagina della storia",
                    "ja": "履歴ページ",
                    "ko": "역사 페이지",
                    "ms": "Halaman Sejarah",
                    "nb": "Historieside",
                    "pl": "Strona historii",
                    "pt": "Página de histórico",
                    "ro": "Pagina de istorie",
                    "ru": "Страница истории",
                    "sk": "Stránka histórie",
                    "es": "Página de historia",
                    "sv": "Historik sida",
                    "th": "หน้าประวัติศาสตร์",
                    "tr": "Geçmiş Sayfası",
                    "uk": "Сторінка історії",
                    "vi": "Trang lịch sử"
                  },
                
                id: "history"
            },
            {
                name: {
                    "ar": "الصفحة التي تم الإعجاب بها",
                    "ca": "Pàgina M'agrada",
                    "zh-CN": "喜欢的页面",
                    "zh-TW": "喜歡的頁面",
                    "hr": "Svidjela mi se stranica",
                    "cs": "Stránka, která se vám líbí",
                    "da": "Synes godt om side",
                    "nl": "Pagina leuk gevonden",
                    "en": "Liked Page",
                    "fi": "Tykkää sivusta",
                    "fr": "Page aimée",
                    "de": "Gefällt mir Seite",
                    "el": "Σελίδα που άρεσε",
                    "he": "עמוד לייק",
                    "hi": "पेज पसंद आया",
                    "hu": "Kedvelt oldal",
                    "id": "Halaman yang Disukai",
                    "it": "Pagina piaciuta",
                    "ja": "気に入ったページ",
                    "ko": "좋아요를 누른 페이지",
                    "ms": "Halaman Suka",
                    "nb": "Likte siden",
                    "pl": "Polubiona strona",
                    "pt": "Página curtida",
                    "ro": "Pagină apreciată",
                    "ru": "Понравившаяся страница",
                    "sk": "Stránka, ktorá sa vám páči",
                    "es": "Página que me gustó",
                    "sv": "Gillade sidan",
                    "th": "ถูกใจเพจ",
                    "tr": "Beğenilen Sayfa",
                    "uk": "Сподобалася сторінка",
                    "vi": "Trang đã thích"
                  },
                id: "liked"
            },
            {
                name: {
                    "ar": "صفحة المكتبة",
                    "ca": "Pàgina de la Biblioteca",
                    "zh-CN": "图书馆页面",
                    "zh-TW": "圖書館頁面",
                    "hr": "Stranica knjižnice",
                    "cs": "Stránka knihovny",
                    "da": "Biblioteksside",
                    "nl": "Bibliotheekpagina",
                    "en": "Library Page",
                    "fi": "Kirjaston sivu",
                    "fr": "Page de la bibliothèque",
                    "de": "Bibliotheksseite",
                    "el": "Σελίδα βιβλιοθήκης",
                    "he": "עמוד ספריה",
                    "hi": "लाइब्रेरी पेज",
                    "hu": "Könyvtár oldala",
                    "id": "Halaman Perpustakaan",
                    "it": "Pagina della biblioteca",
                    "ja": "ライブラリページ",
                    "ko": "도서관 페이지",
                    "ms": "Halaman Perpustakaan",
                    "nb": "Bibliotekside",
                    "pl": "Strona Biblioteki",
                    "pt": "Página da Biblioteca",
                    "ro": "Pagina Bibliotecii",
                    "ru": "Страница библиотеки",
                    "sk": "Stránka knižnice",
                    "es": "Página de la biblioteca",
                    "sv": "Bibliotekssida",
                    "th": "หน้าห้องสมุด",
                    "tr": "Kütüphane Sayfası",
                    "uk": "Сторінка бібліотеки",
                    "vi": "Trang thư viện"
                  },
                id: "library"
            }
        ]
    }
];

const homePageMobileGroups_Suggestions = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الاقتراحات",
            "ca": "Amaga suggeriments",
            "zh-CN": "隐藏建议",
            "zh-TW": "隱藏建議",
            "hr": "Sakrij prijedloge",
            "cs": "Skrýt návrhy",
            "da": "Skjul forslag",
            "nl": "Suggesties verbergen",
            "en": "Hide Suggestions",
            "fi": "Piilota ehdotukset",
            "fr": "Masquer les suggestions",
            "de": "Vorschläge ausblenden",
            "el": "Απόκρυψη προτάσεων",
            "he": "הסתר הצעות",
            "hi": "सुझाव छिपाएँ",
            "hu": "Javaslatok elrejtése",
            "id": "Sembunyikan Saran",
            "it": "Nascondi suggerimenti",
            "ja": "提案を非表示にする",
            "ko": "제안 숨기기",
            "ms": "Sembunyikan Cadangan",
            "nb": "Skjul forslag",
            "pl": "Ukryj sugestie",
            "pt": "Ocultar sugestões",
            "ro": "Ascundeți sugestiile",
            "ru": "Скрыть предложения",
            "sk": "Skryť návrhy",
            "es": "Ocultar sugerencias",
            "sv": "Dölj förslag",
            "th": "ซ่อนคำแนะนำ",
            "tr": "Önerileri Gizle",
            "uk": "Приховати пропозиції",
            "vi": "Ẩn đề xuất"
          },
        id: "untrap_home_hide_suggestions",
        defaultValue: false,
        childOffOptions: [
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء زر الاستكشاف",
                    "ca": "Amaga el botó Explora",
                    "zh-CN": "隐藏探索按钮",
                    "zh-TW": "隱藏探索按鈕",
                    "hr": "Sakrij gumb Istraži",
                    "cs": "Skrýt tlačítko Prozkoumat",
                    "da": "Skjul knappen Udforsk",
                    "nl": "Knop Verkennen verbergen",
                    "en": "Hide Explore Button",
                    "fi": "Piilota Tutki-painike",
                    "fr": "Masquer le bouton Explorer",
                    "de": "Schaltfläche „Erkunden“ ausblenden",
                    "el": "Απόκρυψη κουμπιού εξερεύνησης",
                    "he": "הסתר לחצן חקירה",
                    "hi": "एक्सप्लोर बटन छिपाएँ",
                    "hu": "A Felfedezés gomb elrejtése",
                    "id": "Sembunyikan Tombol Jelajahi",
                    "it": "Nascondi il pulsante Esplora",
                    "ja": "「探索」ボタンを非表示にする",
                    "ko": "탐색 버튼 숨기기",
                    "ms": "Sembunyikan Butang Jelajah",
                    "nb": "Skjul Utforsk-knappen",
                    "pl": "Ukryj przycisk Eksploruj",
                    "pt": "Ocultar botão Explorar",
                    "ro": "Ascunde butonul Explorare",
                    "ru": "Скрыть кнопку «Исследовать»",
                    "sk": "Skryť tlačidlo Preskúmať",
                    "es": "Ocultar botón Explorar",
                    "sv": "Göm Utforska-knappen",
                    "th": "ซ่อนปุ่มสำรวจ",
                    "tr": "Keşfet Düğmesini Gizle",
                    "uk": "Сховати кнопку дослідження",
                    "vi": "Ẩn nút khám phá"
                  },
                id: "untrap_home_mobile_hide_explore_button",
                defaultValue: false
            },
            
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء فئات الاقتراحات",
                    "ca": "Amaga les categories de suggeriments",
                    "zh-CN": "隐藏建议类别",
                    "zh-TW": "隱藏建議類別",
                    "hr": "Sakrij kategorije prijedloga",
                    "cs": "Skrýt kategorie návrhů",
                    "da": "Skjul forslagskategorier",
                    "nl": "Suggestiecategorieën verbergen",
                    "en": "Hide Suggestions Categories",
                    "fi": "Piilota ehdotuskategoriat",
                    "fr": "Masquer les catégories de suggestions",
                    "de": "Vorschlagskategorien ausblenden",
                    "el": "Απόκρυψη κατηγοριών προτάσεων",
                    "he": "הסתר קטגוריות הצעות",
                    "hi": "सुझाव श्रेणियाँ छिपाएँ",
                    "hu": "Javaslatok kategóriák elrejtése",
                    "id": "Sembunyikan Kategori Saran",
                    "it": "Nascondi le categorie dei suggerimenti",
                    "ja": "提案のカテゴリを非表示にする",
                    "ko": "제안 카테고리 숨기기",
                    "ms": "Sembunyikan Kategori Cadangan",
                    "nb": "Skjul forslagskategorier",
                    "pl": "Ukryj kategorie sugestii",
                    "pt": "Ocultar categorias de sugestões",
                    "ro": "Ascundeți categoriile de sugestii",
                    "ru": "Скрыть категории предложений",
                    "sk": "Skryť kategórie návrhov",
                    "es": "Ocultar categorías de sugerencias",
                    "sv": "Dölj förslagskategorier",
                    "th": "ซ่อนหมวดหมู่คำแนะนำ",
                    "tr": "Öneri Kategorilerini Gizle",
                    "uk": "Приховати категорії пропозицій",
                    "vi": "Ẩn danh mục đề xuất"
                  },
                id: "untrap_home_hide_header_with_categories",
                defaultValue: false
            },
            
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء مقاطع الفيديو التي تمت مشاهدتها",
                    "ca": "Amaga els vídeos vists",
                    "zh-CN": "隐藏观看过的视频",
                    "zh-TW": "隱藏觀看過的視頻",
                    "hr": "Sakrij gledane videozapise",
                    "cs": "Skrýt sledovaná videa",
                    "da": "Skjul sete videoer",
                    "nl": "Verberg bekeken video's",
                    "en": "Hide Watched Videos",
                    "fi": "Piilota katsotut videot",
                    "fr": "Masquer les vidéos regardées",
                    "de": "Angesehene Videos ausblenden",
                    "el": "Απόκρυψη βίντεο που παρακολουθήσατε",
                    "he": "הסתר סרטונים שנצפו",
                    "hi": "देखे गए वीडियो छुपाएं",
                    "hu": "Megtekintett videók elrejtése",
                    "id": "Sembunyikan Video yang Ditonton",
                    "it": "Nascondi i video guardati",
                    "ja": "視聴したビデオを非表示にする",
                    "ko": "시청한 동영상 숨기기",
                    "ms": "Sembunyikan Video yang Ditonton",
                    "nb": "Skjul sett videoer",
                    "pl": "Ukryj oglądane filmy",
                    "pt": "Ocultar vídeos assistidos",
                    "ro": "Ascunde videoclipurile vizionate",
                    "ru": "Скрыть просмотренные видео",
                    "sk": "Skryť sledované videá",
                    "es": "Ocultar vídeos vistos",
                    "sv": "Dölj sedda videor",
                    "th": "ซ่อนวิดีโอที่ดู",
                    "tr": "İzlenen Videoları Gizle",
                    "uk": "Приховати переглянуті відео",
                    "vi": "Ẩn video đã xem"
                  },
                id: "untrap_home_hide_watched_videos",
                defaultValue: false
            },
            
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء قوائم التشغيل والمزج",
                    "ca": "Amaga llistes de reproducció i mescles",
                    "zh-CN": "隐藏播放列表和混音",
                    "zh-TW": "隱藏播放清單和混音",
                    "hr": "Sakrij popise za reprodukciju i mikseve",
                    "cs": "Skrýt seznamy skladeb a mixy",
                    "da": "Skjul afspilningslister og mix",
                    "nl": "Verberg afspeellijsten en mixen",
                    "en": "Hide Playlists and Mixes",
                    "fi": "Piilota soittolistat ja sekoitukset",
                    "fr": "Masquer les listes de lecture et les mixages",
                    "de": "Playlists und Mixe ausblenden",
                    "el": "Απόκρυψη λιστών αναπαραγωγής και μίξης",
                    "he": "הסתר רשימות השמעה ומיקסים",
                    "hi": "प्लेलिस्ट और मिक्स छिपाएँ",
                    "hu": "Lejátszási listák és keverékek elrejtése",
                    "id": "Sembunyikan Daftar Putar dan Campuran",
                    "it": "Nascondi playlist e mix",
                    "ja": "プレイリストとミックスを非表示にする",
                    "ko": "재생 목록 및 믹스 숨기기",
                    "ms": "Sembunyikan Senarai Main dan Campuran",
                    "nb": "Skjul spillelister og mikser",
                    "pl": "Ukryj playlisty i składanki",
                    "pt": "Ocultar listas de reprodução e mixagens",
                    "ro": "Ascunde listele de redare și mixuri",
                    "ru": "Скрыть плейлисты и миксы",
                    "sk": "Skryť zoznamy skladieb a mixy",
                    "es": "Ocultar listas de reproducción y mezclas",
                    "sv": "Dölj spellistor och mixar",
                    "th": "ซ่อนเพลย์ลิสต์และมิกซ์",
                    "tr": "Çalma Listelerini ve Karışımları Gizle",
                    "uk": "Приховати списки відтворення та мікси",
                    "vi": "Ẩn danh sách phát và bản phối"
                  },
                id: "untrap_home_hide_suggestion_mixes",
                defaultValue: false
            },
            
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء السراويل القصيرة والمتداولة وما إلى ذلك.",
                    "ca": "Amaga pantalons curts, tendències, etc.",
                    "zh-CN": "隐藏短裤、趋势等。",
                    "zh-TW": "隱藏短褲、趨勢等。",
                    "hr": "Sakrij Shorts, U trendu itd.",
                    "cs": "Skrýt šortky, Trendy atd.",
                    "da": "Skjul shorts, trending osv.",
                    "nl": "Verberg shorts, trends, etc.",
                    "en": "Hide Shorts, Trending, etc.",
                    "fi": "Piilota shortsit, Trendaavat jne.",
                    "fr": "Masquer les shorts, les tendances, etc.",
                    "de": "Shorts, Trends usw. ausblenden",
                    "el": "Απόκρυψη Shorts, Trending, κ.λπ.",
                    "he": "הסתר מכנסיים קצרים, טרנדים וכו'.",
                    "hi": "शॉर्ट्स, ट्रेंडिंग आदि छुपाएं।",
                    "hu": "Rövidnadrágok, Felkapott stb. elrejtése.",
                    "id": "Sembunyikan Celana Pendek, Trending, dll.",
                    "it": "Nascondi Shorts, Tendenze, ecc.",
                    "ja": "ショートパンツ、トレンドなどを非表示にします。",
                    "ko": "Shorts, 인기 급상승 동영상 등 숨기기",
                    "ms": "Sembunyikan Seluar Pendek, Arah Aliran, dsb.",
                    "nb": "Skjul shorts, trending osv.",
                    "pl": "Ukryj szorty, trendy itp.",
                    "pt": "Ocultar Shorts, Tendências, etc.",
                    "ro": "Ascunde pantaloni scurți, tendințe etc.",
                    "ru": "Скрыть шорты, тренды и т. д.",
                    "sk": "Skryť šortky, Trendy atď.",
                    "es": "Ocultar pantalones cortos, tendencias, etc.",
                    "sv": "Göm shorts, trender osv.",
                    "th": "ซ่อนวิดีโอสั้น กำลังมาแรง ฯลฯ",
                    "tr": "Kısaları, Trend Olanları vb. gizleyin.",
                    "uk": "Сховати шорти, популярні тощо.",
                    "vi": "Ẩn video ngắn, Thịnh hành, v.v."
                  },
                id: "untrap_home_hide_extra_rows",
                defaultValue: false
            },
            
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء الشعار - جديد بالنسبة لك",
                    "ca": "Amaga el bàner: nou per a tu",
                    "zh-CN": "隐藏横幅 - 对您来说是新的",
                    "zh-TW": "隱藏橫幅 - 對您來說是新的",
                    "hr": "Sakrij natpis - Novo za vas",
                    "cs": "Skrýt banner – pro vás novinka",
                    "da": "Skjul banner - nyt for dig",
                    "nl": "Banner verbergen - Nieuw voor jou",
                    "en": "Hide Banner - New to you",
                    "fi": "Piilota banneri – uutta sinulle",
                    "fr": "Masquer la bannière - Nouveau pour vous",
                    "de": "Banner ausblenden – Neu für Sie",
                    "el": "Απόκρυψη Banner - Νέος για εσάς",
                    "he": "הסתר באנר - חדש לך",
                    "hi": "बैनर छिपाएँ - आपके लिए नया",
                    "hu": "Banner elrejtése – Újdonság számodra",
                    "id": "Sembunyikan Spanduk - Baru bagi Anda",
                    "it": "Nascondi banner: nuovo per te",
                    "ja": "バナーを非表示にする - 初めての方へ",
                    "ko": "배너 숨기기 - 새로운 소식",
                    "ms": "Sembunyikan Sepanduk - Baru kepada anda",
                    "nb": "Skjul banner – nytt for deg",
                    "pl": "Ukryj baner - nowość dla Ciebie",
                    "pt": "Ocultar banner – novidade para você",
                    "ro": "Ascunde Banner - Nou pentru tine",
                    "ru": "Скрыть баннер – Новое для вас",
                    "sk": "Skryť banner – novinka pre vás",
                    "es": "Ocultar banner: nuevo para ti",
                    "sv": "Göm banner - Nytt för dig",
                    "th": "ซ่อนแบนเนอร์ - ใหม่สำหรับคุณ",
                    "tr": "Banner'ı Gizle - Sizin için yeni",
                    "uk": "Приховати банер - нове для вас",
                    "vi": "Ẩn biểu ngữ - Mới đối với bạn"
                  },
                id: "untrap_home_hide_banners_with_close",
                defaultValue: false
            }
        ]
    }
];

// MARK: - Builder

// Desktop

const homePageDesktopGroups = [
    {
        groupName: {
            "ar": "إعادة توجيه",
            "ca": "Redirigeix",
            "zh-CN": "重定向",
            "zh-TW": "重定向",
            "hr": "Preusmjeri",
            "cs": "Přesměrování",
            "da": "Omdirigere",
            "nl": "Omleiden",
            "en": "Redirect",
            "fi": "Uudelleenohjaus",
            "fr": "Réorienter",
            "de": "Umleiten",
            "el": "Διευθύνω πάλιν",
            "he": "הפניה מחדש",
            "hi": "पुनर्निर्देशन",
            "hu": "Átirányítás",
            "id": "Pengalihan",
            "it": "Reindirizzare",
            "ja": "リダイレクト",
            "ko": "리디렉션",
            "ms": "Ubah hala",
            "no": "Omdirigere",
            "pl": "Przeadresować",
            "pt": "Redirecionar",
            "ro": "Redirecţiona",
            "ru": "Перенаправление",
            "sk": "Presmerovať",
            "es": "Redirigir",
            "sv": "Dirigera om",
            "th": "เปลี่ยนเส้นทาง",
            "tr": "Yönlendir",
            "uk": "Перенаправлення",
            "vi": "Chuyển hướng"
          },
        groupId: "redirects",
        parentCategoryId: "homePage",
        options: homePageDesktopGroups_Redirects
    },
    
    {
        groupName: {
            "ar": "اقتراحات",
            "ca": "Suggeriments",
            "zh-CN": "建议",
            "zh-TW": "建議",
            "hr": "Prijedlozi",
            "cs": "Návrhy",
            "da": "Forslag",
            "nl": "Suggesties",
            "en": "Suggestions",
            "fi": "Ehdotukset",
            "fr": "Suggestions",
            "de": "Vorschläge",
            "el": "Προτάσεις",
            "he": "הצעות",
            "hi": "सुझाव",
            "hu": "Javaslatok",
            "id": "Saran",
            "it": "Suggerimenti",
            "ja": "提案",
            "ko": "제안",
            "ms": "Cadangan",
            "nb": "Forslag",
            "pl": "Propozycje",
            "pt": "Sugestões",
            "ro": "Sugestii",
            "ru": "Предложения",
            "sk": "Návrhy",
            "es": "Sugerencias",
            "sv": "Förslag",
            "th": "ข้อเสนอแนะ",
            "tr": "Öneriler",
            "uk": "Пропозиції",
            "vi": "Đề xuất"
          },
        groupId: "suggestions",
        parentCategoryId: "homePage",
        options: homePageDesktopGroups_Suggestions
    }
];

// Mobile

const homePageMobileGroups = [
    {
        groupName: {
            "ar": "إعادة توجيه",
            "ca": "Redirigeix",
            "zh-CN": "重定向",
            "zh-TW": "重定向",
            "hr": "Preusmjeri",
            "cs": "Přesměrování",
            "da": "Omdirigere",
            "nl": "Omleiden",
            "en": "Redirect",
            "fi": "Uudelleenohjaus",
            "fr": "Réorienter",
            "de": "Umleiten",
            "el": "Διευθύνω πάλιν",
            "he": "הפניה מחדש",
            "hi": "पुनर्निर्देशन",
            "hu": "Átirányítás",
            "id": "Pengalihan",
            "it": "Reindirizzare",
            "ja": "リダイレクト",
            "ko": "리디렉션",
            "ms": "Ubah hala",
            "no": "Omdirigere",
            "pl": "Przeadresować",
            "pt": "Redirecionar",
            "ro": "Redirecţiona",
            "ru": "Перенаправление",
            "sk": "Presmerovať",
            "es": "Redirigir",
            "sv": "Dirigera om",
            "th": "เปลี่ยนเส้นทาง",
            "tr": "Yönlendir",
            "uk": "Перенаправлення",
            "vi": "Chuyển hướng"
          },
        groupId: "redirects",
        parentCategoryId: "homePage",
        options: homePageMobileGroups_Redirects
    },
    
    {
        groupName: {
            "ar": "اقتراحات",
            "ca": "Suggeriments",
            "zh-CN": "建议",
            "zh-TW": "建議",
            "hr": "Prijedlozi",
            "cs": "Návrhy",
            "da": "Forslag",
            "nl": "Suggesties",
            "en": "Suggestions",
            "fi": "Ehdotukset",
            "fr": "Suggestions",
            "de": "Vorschläge",
            "el": "Προτάσεις",
            "he": "הצעות",
            "hi": "सुझाव",
            "hu": "Javaslatok",
            "id": "Saran",
            "it": "Suggerimenti",
            "ja": "提案",
            "ko": "제안",
            "ms": "Cadangan",
            "nb": "Forslag",
            "pl": "Propozycje",
            "pt": "Sugestões",
            "ro": "Sugestii",
            "ru": "Предложения",
            "sk": "Návrhy",
            "es": "Sugerencias",
            "sv": "Förslag",
            "th": "ข้อเสนอแนะ",
            "tr": "Öneriler",
            "uk": "Пропозиції",
            "vi": "Đề xuất"
          },
        groupId: "suggestions",
        parentCategoryId: "homePage",
        options: homePageMobileGroups_Suggestions
    }
]
