const CATEGORIES = [
    
    // MARK: - Home Page
    
    {
        categoryId: "homePage",
        
        categoryDesktopName: {
            "ar": "الصفحة الرئيسية",
            "ca": "Pàgina d'inici",
            "zh-CN": "主页",
            "zh-TW": "首頁",
            "hr": "Početna stranica",
            "cs": "Domovská stránka",
            "da": "Hjemmeside",
            "nl": "Startpagina",
            "en": "Home Page",
            "fi": "Kotisivu",
            "fr": "Page d'accueil",
            "de": "Startseite",
            "el": "Αρχική Σελίδα",
            "he": "דף הבית",
            "hi": "होम पेज",
            "hu": "Kezdőlap",
            "id": "Halaman Beranda",
            "it": "Pagina iniziale",
            "ja": "ホームページ",
            "ko": "홈 페이지",
            "ms": "Halaman Utama",
            "nb": "Hjemmeside",
            "pl": "Strona główna",
            "pt": "Pagina inicial",
            "ro": "Pagina principala",
            "ru": "Домашняя страница",
            "sk": "Domovská stránka",
            "es": "Página de inicio",
            "sv": "Hemsida",
            "th": "หน้าแรก",
            "tr": "Ana Sayfa",
            "uk": "Домашня сторінка",
            "vi": "Trang chủ"
          },
        
        categoryMobileName: {
            "ar": "الصفحة الرئيسية",
            "ca": "Pàgina d'inici",
            "zh-CN": "主页",
            "zh-TW": "首頁",
            "hr": "Početna stranica",
            "cs": "Domovská stránka",
            "da": "Hjemmeside",
            "nl": "Startpagina",
            "en": "Home Page",
            "fi": "Kotisivu",
            "fr": "Page d'accueil",
            "de": "Startseite",
            "el": "Αρχική Σελίδα",
            "he": "דף הבית",
            "hi": "होम पेज",
            "hu": "Kezdőlap",
            "id": "Halaman Beranda",
            "it": "Pagina iniziale",
            "ja": "ホームページ",
            "ko": "홈 페이지",
            "ms": "Halaman Utama",
            "nb": "Hjemmeside",
            "pl": "Strona główna",
            "pt": "Pagina inicial",
            "ro": "Pagina principala",
            "ru": "Домашняя страница",
            "sk": "Domovská stránka",
            "es": "Página de inicio",
            "sv": "Hemsida",
            "th": "หน้าแรก",
            "tr": "Ana Sayfa",
            "uk": "Домашня сторінка",
            "vi": "Trang chủ"
          },
        
        categoryDesktopGroups: homePageDesktopGroups,
        categoryMobileGroups: homePageMobileGroups
    },
    
    // MARK: - Navigation Bar
    
    {
        categoryId: "navigationSidebar",
        
        categoryDesktopName: {
            "ar": "شريط التنقل الأيسر",
            "ca": "Barra de navegació esquerra",
            "zh-CN": "左侧导航栏",
            "zh-TW": "左側導覽列",
            "hr": "Lijeva navigacijska traka",
            "cs": "Levý navigační panel",
            "da": "Venstre navigationslinje",
            "nl": "Linker navigatiebalk",
            "en": "Left Navigation Bar",
            "fi": "Vasen navigointipalkki",
            "fr": "Barre de navigation gauche",
            "de": "Linke Navigationsleiste",
            "el": "Αριστερή γραμμή πλοήγησης",
            "he": "סרגל הניווט השמאלי",
            "hi": "बायां नेविगेशन बार",
            "hu": "Bal oldali navigációs sáv",
            "id": "Bilah Navigasi Kiri",
            "it": "Barra di navigazione sinistra",
            "ja": "左側のナビゲーション バー",
            "ko": "왼쪽 탐색 모음",
            "ms": "Bar Navigasi Kiri",
            "nb": "Venstre navigasjonslinje",
            "pl": "Lewy pasek nawigacyjny",
            "pt": "Barra de navegação esquerda",
            "ro": "Bara de navigare din stânga",
            "ru": "Левая панель навигации",
            "sk": "Ľavý navigačný panel",
            "es": "Barra de navegación izquierda",
            "sv": "Vänster navigeringsfält",
            "th": "แถบนำทางด้านซ้าย",
            "tr": "Sol Gezinti Çubuğu",
            "uk": "Ліва панель навігації",
            "vi": "Thanh điều hướng bên trái"
          },
        
        categoryMobileName: {
            "ar": "شريط التنقل السفلي",
            "ca": "Barra de navegació inferior",
            "zh-CN": "底部导航栏",
            "zh-TW": "底部導覽列",
            "hr": "Donja navigacijska traka",
            "cs": "Spodní navigační lišta",
            "da": "Nederste navigationslinje",
            "nl": "Onderste navigatiebalk",
            "en": "Bottom Navigation Bar",
            "fi": "Alempi navigointipalkki",
            "fr": "Barre de navigation inférieure",
            "de": "Untere Navigationsleiste",
            "el": "Κάτω γραμμή πλοήγησης",
            "he": "סרגל ניווט תחתון",
            "hi": "निचला नेविगेशन बार",
            "hu": "Alsó navigációs sáv",
            "id": "Bilah Navigasi Bawah",
            "it": "Barra di navigazione inferiore",
            "ja": "下部ナビゲーションバー",
            "ko": "하단 탐색 표시줄",
            "ms": "Bar Navigasi Bawah",
            "nb": "Nederste navigasjonslinje",
            "pl": "Dolny pasek nawigacyjny",
            "pt": "Barra de navegação inferior",
            "ro": "Bara de navigare de jos",
            "ru": "Нижняя панель навигации",
            "sk": "Spodný navigačný panel",
            "es": "Barra de navegación inferior",
            "sv": "Nedre navigeringsfältet",
            "th": "แถบนำทางด้านล่าง",
            "tr": "Alt Gezinme Çubuğu",
            "uk": "Нижня панель навігації",
            "vi": "Thanh điều hướng dưới cùng"
          },
        
        categoryDesktopGroups: navigationSidebarDesktopGroups,
        categoryMobileGroups: navigationSidebarMobileGroups
    },
    
    // MARK: - Header
    
    {
        categoryId: "header",
        
        categoryDesktopName: {
            "ar": "رأس",
            "ca": "Capçalera",
            "zh-CN": "标头",
            "zh-TW": "標頭",
            "hr": "Zaglavlje",
            "cs": "Záhlaví",
            "da": "Header",
            "nl": "Koptekst",
            "en": "Header",
            "fi": "Otsikko",
            "fr": "Entête",
            "de": "Header",
            "el": "Επί κεφαλής",
            "he": "כּוֹתֶרֶת",
            "hi": "हैडर",
            "hu": "Fejléc",
            "id": "Tajuk",
            "it": "Intestazione",
            "ja": "ヘッダ",
            "ko": "머리글",
            "ms": "Kepala",
            "nb": "Overskrift",
            "pl": "nagłówek",
            "pt": "Cabeçalho",
            "ro": "Antet",
            "ru": "Заголовок",
            "sk": "Hlavička",
            "es": "Encabezamiento",
            "sv": "Rubrik",
            "th": "หัวข้อ",
            "tr": "Başlık",
            "uk": "Заголовок",
            "vi": "tiêu đề"
          },
        
        categoryMobileName: {
            "ar": "رأس",
            "ca": "Capçalera",
            "zh-CN": "标头",
            "zh-TW": "標頭",
            "hr": "Zaglavlje",
            "cs": "Záhlaví",
            "da": "Header",
            "nl": "Koptekst",
            "en": "Header",
            "fi": "Otsikko",
            "fr": "Entête",
            "de": "Header",
            "el": "Επί κεφαλής",
            "he": "כּוֹתֶרֶת",
            "hi": "हैडर",
            "hu": "Fejléc",
            "id": "Tajuk",
            "it": "Intestazione",
            "ja": "ヘッダ",
            "ko": "머리글",
            "ms": "Kepala",
            "nb": "Overskrift",
            "pl": "nagłówek",
            "pt": "Cabeçalho",
            "ro": "Antet",
            "ru": "Заголовок",
            "sk": "Hlavička",
            "es": "Encabezamiento",
            "sv": "Rubrik",
            "th": "หัวข้อ",
            "tr": "Başlık",
            "uk": "Заголовок",
            "vi": "tiêu đề"
          },
        
        categoryDesktopGroups: headerDesktopGroups,
        categoryMobileGroups: headerMobileGroups
    },
    
    // MARK: - Video Page
    
    {
        categoryId: "videoPage",
        
        categoryDesktopName: {
            "ar": "صفحة الفيديو",
            "ca": "Pàgina de vídeo",
            "zh-CN": "视频页面",
            "zh-TW": "影片頁面",
            "hr": "Video stranica",
            "cs": "Stránka videa",
            "da": "Video side",
            "nl": "Videopagina",
            "en": "Video Page",
            "fi": "Video sivu",
            "fr": "Page vidéo",
            "de": "Videoseite",
            "el": "Σελίδα βίντεο",
            "he": "דף וידאו",
            "hi": "वीडियो पेज",
            "hu": "Videó oldal",
            "id": "Halaman Video",
            "it": "Pagina video",
            "ja": "ビデオページ",
            "ko": "비디오 페이지",
            "ms": "Halaman Video",
            "nb": "Videoside",
            "pl": "Strona wideo",
            "pt": "Página de vídeo",
            "ro": "Pagina video",
            "ru": "Страница видео",
            "sk": "Stránka videa",
            "es": "Página de vídeos",
            "sv": "Videosida",
            "th": "หน้าวิดีโอ",
            "tr": "Video Sayfası",
            "uk": "Сторінка відео",
            "vi": "Trang Video"
          },
        
        categoryMobileName: {
            "ar": "صفحة الفيديو",
            "ca": "Pàgina de vídeo",
            "zh-CN": "视频页面",
            "zh-TW": "影片頁面",
            "hr": "Video stranica",
            "cs": "Stránka videa",
            "da": "Video side",
            "nl": "Videopagina",
            "en": "Video Page",
            "fi": "Video sivu",
            "fr": "Page vidéo",
            "de": "Videoseite",
            "el": "Σελίδα βίντεο",
            "he": "דף וידאו",
            "hi": "वीडियो पेज",
            "hu": "Videó oldal",
            "id": "Halaman Video",
            "it": "Pagina video",
            "ja": "ビデオページ",
            "ko": "비디오 페이지",
            "ms": "Halaman Video",
            "nb": "Videoside",
            "pl": "Strona wideo",
            "pt": "Página de vídeo",
            "ro": "Pagina video",
            "ru": "Страница видео",
            "sk": "Stránka videa",
            "es": "Página de vídeos",
            "sv": "Videosida",
            "th": "หน้าวิดีโอ",
            "tr": "Video Sayfası",
            "uk": "Сторінка відео",
            "vi": "Trang Video"
          },
        
        categoryDesktopGroups: videoPageDesktopGroups,
        categoryMobileGroups: videoPageMobileGroups
    },
    
    // MARK: - Video Card
    
    {
        categoryId: "videoCard",
        
        categoryDesktopName: {
            "ar": "عنصر الفيديو",
            "ca": "Element de vídeo",
            "zh-CN": "视频项目",
            "zh-TW": "影片項目",
            "hr": "Video stavka",
            "cs": "Video položka",
            "da": "Video element",
            "nl": "Video-item",
            "en": "Video Item",
            "fi": "Videokohde",
            "fr": "Article vidéo",
            "de": "Videoartikel",
            "el": "Στοιχείο βίντεο",
            "he": "פריט וידאו",
            "hi": "वीडियो आइटम",
            "hu": "Videó elem",
            "id": "Barang Video",
            "it": "Elemento video",
            "ja": "ビデオアイテム",
            "ko": "비디오 항목",
            "ms": "Item Video",
            "no": "Videoelement",
            "pl": "Element wideo",
            "pt": "Item de vídeo",
            "ro": "Articol video",
            "ru": "Видео элемент",
            "sk": "Video položka",
            "es": "Artículo de vídeo",
            "sv": "Videoobjekt",
            "th": "รายการวิดีโอ",
            "tr": "Video Öğesi",
            "uk": "Відео елемент",
            "vi": "Mục Video"
          },
        
        categoryMobileName: {
            "ar": "عنصر الفيديو",
            "ca": "Element de vídeo",
            "zh-CN": "视频项目",
            "zh-TW": "影片項目",
            "hr": "Video stavka",
            "cs": "Video položka",
            "da": "Video element",
            "nl": "Video-item",
            "en": "Video Item",
            "fi": "Videokohde",
            "fr": "Article vidéo",
            "de": "Videoartikel",
            "el": "Στοιχείο βίντεο",
            "he": "פריט וידאו",
            "hi": "वीडियो आइटम",
            "hu": "Videó elem",
            "id": "Barang Video",
            "it": "Elemento video",
            "ja": "ビデオアイテム",
            "ko": "비디오 항목",
            "ms": "Item Video",
            "no": "Videoelement",
            "pl": "Element wideo",
            "pt": "Item de vídeo",
            "ro": "Articol video",
            "ru": "Видео элемент",
            "sk": "Video položka",
            "es": "Artículo de vídeo",
            "sv": "Videoobjekt",
            "th": "รายการวิดีโอ",
            "tr": "Video Öğesi",
            "uk": "Відео елемент",
            "vi": "Mục Video"
          },
        
        categoryDesktopGroups: videoCardDesktopGroups,
        categoryMobileGroups: videoCardMobileGroups
    },
    
    // MARK: - Search Page
    
    {
        categoryId: "searchPage",
        
        categoryDesktopName: {
            "ar": "صفحة البحث",
            "ca": "Pàgina de cerca",
            "zh-CN": "搜索页",
            "zh-TW": "搜尋頁",
            "hr": "Stranica za pretraživanje",
            "cs": "Stránka vyhledávání",
            "da": "Søgeside",
            "nl": "Zoekpagina",
            "en": "Search Page",
            "fi": "Hakusivu",
            "fr": "Page de recherche",
            "de": "Suchseite",
            "el": "Αναζήτηση σελίδας",
            "he": "דף חיפוש",
            "hi": "पृष्ठ खोजें",
            "hu": "Keresés oldal",
            "id": "Halaman Pencarian",
            "it": "Pagina di ricerca",
            "ja": "検索ページ",
            "ko": "검색 페이지",
            "ms": "Halaman Carian",
            "nb": "Søkeside",
            "pl": "Strona wyszukiwania",
            "pt": "Página de pesquisa",
            "ro": "Pagina de căutare",
            "ru": "Страница поиска",
            "sk": "Stránka vyhľadávania",
            "es": "Página de búsqueda",
            "sv": "Söksida",
            "th": "หน้าการค้นหา",
            "tr": "Arama Sayfası",
            "uk": "Сторінка пошуку",
            "vi": "Trang tìm kiếm"
          },
        
        categoryMobileName: {
            "ar": "صفحة البحث",
            "ca": "Pàgina de cerca",
            "zh-CN": "搜索页",
            "zh-TW": "搜尋頁",
            "hr": "Stranica za pretraživanje",
            "cs": "Stránka vyhledávání",
            "da": "Søgeside",
            "nl": "Zoekpagina",
            "en": "Search Page",
            "fi": "Hakusivu",
            "fr": "Page de recherche",
            "de": "Suchseite",
            "el": "Αναζήτηση σελίδας",
            "he": "דף חיפוש",
            "hi": "पृष्ठ खोजें",
            "hu": "Keresés oldal",
            "id": "Halaman Pencarian",
            "it": "Pagina di ricerca",
            "ja": "検索ページ",
            "ko": "검색 페이지",
            "ms": "Halaman Carian",
            "nb": "Søkeside",
            "pl": "Strona wyszukiwania",
            "pt": "Página de pesquisa",
            "ro": "Pagina de căutare",
            "ru": "Страница поиска",
            "sk": "Stránka vyhľadávania",
            "es": "Página de búsqueda",
            "sv": "Söksida",
            "th": "หน้าการค้นหา",
            "tr": "Arama Sayfası",
            "uk": "Сторінка пошуку",
            "vi": "Trang tìm kiếm"
          },
        
        categoryDesktopGroups: searchPageDesktopGroups,
        categoryMobileGroups: searchPageMobileGroups
    },
    
    // MARK: - Subscriptions Page
    
    {
        categoryId: "subscriptionsPage",
        
        categoryDesktopName: {
            "ar": "صفحة الاشتراكات",
            "ca": "Pàgina de subscripcions",
            "zh-CN": "订阅页面",
            "zh-TW": "訂閱頁面",
            "hr": "Stranica pretplata",
            "cs": "Stránka odběrů",
            "da": "Side med abonnementer",
            "nl": "Abonnementenpagina",
            "en": "Subscriptions Page",
            "fi": "Tilaukset-sivu",
            "fr": "Page d'abonnements",
            "de": "Seite „Abonnements“.",
            "el": "Σελίδα συνδρομών",
            "he": "עמוד מנויים",
            "hi": "सदस्यता पृष्ठ",
            "hu": "Előfizetések oldal",
            "id": "Halaman Langganan",
            "it": "Pagina Abbonamenti",
            "ja": "定期購入ページ",
            "ko": "구독 페이지",
            "ms": "Halaman Langganan",
            "nb": "Abonnementsside",
            "pl": "Strona subskrypcji",
            "pt": "Página de assinaturas",
            "ro": "Pagina de abonamente",
            "ru": "Страница подписок",
            "sk": "Stránka odberov",
            "es": "Página de suscripciones",
            "sv": "Prenumerationssida",
            "th": "หน้าสมัครสมาชิก",
            "tr": "Abonelikler Sayfası",
            "uk": "Сторінка підписки",
            "vi": "Trang đăng ký"
          },
        
        categoryMobileName: {
            "ar": "صفحة الاشتراكات",
            "ca": "Pàgina de subscripcions",
            "zh-CN": "订阅页面",
            "zh-TW": "訂閱頁面",
            "hr": "Stranica pretplata",
            "cs": "Stránka odběrů",
            "da": "Side med abonnementer",
            "nl": "Abonnementenpagina",
            "en": "Subscriptions Page",
            "fi": "Tilaukset-sivu",
            "fr": "Page d'abonnements",
            "de": "Seite „Abonnements“.",
            "el": "Σελίδα συνδρομών",
            "he": "עמוד מנויים",
            "hi": "सदस्यता पृष्ठ",
            "hu": "Előfizetések oldal",
            "id": "Halaman Langganan",
            "it": "Pagina Abbonamenti",
            "ja": "定期購入ページ",
            "ko": "구독 페이지",
            "ms": "Halaman Langganan",
            "nb": "Abonnementsside",
            "pl": "Strona subskrypcji",
            "pt": "Página de assinaturas",
            "ro": "Pagina de abonamente",
            "ru": "Страница подписок",
            "sk": "Stránka odberov",
            "es": "Página de suscripciones",
            "sv": "Prenumerationssida",
            "th": "หน้าสมัครสมาชิก",
            "tr": "Abonelikler Sayfası",
            "uk": "Сторінка підписки",
            "vi": "Trang đăng ký"
          },
        
        categoryDesktopGroups: subscriptionsPageDesktopGroups,
        categoryMobileGroups: subscriptionsPageMobileGroups
    },
    
    // MARK: - Channel Page
    
    {
        categoryId: "channelPage",
        
        categoryDesktopName: {
            "ar": "صفحة القناة",
            "ca": "Pàgina del canal",
            "zh-CN": "频道页面",
            "zh-TW": "頻道頁面",
            "hr": "Stranica kanala",
            "cs": "Stránka kanálu",
            "da": "Kanalside",
            "nl": "Kanaalpagina",
            "en": "Channel Page",
            "fi": "Kanavan sivu",
            "fr": "Page de la chaîne",
            "de": "Kanalseite",
            "el": "Σελίδα καναλιού",
            "he": "עמוד הערוץ",
            "hi": "चैनल पेज",
            "hu": "Csatorna oldal",
            "id": "Halaman Saluran",
            "it": "Pagina canale",
            "ja": "チャンネルページ",
            "ko": "채널 페이지",
            "ms": "Halaman Saluran",
            "nb": "Kanalside",
            "pl": "Strona kanału",
            "pt": "Página do canal",
            "ro": "Pagina canalului",
            "ru": "Страница канала",
            "sk": "Stránka kanála",
            "es": "Página del canal",
            "sv": "Kanalsida",
            "th": "หน้าช่อง",
            "tr": "Kanal Sayfası",
            "uk": "Сторінка каналу",
            "vi": "Trang kênh"
          },
        
        categoryMobileName: {
            "ar": "صفحة القناة",
            "ca": "Pàgina del canal",
            "zh-CN": "频道页面",
            "zh-TW": "頻道頁面",
            "hr": "Stranica kanala",
            "cs": "Stránka kanálu",
            "da": "Kanalside",
            "nl": "Kanaalpagina",
            "en": "Channel Page",
            "fi": "Kanavan sivu",
            "fr": "Page de la chaîne",
            "de": "Kanalseite",
            "el": "Σελίδα καναλιού",
            "he": "עמוד הערוץ",
            "hi": "चैनल पेज",
            "hu": "Csatorna oldal",
            "id": "Halaman Saluran",
            "it": "Pagina canale",
            "ja": "チャンネルページ",
            "ko": "채널 페이지",
            "ms": "Halaman Saluran",
            "nb": "Kanalside",
            "pl": "Strona kanału",
            "pt": "Página do canal",
            "ro": "Pagina canalului",
            "ru": "Страница канала",
            "sk": "Stránka kanála",
            "es": "Página del canal",
            "sv": "Kanalsida",
            "th": "หน้าช่อง",
            "tr": "Kanal Sayfası",
            "uk": "Сторінка каналу",
            "vi": "Trang kênh"
          },
        
        categoryDesktopGroups: channelPageDesktopGroups,
        categoryMobileGroups: channelPageMobileGroups
    },
    
    // MARK: - Shorts Page
    
    {
        categoryId: "shortsPage",
        
        categoryDesktopName: {
            "ar": "صفحة السراويل القصيرة",
            "ca": "Pàgina de curts",
            "zh-CN": "短裤页",
            "zh-TW": "短褲頁",
            "hr": "Stranica kratkih filmova",
            "cs": "Stránka šortky",
            "da": "Shorts-side",
            "nl": "Shorts-pagina",
            "en": "Shorts Page",
            "fi": "Shortsit sivu",
            "fr": "Page des courts métrages",
            "de": "Shorts-Seite",
            "el": "Σελίδα Shorts",
            "he": "דף קצרים",
            "hi": "शॉर्ट्स पेज",
            "hu": "Rövidnadrág oldal",
            "id": "Halaman Celana Pendek",
            "it": "Pagina dei cortometraggi",
            "ja": "ショートパンツページ",
            "ko": "쇼츠 페이지",
            "ms": "Halaman Seluar Pendek",
            "nb": "Shorts-side",
            "pl": "Strona z krótkimi spodenkami",
            "pt": "Página de curtas",
            "ro": "Pagina de pantaloni scurți",
            "ru": "Страница с короткими видео",
            "sk": "Stránka šortiek",
            "es": "Página de cortos",
            "sv": "Kortsida",
            "th": "หน้าสั้น",
            "tr": "Şort Sayfası",
            "uk": "Сторінка шорти",
            "vi": "Trang ngắn"
          },
        
        categoryMobileName: {
            "ar": "صفحة السراويل القصيرة",
            "ca": "Pàgina de curts",
            "zh-CN": "短裤页",
            "zh-TW": "短褲頁",
            "hr": "Stranica kratkih filmova",
            "cs": "Stránka šortky",
            "da": "Shorts-side",
            "nl": "Shorts-pagina",
            "en": "Shorts Page",
            "fi": "Shortsit sivu",
            "fr": "Page des courts métrages",
            "de": "Shorts-Seite",
            "el": "Σελίδα Shorts",
            "he": "דף קצרים",
            "hi": "शॉर्ट्स पेज",
            "hu": "Rövidnadrág oldal",
            "id": "Halaman Celana Pendek",
            "it": "Pagina dei cortometraggi",
            "ja": "ショートパンツページ",
            "ko": "쇼츠 페이지",
            "ms": "Halaman Seluar Pendek",
            "nb": "Shorts-side",
            "pl": "Strona z krótkimi spodenkami",
            "pt": "Página de curtas",
            "ro": "Pagina de pantaloni scurți",
            "ru": "Страница с короткими видео",
            "sk": "Stránka šortiek",
            "es": "Página de cortos",
            "sv": "Kortsida",
            "th": "หน้าสั้น",
            "tr": "Şort Sayfası",
            "uk": "Сторінка шорти",
            "vi": "Trang ngắn"
          },
        
        categoryDesktopGroups: shortsPageDesktopGroups,
        categoryMobileGroups: shortsPageMobileGroups
    },
    
    // MARK: - You Page
    
    {
        categoryId: "youPage",
        
        categoryDesktopName: {
            "ar": "صفحة المكتبة",
            "ca": "Pàgina de la Biblioteca",
            "zh-CN": "图书馆页面",
            "zh-TW": "圖書館頁面",
            "hr": "Stranica knjižnice",
            "cs": "Stránka knihovny",
            "da": "Biblioteksside",
            "nl": "Bibliotheekpagina",
            "en": "Library Page",
            "fi": "Kirjaston sivu",
            "fr": "Page de la bibliothèque",
            "de": "Bibliotheksseite",
            "el": "Σελίδα βιβλιοθήκης",
            "he": "עמוד ספריה",
            "hi": "लाइब्रेरी पेज",
            "hu": "Könyvtár oldala",
            "id": "Halaman Perpustakaan",
            "it": "Pagina della biblioteca",
            "ja": "ライブラリページ",
            "ko": "도서관 페이지",
            "ms": "Halaman Perpustakaan",
            "nb": "Bibliotekside",
            "pl": "Strona Biblioteki",
            "pt": "Página da Biblioteca",
            "ro": "Pagina Bibliotecii",
            "ru": "Страница библиотеки",
            "sk": "Stránka knižnice",
            "es": "Página de la biblioteca",
            "sv": "Bibliotekssida",
            "th": "หน้าห้องสมุด",
            "tr": "Kütüphane Sayfası",
            "uk": "Сторінка бібліотеки",
            "vi": "Trang thư viện"
          },
        
        categoryMobileName: {
            "ar": "صفحة المكتبة",
            "ca": "Pàgina de la Biblioteca",
            "zh-CN": "图书馆页面",
            "zh-TW": "圖書館頁面",
            "hr": "Stranica knjižnice",
            "cs": "Stránka knihovny",
            "da": "Biblioteksside",
            "nl": "Bibliotheekpagina",
            "en": "Library Page",
            "fi": "Kirjaston sivu",
            "fr": "Page de la bibliothèque",
            "de": "Bibliotheksseite",
            "el": "Σελίδα βιβλιοθήκης",
            "he": "עמוד ספריה",
            "hi": "लाइब्रेरी पेज",
            "hu": "Könyvtár oldala",
            "id": "Halaman Perpustakaan",
            "it": "Pagina della biblioteca",
            "ja": "ライブラリページ",
            "ko": "도서관 페이지",
            "ms": "Halaman Perpustakaan",
            "nb": "Bibliotekside",
            "pl": "Strona Biblioteki",
            "pt": "Página da Biblioteca",
            "ro": "Pagina Bibliotecii",
            "ru": "Страница библиотеки",
            "sk": "Stránka knižnice",
            "es": "Página de la biblioteca",
            "sv": "Bibliotekssida",
            "th": "หน้าห้องสมุด",
            "tr": "Kütüphane Sayfası",
            "uk": "Сторінка бібліотеки",
            "vi": "Trang thư viện"
          },
        
        categoryDesktopGroups: youPageDesktopGroups,
        categoryMobileGroups: youPageMobileGroups
    },
    
    // MARK: - Embed Videos
    
    {
        categoryId: "embed",
        
        categoryDesktopName: {
            "ar": "تضمين مقاطع الفيديو",
            "ca": "Insereix vídeos",
            "zh-CN": "嵌入视频",
            "zh-TW": "嵌入影片",
            "hr": "Ugradite videozapise",
            "cs": "Vkládání videí",
            "da": "Integrer videoer",
            "nl": "Video's insluiten",
            "en": "Embed Videos",
            "fi": "Upota videoita",
            "fr": "Intégrer des vidéos",
            "de": "Videos einbetten",
            "el": "Ενσωμάτωση βίντεο",
            "he": "הטמע סרטונים",
            "hi": "वीडियो एम्बेड करें",
            "hu": "Videók beágyazása",
            "id": "Sematkan Video",
            "it": "Incorpora video",
            "ja": "ビデオを埋め込む",
            "ko": "동영상 삽입",
            "ms": "Benamkan Video",
            "nb": "Bygg inn videoer",
            "pl": "Osadzaj filmy",
            "pt": "Incorporar vídeos",
            "ro": "Încorporați videoclipuri",
            "ru": "Встроить видео",
            "sk": "Vkladanie videí",
            "es": "Insertar vídeos",
            "sv": "Bädda in videor",
            "th": "ฝังวิดีโอ",
            "tr": "Videoları Yerleştir",
            "uk": "Вставити відео",
            "vi": "Nhúng Video"
          },
        
        categoryMobileName: {
            "ar": "تضمين مقاطع الفيديو",
            "ca": "Insereix vídeos",
            "zh-CN": "嵌入视频",
            "zh-TW": "嵌入影片",
            "hr": "Ugradite videozapise",
            "cs": "Vkládání videí",
            "da": "Integrer videoer",
            "nl": "Video's insluiten",
            "en": "Embed Videos",
            "fi": "Upota videoita",
            "fr": "Intégrer des vidéos",
            "de": "Videos einbetten",
            "el": "Ενσωμάτωση βίντεο",
            "he": "הטמע סרטונים",
            "hi": "वीडियो एम्बेड करें",
            "hu": "Videók beágyazása",
            "id": "Sematkan Video",
            "it": "Incorpora video",
            "ja": "ビデオを埋め込む",
            "ko": "동영상 삽입",
            "ms": "Benamkan Video",
            "nb": "Bygg inn videoer",
            "pl": "Osadzaj filmy",
            "pt": "Incorporar vídeos",
            "ro": "Încorporați videoclipuri",
            "ru": "Встроить видео",
            "sk": "Vkladanie videí",
            "es": "Insertar vídeos",
            "sv": "Bädda in videor",
            "th": "ฝังวิดีโอ",
            "tr": "Videoları Yerleştir",
            "uk": "Вставити відео",
            "vi": "Nhúng Video"
          },
        
        categoryDesktopGroups: embedDesktopGroups,
        notInBrowser: "Safari"
    },
    
    // MARK: - Appearance
    
    {
        categoryId: "appearance",
        
        categoryDesktopName: {
            "ar": "زخرفة",
            "ca": "Decoració",
            "zh-CN": "装饰",
            "zh-TW": "裝飾",
            "hr": "Ukras",
            "cs": "Dekorace",
            "da": "Dekoration",
            "nl": "Decoratie",
            "en": "Decoration",
            "fi": "Koriste",
            "fr": "Décoration",
            "de": "Dekoration",
            "el": "Διακόσμηση",
            "he": "תַפאוּרָה",
            "hi": "सजावट",
            "hu": "Dekoráció",
            "id": "Dekorasi",
            "it": "Decorazione",
            "ja": "装飾",
            "ko": "장식",
            "ms": "Hiasan",
            "no": "Dekorasjon",
            "pl": "Dekoracja",
            "pt": "Decoração",
            "ro": "Decor",
            "ru": "Украшение",
            "sk": "Dekorácia",
            "es": "Decoración",
            "sv": "Dekoration",
            "th": "การตกแต่ง",
            "tr": "Dekorasyon",
            "uk": "Прикраса",
            "vi": "Trang trí"
          },
        
        categoryMobileName: {
            "ar": "زخرفة",
            "ca": "Decoració",
            "zh-CN": "装饰",
            "zh-TW": "裝飾",
            "hr": "Ukras",
            "cs": "Dekorace",
            "da": "Dekoration",
            "nl": "Decoratie",
            "en": "Decoration",
            "fi": "Koriste",
            "fr": "Décoration",
            "de": "Dekoration",
            "el": "Διακόσμηση",
            "he": "תַפאוּרָה",
            "hi": "सजावट",
            "hu": "Dekoráció",
            "id": "Dekorasi",
            "it": "Decorazione",
            "ja": "装飾",
            "ko": "장식",
            "ms": "Hiasan",
            "no": "Dekorasjon",
            "pl": "Dekoracja",
            "pt": "Decoração",
            "ro": "Decor",
            "ru": "Украшение",
            "sk": "Dekorácia",
            "es": "Decoración",
            "sv": "Dekoration",
            "th": "การตกแต่ง",
            "tr": "Dekorasyon",
            "uk": "Прикраса",
            "vi": "Trang trí"
          },
        
        categoryDesktopGroups: appearanceDesktopGroups,
        categoryMobileGroups: appearanceMobileGroups
    },
];

const OTHER_SETTINGS = [
    {
        id: "untrap_global_enable",
        defaultValue: true
    }
];
