// MARK: - Desktop Groups

const searchPageDesktopGroups_Results = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء القنوات",
            "ca": "Amaga els canals",
            "zh-CN": "隐藏频道",
            "zh-TW": "隱藏頻道",
            "hr": "Sakrij kanale",
            "cs": "Skrýt kanály",
            "da": "Skjul kanaler",
            "nl": "Kanalen verbergen",
            "en": "Hide Channels",
            "fi": "Piilota kanavat",
            "fr": "Masquer les chaînes",
            "de": "Kanäle ausblenden",
            "el": "Απόκρυψη καναλιών",
            "he": "הסתר ערוצים",
            "hi": "चैनल छिपाएँ",
            "hu": "Csatornák elrejtése",
            "id": "Sembunyikan Saluran",
            "it": "Nascondi canali",
            "ja": "チャンネルを隠す",
            "ko": "채널 숨기기",
            "ms": "Sembunyikan Saluran",
            "nb": "Skjul kanaler",
            "pl": "Ukryj kanały",
            "pt": "Ocultar canais",
            "ro": "Ascunde canalele",
            "ru": "Скрыть каналы",
            "sk": "Skryť kanály",
            "es": "Ocultar canales",
            "sv": "Dölj kanaler",
            "th": "ซ่อนช่อง",
            "tr": "Kanalları Gizle",
            "uk": "Приховати канали",
            "vi": "Ẩn kênh"
          },
        id: "untrap_search_hide_results_channels",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قوائم التشغيل",
            "ca": "Amaga les llistes de reproducció",
            "zh-CN": "隐藏播放列表",
            "zh-TW": "隱藏播放清單",
            "hr": "Sakrij popise za reprodukciju",
            "cs": "Skrýt seznamy skladeb",
            "da": "Skjul afspilningslister",
            "nl": "Afspeellijsten verbergen",
            "en": "Hide Playlists",
            "fi": "Piilota soittolistat",
            "fr": "Masquer les listes de lecture",
            "de": "Playlists ausblenden",
            "el": "Απόκρυψη λιστών αναπαραγωγής",
            "he": "הסתר רשימות השמעה",
            "hi": "प्लेलिस्ट छुपाएं",
            "hu": "Lejátszási listák elrejtése",
            "id": "Sembunyikan Daftar Putar",
            "it": "Nascondi playlist",
            "ja": "プレイリストを非表示にする",
            "ko": "재생목록 숨기기",
            "ms": "Sembunyikan Senarai Main",
            "nb": "Skjul spillelister",
            "pl": "Ukryj listy odtwarzania",
            "pt": "Ocultar listas de reprodução",
            "ro": "Ascunde listele de redare",
            "ru": "Скрыть плейлисты",
            "sk": "Skryť zoznamy skladieb",
            "es": "Ocultar listas de reproducción",
            "sv": "Dölj spellistor",
            "th": "ซ่อนเพลย์ลิสต์",
            "tr": "Oynatma Listelerini Gizle",
            "uk": "Приховати списки відтворення",
            "vi": "Ẩn danh sách phát"
          },
        id: "untrap_search_hide_results_playlists",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الخلطات",
            "ca": "Amaga les barreges",
            "zh-CN": "隐藏混合",
            "zh-TW": "隱藏混合",
            "hr": "Sakrij mikseve",
            "cs": "Skrýt mixy",
            "da": "Skjul blandinger",
            "nl": "Mengsels verbergen",
            "en": "Hide Mixes",
            "fi": "Piilota sekoitukset",
            "fr": "Masquer les mélanges",
            "de": "Mischungen ausblenden",
            "el": "Απόκρυψη μειγμάτων",
            "he": "הסתר מיקסים",
            "hi": "मिश्रण छिपाएँ",
            "hu": "Egyvelegek elrejtése",
            "id": "Sembunyikan Campuran",
            "it": "Nascondi mix",
            "ja": "ミックスを非表示にする",
            "ko": "믹스 숨기기",
            "ms": "Sembunyikan Campuran",
            "nb": "Skjul blandinger",
            "pl": "Ukryj miksy",
            "pt": "Ocultar mixagens",
            "ro": "Ascunde amestecurile",
            "ru": "Скрыть миксы",
            "sk": "Skryť mixy",
            "es": "Ocultar mezclas",
            "sv": "Dölj blandningar",
            "th": "ซ่อนมิกซ์",
            "tr": "Karışımları Gizle",
            "uk": "Приховати мікси",
            "vi": "Ẩn hỗn hợp"
          },
        id: "untrap_search_hide_results_mixes",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء السراويل القصيرة",
            "ca": "Amaga pantalons curts",
            "zh-CN": "隐藏短裤",
            "zh-TW": "隱藏短褲",
            "hr": "Sakrij kratke hlače",
            "cs": "Skrýt šortky",
            "da": "Skjul shorts",
            "nl": "Shorts verbergen",
            "en": "Hide Shorts",
            "fi": "Piilota shortsit",
            "fr": "Masquer les courts métrages",
            "de": "Shorts verstecken",
            "el": "Απόκρυψη σορτς",
            "he": "הסתר מכנסיים קצרים",
            "hi": "शॉर्ट्स छुपाएं",
            "hu": "Rövidnadrágok elrejtése",
            "id": "Sembunyikan Celana Pendek",
            "it": "Nascondi pantaloncini",
            "ja": "ショートパンツを隠す",
            "ko": "쇼츠 숨기기",
            "ms": "Sembunyikan Seluar Pendek",
            "nb": "Skjul shorts",
            "pl": "Ukryj szorty",
            "pt": "Ocultar Shorts",
            "ro": "Ascunde pantaloni scurți",
            "ru": "Скрыть шорты",
            "sk": "Skryť šortky",
            "es": "Ocultar pantalones cortos",
            "sv": "Göm shorts",
            "th": "ซ่อนวิดีโอสั้น",
            "tr": "Kısaları Gizle",
            "uk": "Сховати шорти",
            "vi": "Ẩn video ngắn"
          },
        id: "untrap_search_hide_results_shorts",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء بالنسبة لك، الشائعة، وما إلى ذلك",
            "ca": "Amaga per a tu, Tendències, etc",
            "zh-CN": "为你隐藏、趋势等。",
            "zh-TW": "為你隱藏、趨勢等。",
            "hr": "Sakrij za vas, U trendu itd",
            "cs": "Skrýt pro vás, Trendy atd",
            "da": "Skjul for dig, trending osv",
            "nl": "Verbergen voor jou, Trending, enz",
            "en": "Hide For You, Trending, etc",
            "fi": "Piilota sinulle, Nousussa jne",
            "fr": "Cachez-vous pour vous, tendances, etc",
            "de": "Für Sie verstecken, Trends usw",
            "el": "Hide For You, Trending, κ.λπ",
            "he": "הסתר עבורך, טרנדים וכו'",
            "hi": "आपके लिए छुपाएं, ट्रेंडिंग, आदि।",
            "hu": "Hide For You, Felkapott stb",
            "id": "Sembunyikan Untuk Anda, Trending, dll",
            "it": "Nascondi per te, Tendenze, ecc",
            "ja": "Hide For You、トレンドなど",
            "ko": "Hide For You, 인기 급상승 등",
            "ms": "Sembunyi Untuk Anda, Arah Aliran, dsb",
            "nb": "Skjul for deg, trender osv",
            "pl": "Ukryj dla Ciebie, Trendy itp",
            "pt": "Ocultar para você, tendências, etc",
            "ro": "Ascunde pentru tine, Trending etc",
            "ru": "Скрыть для вас, тренды и т. д",
            "sk": "Hide For You, Trending atď",
            "es": "Ocultar para usted, Tendencias, etc",
            "sv": "Hide For You, Trending, etc",
            "th": "ซ่อนสำหรับคุณ กระแสนิยม ฯลฯ",
            "tr": "Sizin İçin Gizle, Trend Olanlar vb",
            "uk": "Приховати для вас, Популярні тощо",
            "vi": "Ẩn cho bạn, Xu hướng, v.v"
          },
        id: "untrap_search_hide_results_for_you",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء 'يبحث الأشخاص أيضًا عن'",
            "ca": "Amaga 'La gent també cerca'",
            "zh-CN": "隐藏“人们也在搜索”",
            "zh-TW": "隱藏“人們也在搜尋”",
            "hr": "Sakrij 'Ljudi također traže'",
            "cs": "Skrýt „Lidé také hledají“",
            "da": "Skjul 'Folk søger også efter'",
            "nl": "'Mensen zoeken ook naar' verbergen",
            "en": "Hide 'People Also Search For'",
            "fi": "Piilota 'Ihmiset myös etsivät'",
            "fr": "Masquer « Les gens recherchent également »",
            "de": "„Personen suchen auch nach“ ausblenden",
            "el": "Απόκρυψη 'Οι άνθρωποι αναζητούν επίσης'",
            "he": "הסתר 'אנשים מחפשים גם'",
            "hi": "छिपाएँ 'लोग भी खोजें'",
            "hu": "'Az emberek is keresnek' elrejtése",
            "id": "Sembunyikan 'Orang Juga Mencari'",
            "it": "Nascondi 'Le persone cercano anche'",
            "ja": "「他のユーザーも検索」を非表示にする",
            "ko": "'다른 사용자가 검색하는 항목' 숨기기",
            "ms": "Sembunyikan 'Orang Juga Cari'",
            "nb": "Skjul 'Folk søker også etter'",
            "pl": "Ukryj „Ludzie też szukają”",
            "pt": "Ocultar 'As pessoas também pesquisam'",
            "ro": "Ascunde „Căută și oamenii”",
            "ru": "Скрыть «Люди также ищут»",
            "sk": "Skryť „Ľudia tiež vyhľadávajú“",
            "es": "Ocultar 'La gente también busca'",
            "sv": "Dölj 'Personer söker också efter'",
            "th": "ซ่อน 'ผู้คนยังค้นหา'",
            "tr": "'Kullanıcılar Şunu da Aradı'yı gizle",
            "uk": "Сховати 'Люди також шукають'",
            "vi": "Ẩn 'Mọi người cũng tìm kiếm'"
          },
        id: "untrap_search_hide_results_people_also_search",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء مقاطع الفيديو التي تمت مشاهدتها",
            "ca": "Amaga els vídeos vists",
            "zh-CN": "隐藏观看过的视频",
            "zh-TW": "隱藏觀看過的視頻",
            "hr": "Sakrij gledane videozapise",
            "cs": "Skrýt sledovaná videa",
            "da": "Skjul sete videoer",
            "nl": "Verberg bekeken video's",
            "en": "Hide Watched Videos",
            "fi": "Piilota katsotut videot",
            "fr": "Masquer les vidéos regardées",
            "de": "Angesehene Videos ausblenden",
            "el": "Απόκρυψη βίντεο που παρακολουθήσατε",
            "he": "הסתר סרטונים שנצפו",
            "hi": "देखे गए वीडियो छुपाएं",
            "hu": "Megtekintett videók elrejtése",
            "id": "Sembunyikan Video yang Ditonton",
            "it": "Nascondi i video guardati",
            "ja": "視聴したビデオを非表示にする",
            "ko": "시청한 동영상 숨기기",
            "ms": "Sembunyikan Video yang Ditonton",
            "nb": "Skjul sett videoer",
            "pl": "Ukryj oglądane filmy",
            "pt": "Ocultar vídeos assistidos",
            "ro": "Ascunde videoclipurile vizionate",
            "ru": "Скрыть просмотренные видео",
            "sk": "Skryť sledované videá",
            "es": "Ocultar vídeos vistos",
            "sv": "Dölj sedda videor",
            "th": "ซ่อนวิดีโอที่ดู",
            "tr": "İzlenen Videoları Gizle",
            "uk": "Приховати переглянуті відео",
            "vi": "Ẩn video đã xem"
          },
        id: "untrap_search_hide_watched_videos",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "تعطيل تمرير النتائج اللانهائية",
            "ca": "Desactiva el desplaçament de resultats infinits",
            "zh-CN": "禁用无限结果滚动",
            "zh-TW": "禁用無限結果滾動",
            "hr": "Onemogući beskonačno pomicanje rezultata",
            "cs": "Zakázat nekonečné posouvání výsledků",
            "da": "Deaktiver rulning med uendelig resultater",
            "nl": "Schakel het scrollen van oneindige resultaten uit",
            "en": "Disable Infinite Results Scrolling",
            "fi": "Poista Infinite Results -vieritys käytöstä",
            "fr": "Désactiver le défilement infini des résultats",
            "de": "Deaktivieren Sie das unendliche Scrollen der Ergebnisse",
            "el": "Απενεργοποιήστε την κύλιση άπειρων αποτελεσμάτων",
            "he": "השבת גלילת תוצאות אינסופיות",
            "hi": "अनंत परिणाम स्क्रॉलिंग अक्षम करें",
            "hu": "A végtelen eredmények görgetésének letiltása",
            "id": "Nonaktifkan Pengguliran Hasil Tak Terbatas",
            "it": "Disabilita lo scorrimento infinito dei risultati",
            "ja": "無限の結果スクロールを無効にする",
            "ko": "무한 결과 스크롤 비활성화",
            "ms": "Lumpuhkan Tatal Keputusan Infinite",
            "nb": "Deaktiver rulling med uendelig resultater",
            "pl": "Wyłącz nieskończone przewijanie wyników",
            "pt": "Desativar rolagem de resultados infinitos",
            "ro": "Dezactivați derularea rezultatelor infinite",
            "ru": "Отключить бесконечную прокрутку результатов",
            "sk": "Zakázať nekonečné posúvanie výsledkov",
            "es": "Desactivar el desplazamiento de resultados infinitos",
            "sv": "Inaktivera rullning av oändliga resultat",
            "th": "ปิดการใช้งานการเลื่อนผลลัพธ์ที่ไม่มีที่สิ้นสุด",
            "tr": "Sonsuz Sonuç Kaydırmayı Devre Dışı Bırak",
            "uk": "Вимкнути нескінченне прокручування результатів",
            "vi": "Tắt tính năng cuộn kết quả vô hạn"
          },
        id: "untrap_search_page_disable_infinite_scrolling",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الشريط الجانبي الأيمن",
            "ca": "Amaga la barra lateral dreta",
            "zh-CN": "隐藏右侧边栏",
            "zh-TW": "隱藏右側邊欄",
            "hr": "Sakrij desnu bočnu traku",
            "cs": "Skrýt pravý boční panel",
            "da": "Skjul højre sidebjælke",
            "nl": "Rechterzijbalk verbergen",
            "en": "Hide Right Sidebar",
            "fi": "Piilota oikea sivupalkki",
            "fr": "Masquer la barre latérale droite",
            "de": "Rechte Seitenleiste ausblenden",
            "el": "Απόκρυψη της δεξιάς πλευρικής γραμμής",
            "he": "הסתר סרגל צד ימין",
            "hi": "दायां साइडबार छुपाएं",
            "hu": "Jobb oldalsáv elrejtése",
            "id": "Sembunyikan Sidebar Kanan",
            "it": "Nascondi la barra laterale destra",
            "ja": "右サイドバーを非表示にする",
            "ko": "오른쪽 사이드바 숨기기",
            "ms": "Sembunyikan Bar Sisi Kanan",
            "nb": "Skjul høyre sidefelt",
            "pl": "Ukryj prawy pasek boczny",
            "pt": "Ocultar barra lateral direita",
            "ro": "Ascundeți bara laterală din dreapta",
            "ru": "Скрыть правую боковую панель",
            "sk": "Skryť pravý bočný panel",
            "es": "Ocultar barra lateral derecha",
            "sv": "Dölj höger sidofält",
            "th": "ซ่อนแถบด้านข้างขวา",
            "tr": "Sağ Kenar Çubuğunu Gizle",
            "uk": "Приховати праву бічну панель",
            "vi": "Ẩn thanh bên phải"
          },
        id: "untrap_search_page_hide_right_sidebar",
        defaultValue: false
    },
    {
        type: "select",
        name: {
            "ar": "ترتيب النتائج حسب",
            "ca": "Ordena els resultats per",
            "zh-CN": "结果排序依据",
            "zh-TW": "結果排序依據",
            "hr": "Poredaj rezultate po",
            "cs": "Seřadit výsledky podle",
            "da": "Sorter resultater efter",
            "nl": "Sorteer Resultaten op",
            "en": "Sort Results by",
            "fi": "Lajittele tulokset",
            "fr": "Trier les résultats par",
            "de": "Sortiere Ergebnisse nach",
            "el": "Ταξινόμηση αποτελεσμάτων κατά",
            "he": "מיין תוצאות לפי",
            "hi": "द्वारा परिणामों को छांटें",
            "hu": "Az eredmények rendezése a következő szerint",
            "id": "Urutkan Hasil berdasarkan",
            "it": "Ordina i risultati per",
            "ja": "結果の並べ替え基準",
            "ko": "결과 정렬 기준",
            "ms": "Isih Keputusan mengikut",
            "nb": "Sorter resultater etter",
            "pl": "Posortuj wyniki po",
            "pt": "Classificar resultados por",
            "ro": "Sortați rezultatele după",
            "ru": "Сортировать результаты по",
            "sk": "Zoradiť výsledky podľa",
            "es": "Ordenar resultados por",
            "sv": "Sortera resultat efter",
            "th": "เรียงลำดับผลลัพธ์ตาม",
            "tr": "Sonuçları şuna göre sırala:",
            "uk": "Сортувати результати за",
            "vi": "Sắp xếp kết quả theo"
          },
        id: "untrap_search_page_sort_by",
        defaultValue: "relevance",
        selects: [
            {
                name: {
                    "ar": "الصلة (افتراضي)",
                    "ca": "Rellevància (per defecte)",
                    "zh-CN": "相关性（默认）",
                    "zh-TW": "相關性（預設）",
                    "hr": "Relevantnost (zadano)",
                    "cs": "Relevance (výchozí)",
                    "da": "Relevans (standard)",
                    "nl": "Relevantie (standaard)",
                    "en": "Relevance (Default)",
                    "fi": "Osuvuus (oletus)",
                    "fr": "Pertinence (par défaut)",
                    "de": "Relevanz (Standard)",
                    "el": "Συνάφεια (Προεπιλογή)",
                    "he": "רלוונטיות (ברירת מחדל)",
                    "hi": "प्रासंगिकता (डिफ़ॉल्ट)",
                    "hu": "Relevancia (alapértelmezett)",
                    "id": "Relevansi (Bawaan)",
                    "it": "Pertinenza (impostazione predefinita)",
                    "ja": "関連性 (デフォルト)",
                    "ko": "관련성(기본값)",
                    "ms": "Perkaitan (Lalai)",
                    "nb": "Relevans (standard)",
                    "pl": "Trafność (domyślna)",
                    "pt": "Relevância (padrão)",
                    "ro": "Relevanță (implicit)",
                    "ru": "Релевантность (по умолчанию)",
                    "sk": "Relevancia (predvolená)",
                    "es": "Relevancia (predeterminado)",
                    "sv": "Relevans (standard)",
                    "th": "ความเกี่ยวข้อง (ค่าเริ่มต้น)",
                    "tr": "Alaka Düzeyi (Varsayılan)",
                    "uk": "Релевантність (за замовчуванням)",
                    "vi": "Mức độ liên quan (Mặc định)"
                  },
                id: "relevance"
            },
            {
                name: {
                    "ar": "تاريخ الرفع",
                    "ca": "Data de càrrega",
                    "zh-CN": "上传日期",
                    "zh-TW": "上傳日期",
                    "hr": "Datum učitavanja",
                    "cs": "Datum nahrání",
                    "da": "Upload dato",
                    "nl": "Upload datum",
                    "en": "Upload Date",
                    "fi": "Latauspäivämäärä",
                    "fr": "Date de dépôt",
                    "de": "Datum des Hochladens",
                    "el": "Ημερομηνία ανεβάσματος",
                    "he": "תאריך העלאה",
                    "hi": "बार डालने की तारिक",
                    "hu": "Feltöltés dátuma",
                    "id": "Tanggal Pengunggahan",
                    "it": "Data di caricamento",
                    "ja": "アップロード日",
                    "ko": "업로드 날짜",
                    "ms": "Tarikh muat-naik",
                    "nb": "Opplastnings dato",
                    "pl": "Data przesłania",
                    "pt": "Data de upload",
                    "ro": "Data de incarcare",
                    "ru": "Дата загрузки",
                    "sk": "Dátum nahrania",
                    "es": "Fecha de carga",
                    "sv": "Uppladdningsdatum",
                    "th": "วันที่อัพโหลด",
                    "tr": "Yükleme tarihi",
                    "uk": "Дата завантаження",
                    "vi": "Ngày tải lên"
                  },
                id: "uploadDate"
            },
            {
                name: {
                    "ar": "عرض العدد",
                    "ca": "Recompte de visualitzacions",
                    "zh-CN": "查看次数",
                    "zh-TW": "查看次數",
                    "hr": "Brojac pregleda",
                    "cs": "Počet zobrazení",
                    "da": "Visningstal",
                    "nl": "Kijkcijfers",
                    "en": "View Count",
                    "fi": "Katselukertojen määrä",
                    "fr": "Nombre de vues",
                    "de": "Anzahl anzeigen",
                    "el": "Πλήθος προβολών",
                    "he": "ספירת צפיות",
                    "hi": "देखे जाने की संख्या",
                    "hu": "Megtekintések száma",
                    "id": "Lihat Jumlah",
                    "it": "Visualizza conteggio",
                    "ja": "ビュー数",
                    "ko": "조회수",
                    "ms": "Kiraan Pandangan",
                    "nb": "Seertall",
                    "pl": "Licznik wyświetleń",
                    "pt": "Ver contagem",
                    "ro": "Număr de vizualizări",
                    "ru": "Количество просмотров",
                    "sk": "Počet zobrazení",
                    "es": "Conteo de visitas",
                    "sv": "Antal visningar",
                    "th": "จำนวนการดู",
                    "tr": "Sayıyı Görüntüle",
                    "uk": "Кількість переглядів",
                    "vi": "Lượng xem"
                  },
                id: "viewCount"
            },
            {
                name: {
                    "ar": "تقييم",
                    "ca": "Valoració",
                    "zh-CN": "评分",
                    "zh-TW": "評分",
                    "hr": "Ocjena",
                    "cs": "Hodnocení",
                    "da": "Bedømmelse",
                    "nl": "Beoordeling",
                    "en": "Rating",
                    "fi": "Luokitus",
                    "fr": "Notation",
                    "de": "Bewertung",
                    "el": "Εκτίμηση",
                    "he": "דֵרוּג",
                    "hi": "रेटिंग",
                    "hu": "Értékelés",
                    "id": "Peringkat",
                    "it": "Valutazione",
                    "ja": "評価",
                    "ko": "평가",
                    "ms": "Penilaian",
                    "nb": "Vurdering",
                    "pl": "Ocena",
                    "pt": "Avaliação",
                    "ro": "Evaluare",
                    "ru": "Рейтинг",
                    "sk": "Hodnotenie",
                    "es": "Clasificación",
                    "sv": "Betyg",
                    "th": "เรตติ้ง",
                    "tr": "Değerlendirme",
                    "uk": "Рейтинг",
                    "vi": "Xếp hạng"
                  },
                id: "rating"
            }
        ]
    }
];

const searchPageDesktopGroups_Buttons = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'حول هذه النتائج'",
            "ca": "Amaga el botó 'Sobre aquests resultats'",
            "zh-CN": "隐藏“关于这些结果”按钮",
            "zh-TW": "隱藏「關於這些結果」按鈕",
            "hr": "Sakrij gumb 'O ovim rezultatima'",
            "cs": "Skrýt tlačítko „O těchto výsledcích“",
            "da": "Skjul knappen 'Om disse resultater'",
            "nl": "Knop 'Over deze resultaten' verbergen",
            "en": "Hide 'About These Results' Button",
            "fi": "Piilota 'Tietoja näistä tuloksista' -painike",
            "fr": "Masquer le bouton « À propos de ces résultats »",
            "de": "Schaltfläche „Über diese Ergebnisse“ ausblenden",
            "el": "Απόκρυψη του κουμπιού 'Σχετικά με αυτά τα αποτελέσματα'",
            "he": "הסתר את הלחצן 'אודות תוצאות אלו'",
            "hi": "'इन परिणामों के बारे में' बटन छिपाएँ",
            "hu": "'Az eredményekről' gomb elrejtése",
            "id": "Sembunyikan Tombol 'Tentang Hasil Ini'",
            "it": "Nascondi il pulsante 'Informazioni su questi risultati'",
            "ja": "「これらの結果について」ボタンを非表示にする",
            "ko": "'이 결과 정보' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Mengenai Keputusan Ini'",
            "nb": "Skjul 'Om disse resultatene'-knappen",
            "pl": "Ukryj przycisk „Informacje o tych wynikach”",
            "pt": "Ocultar o botão 'Sobre estes resultados'",
            "ro": "Ascundeți butonul „Despre aceste rezultate”",
            "ru": "Скрыть кнопку «Об этих результатах»",
            "sk": "Skryť tlačidlo „O týchto výsledkoch“",
            "es": "Ocultar el botón 'Acerca de estos resultados'",
            "sv": "Dölj knappen 'Om dessa resultat'",
            "th": "ซ่อนปุ่ม 'เกี่ยวกับผลลัพธ์เหล่านี้'",
            "tr": "'Bu Sonuçlar Hakkında' Düğmesini Gizle",
            "uk": "Сховати кнопку «Про ці результати»",
            "vi": "Ẩn nút 'Giới thiệu về những kết quả này'"
          },
        id: "untrap_search_page_hide_about_these_results",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'المرشحات'",
            "ca": "Amaga el botó 'Filtres'",
            "zh-CN": "隐藏“过滤器”按钮",
            "zh-TW": "隱藏“過濾器”按鈕",
            "hr": "Sakrij gumb 'Filtri'",
            "cs": "Skrýt tlačítko 'Filtry'",
            "da": "Skjul knappen 'Filtre'",
            "nl": "Knop 'Filters' verbergen",
            "en": "Hide 'Filters' Button",
            "fi": "Piilota 'Suodattimet'-painike",
            "fr": "Masquer le bouton « Filtres »",
            "de": "Schaltfläche „Filter“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Φίλτρα'",
            "he": "הסתר כפתור 'מסננים'",
            "hi": "'फ़िल्टर' बटन छिपाएँ",
            "hu": "A „Szűrők” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Filter'",
            "it": "Nascondi il pulsante 'Filtri'",
            "ja": "「フィルター」ボタンを非表示にする",
            "ko": "'필터' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Penapis'",
            "nb": "Skjul 'Filter'-knappen",
            "pl": "Ukryj przycisk „Filtry”",
            "pt": "Ocultar botão 'Filtros'",
            "ro": "Ascundeți butonul „Filtre”",
            "ru": "Скрыть кнопку «Фильтры»",
            "sk": "Skryť tlačidlo 'Filtre'",
            "es": "Ocultar el botón 'Filtros'",
            "sv": "Dölj 'Filter'-knappen",
            "th": "ซ่อนปุ่ม 'ตัวกรอง'",
            "tr": "'Filtreler' Düğmesini Gizle",
            "uk": "Сховати кнопку «Фільтри»",
            "vi": "Ẩn nút 'Bộ lọc'"
          },
        id: "untrap_search_page_hide_filters",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء فئات البحث",
            "ca": "Amaga les categories de cerca",
            "zh-CN": "隐藏搜索类别",
            "zh-TW": "隱藏搜尋類別",
            "hr": "Sakrij kategorije pretraživanja",
            "cs": "Skrýt vyhledávací kategorie",
            "da": "Skjul søgekategorier",
            "nl": "Zoekcategorieën verbergen",
            "en": "Hide Search Categories",
            "fi": "Piilota hakukategoriat",
            "fr": "Masquer les catégories de recherche",
            "de": "Suchkategorien ausblenden",
            "el": "Απόκρυψη κατηγοριών αναζήτησης",
            "he": "הסתר קטגוריות חיפוש",
            "hi": "खोज श्रेणियाँ छिपाएँ",
            "hu": "Keresési kategóriák elrejtése",
            "id": "Sembunyikan Kategori Pencarian",
            "it": "Nascondi categorie di ricerca",
            "ja": "検索カテゴリを非表示にする",
            "ko": "검색 카테고리 숨기기",
            "ms": "Sembunyikan Kategori Carian",
            "nb": "Skjul søkekategorier",
            "pl": "Ukryj kategorie wyszukiwania",
            "pt": "Ocultar categorias de pesquisa",
            "ro": "Ascundeți categoriile de căutare",
            "ru": "Скрыть категории поиска",
            "sk": "Skryť kategórie vyhľadávania",
            "es": "Ocultar categorías de búsqueda",
            "sv": "Dölj sökkategorier",
            "th": "ซ่อนหมวดหมู่การค้นหา",
            "tr": "Arama Kategorilerini Gizle",
            "uk": "Приховати категорії пошуку",
            "vi": "Ẩn danh mục tìm kiếm"
          },
        id: "untrap_search_page_hide_search_categories",
        defaultValue: false
    }
]

const searchPageDesktopGroups_Ads = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء المواقع التي يتم الترويج لها",
            "ca": "Amaga els llocs web promocionats",
            "zh-CN": "隐藏推广网站",
            "zh-TW": "隱藏推廣網站",
            "hr": "Sakrij promovirane web stranice",
            "cs": "Skrýt propagované webové stránky",
            "da": "Skjul promoverede websteder",
            "nl": "Gesponsorde websites verbergen",
            "en": "Hide Promoted Websites",
            "fi": "Piilota korostetut verkkosivustot",
            "fr": "Masquer les sites Web sponsorisés",
            "de": "Gesponserte Websites ausblenden",
            "el": "Απόκρυψη ιστοτόπων που προωθούνται",
            "he": "הסתר אתרים מקודמים",
            "hi": "प्रचारित वेबसाइट छिपाएँ",
            "hu": "Promotált webhelyek elrejtése",
            "id": "Sembunyikan Situs Web yang Dipromosikan",
            "it": "Nascondi siti web sponsorizzati",
            "ja": "プロモートされた Web サイトを非表示にする",
            "ko": "프로모션된 웹사이트 숨기기",
            "ms": "Sembunyikan Tapak Web Digalakkan",
            "nb": "Skjul markedsførte nettsteder",
            "pl": "Ukryj promowane witryny internetowe",
            "pt": "Ocultar sites promovidos",
            "ro": "Ascunde site-urile promovate",
            "ru": "Скрыть продвигаемые сайты",
            "sk": "Skryť propagované webové stránky",
            "es": "Ocultar sitios web promocionados",
            "sv": "Dölj marknadsförda webbplatser",
            "th": "ซ่อนเว็บไซต์ที่ได้รับการโปรโมต",
            "tr": "Tanıtılan Web Sitelerini Gizle",
            "uk": "Приховати рекламовані сайти",
            "vi": "Ẩn trang web được quảng cáo"
          },
        id: "untrap_search_hide_ads_promoted_websites",
        defaultValue: true
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء مقاطع الفيديو الدعائية",
            "ca": "Amaga els vídeos promocionats",
            "zh-CN": "隐藏推荐视频",
            "zh-TW": "隱藏推薦影片",
            "hr": "Sakrij promovirane videozapise",
            "cs": "Skrýt sponzorovaná videa",
            "da": "Skjul promoverede videoer",
            "nl": "Gesponsorde video's verbergen",
            "en": "Hide Promoted Videos",
            "fi": "Piilota korostetut videot",
            "fr": "Masquer les vidéos sponsorisées",
            "de": "Gesponserte Videos ausblenden",
            "el": "Απόκρυψη βίντεο που προωθούνται",
            "he": "הסתר סרטונים מקודמים",
            "hi": "प्रचारित वीडियो छिपाएँ",
            "hu": "Promotált videók elrejtése",
            "id": "Sembunyikan Video yang Dipromosikan",
            "it": "Nascondi video sponsorizzati",
            "ja": "プロモートされたビデオを非表示にする",
            "ko": "프로모션 동영상 숨기기",
            "ms": "Sembunyikan Video Galakan",
            "nb": "Skjul sponsede videoer",
            "pl": "Ukryj promowane filmy",
            "pt": "Ocultar vídeos promovidos",
            "ro": "Ascunde videoclipurile promovate",
            "ru": "Скрыть продвигаемые видео",
            "sk": "Skryť propagované videá",
            "es": "Ocultar vídeos promocionados",
            "sv": "Dölj sponsrade videor",
            "th": "ซ่อนวิดีโอโปรโมต",
            "tr": "Tanıtılan Videoları Gizle",
            "uk": "Приховати рекламоване відео",
            "vi": "Ẩn video quảng cáo"
          },
        id: "untrap_search_hide_ads_promoted_videos",
        defaultValue: true
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء المنتجات المقترحة",
            "ca": "Amaga els productes suggerits",
            "zh-CN": "隐藏推荐产品",
            "zh-TW": "隱藏推薦產品",
            "hr": "Sakrij predložene proizvode",
            "cs": "Skrýt navrhované produkty",
            "da": "Skjul foreslåede produkter",
            "nl": "Voorgestelde producten verbergen",
            "en": "Hide Suggested Products",
            "fi": "Piilota ehdotetut tuotteet",
            "fr": "Masquer les produits suggérés",
            "de": "Vorgeschlagene Produkte ausblenden",
            "el": "Απόκρυψη προτεινόμενων προϊόντων",
            "he": "הסתר מוצרים מוצעים",
            "hi": "सुझाए गए उत्पाद छिपाएँ",
            "hu": "Javasolt termékek elrejtése",
            "id": "Sembunyikan Produk yang Disarankan",
            "it": "Nascondi prodotti suggeriti",
            "ja": "提案された製品を非表示にする",
            "ko": "추천 제품 숨기기",
            "ms": "Sembunyikan Produk yang Dicadangkan",
            "nb": "Skjul foreslåtte produkter",
            "pl": "Ukryj sugerowane produkty",
            "pt": "Ocultar produtos sugeridos",
            "ro": "Ascundeți produsele sugerate",
            "ru": "Скрыть предлагаемые продукты",
            "sk": "Skryť navrhované produkty",
            "es": "Ocultar productos sugeridos",
            "sv": "Dölj föreslagna produkter",
            "th": "ซ่อนผลิตภัณฑ์ที่แนะนำ",
            "tr": "Önerilen Ürünleri Gizle",
            "uk": "Приховати запропоновані продукти",
            "vi": "Ẩn sản phẩm được đề xuất"
          },
        id: "untrap_search_hide_ads_suggested_products",
        defaultValue: true
    }
]


// MARK: - Mobile Groups

const searchPageMobileGroups_Results = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء القنوات",
            "ca": "Amaga els canals",
            "zh-CN": "隐藏频道",
            "zh-TW": "隱藏頻道",
            "hr": "Sakrij kanale",
            "cs": "Skrýt kanály",
            "da": "Skjul kanaler",
            "nl": "Kanalen verbergen",
            "en": "Hide Channels",
            "fi": "Piilota kanavat",
            "fr": "Masquer les chaînes",
            "de": "Kanäle ausblenden",
            "el": "Απόκρυψη καναλιών",
            "he": "הסתר ערוצים",
            "hi": "चैनल छिपाएँ",
            "hu": "Csatornák elrejtése",
            "id": "Sembunyikan Saluran",
            "it": "Nascondi canali",
            "ja": "チャンネルを隠す",
            "ko": "채널 숨기기",
            "ms": "Sembunyikan Saluran",
            "nb": "Skjul kanaler",
            "pl": "Ukryj kanały",
            "pt": "Ocultar canais",
            "ro": "Ascunde canalele",
            "ru": "Скрыть каналы",
            "sk": "Skryť kanály",
            "es": "Ocultar canales",
            "sv": "Dölj kanaler",
            "th": "ซ่อนช่อง",
            "tr": "Kanalları Gizle",
            "uk": "Приховати канали",
            "vi": "Ẩn kênh"
          },
        id: "untrap_search_hide_results_channels",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قوائم التشغيل",
            "ca": "Amaga les llistes de reproducció",
            "zh-CN": "隐藏播放列表",
            "zh-TW": "隱藏播放清單",
            "hr": "Sakrij popise za reprodukciju",
            "cs": "Skrýt seznamy skladeb",
            "da": "Skjul afspilningslister",
            "nl": "Afspeellijsten verbergen",
            "en": "Hide Playlists",
            "fi": "Piilota soittolistat",
            "fr": "Masquer les listes de lecture",
            "de": "Playlists ausblenden",
            "el": "Απόκρυψη λιστών αναπαραγωγής",
            "he": "הסתר רשימות השמעה",
            "hi": "प्लेलिस्ट छुपाएं",
            "hu": "Lejátszási listák elrejtése",
            "id": "Sembunyikan Daftar Putar",
            "it": "Nascondi playlist",
            "ja": "プレイリストを非表示にする",
            "ko": "재생목록 숨기기",
            "ms": "Sembunyikan Senarai Main",
            "nb": "Skjul spillelister",
            "pl": "Ukryj listy odtwarzania",
            "pt": "Ocultar listas de reprodução",
            "ro": "Ascunde listele de redare",
            "ru": "Скрыть плейлисты",
            "sk": "Skryť zoznamy skladieb",
            "es": "Ocultar listas de reproducción",
            "sv": "Dölj spellistor",
            "th": "ซ่อนเพลย์ลิสต์",
            "tr": "Oynatma Listelerini Gizle",
            "uk": "Приховати списки відтворення",
            "vi": "Ẩn danh sách phát"
          },
        id: "untrap_search_hide_results_playlists",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء السراويل القصيرة",
            "ca": "Amaga pantalons curts",
            "zh-CN": "隐藏短裤",
            "zh-TW": "隱藏短褲",
            "hr": "Sakrij kratke hlače",
            "cs": "Skrýt šortky",
            "da": "Skjul shorts",
            "nl": "Shorts verbergen",
            "en": "Hide Shorts",
            "fi": "Piilota shortsit",
            "fr": "Masquer les courts métrages",
            "de": "Shorts verstecken",
            "el": "Απόκρυψη σορτς",
            "he": "הסתר מכנסיים קצרים",
            "hi": "शॉर्ट्स छुपाएं",
            "hu": "Rövidnadrágok elrejtése",
            "id": "Sembunyikan Celana Pendek",
            "it": "Nascondi pantaloncini",
            "ja": "ショートパンツを隠す",
            "ko": "쇼츠 숨기기",
            "ms": "Sembunyikan Seluar Pendek",
            "nb": "Skjul shorts",
            "pl": "Ukryj szorty",
            "pt": "Ocultar Shorts",
            "ro": "Ascunde pantaloni scurți",
            "ru": "Скрыть шорты",
            "sk": "Skryť šortky",
            "es": "Ocultar pantalones cortos",
            "sv": "Göm shorts",
            "th": "ซ่อนวิดีโอสั้น",
            "tr": "Kısaları Gizle",
            "uk": "Сховати шорти",
            "vi": "Ẩn video ngắn"
          },
        id: "untrap_search_hide_results_shorts",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء مقاطع الفيديو التي تمت مشاهدتها",
            "ca": "Amaga els vídeos vists",
            "zh-CN": "隐藏观看过的视频",
            "zh-TW": "隱藏觀看過的視頻",
            "hr": "Sakrij gledane videozapise",
            "cs": "Skrýt sledovaná videa",
            "da": "Skjul sete videoer",
            "nl": "Verberg bekeken video's",
            "en": "Hide Watched Videos",
            "fi": "Piilota katsotut videot",
            "fr": "Masquer les vidéos regardées",
            "de": "Angesehene Videos ausblenden",
            "el": "Απόκρυψη βίντεο που παρακολουθήσατε",
            "he": "הסתר סרטונים שנצפו",
            "hi": "देखे गए वीडियो छुपाएं",
            "hu": "Megtekintett videók elrejtése",
            "id": "Sembunyikan Video yang Ditonton",
            "it": "Nascondi i video guardati",
            "ja": "視聴したビデオを非表示にする",
            "ko": "시청한 동영상 숨기기",
            "ms": "Sembunyikan Video yang Ditonton",
            "nb": "Skjul sett videoer",
            "pl": "Ukryj oglądane filmy",
            "pt": "Ocultar vídeos assistidos",
            "ro": "Ascunde videoclipurile vizionate",
            "ru": "Скрыть просмотренные видео",
            "sk": "Skryť sledované videá",
            "es": "Ocultar vídeos vistos",
            "sv": "Dölj sedda videor",
            "th": "ซ่อนวิดีโอที่ดู",
            "tr": "İzlenen Videoları Gizle",
            "uk": "Приховати переглянуті відео",
            "vi": "Ẩn video đã xem"
          },
        id: "untrap_search_hide_watched_videos",
        defaultValue: false
    }
];


const searchPageMobileGroups_Ads = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء المواقع التي يتم الترويج لها",
            "ca": "Amaga els llocs web promocionats",
            "zh-CN": "隐藏推广网站",
            "zh-TW": "隱藏推廣網站",
            "hr": "Sakrij promovirane web stranice",
            "cs": "Skrýt propagované webové stránky",
            "da": "Skjul promoverede websteder",
            "nl": "Gesponsorde websites verbergen",
            "en": "Hide Promoted Websites",
            "fi": "Piilota korostetut verkkosivustot",
            "fr": "Masquer les sites Web sponsorisés",
            "de": "Gesponserte Websites ausblenden",
            "el": "Απόκρυψη ιστοτόπων που προωθούνται",
            "he": "הסתר אתרים מקודמים",
            "hi": "प्रचारित वेबसाइट छिपाएँ",
            "hu": "Promotált webhelyek elrejtése",
            "id": "Sembunyikan Situs Web yang Dipromosikan",
            "it": "Nascondi siti Web sponsorizzati",
            "ja": "プロモートされた Web サイトを非表示にする",
            "ko": "프로모션된 웹사이트 숨기기",
            "ms": "Sembunyikan Tapak Web Digalakkan",
            "nb": "Skjul markedsførte nettsteder",
            "pl": "Ukryj promowane witryny internetowe",
            "pt": "Ocultar sites promovidos",
            "ro": "Ascunde site-urile promovate",
            "ru": "Скрыть продвигаемые сайты",
            "sk": "Skryť propagované webové stránky",
            "es": "Ocultar sitios web promocionados",
            "sv": "Dölj marknadsförda webbplatser",
            "th": "ซ่อนเว็บไซต์ที่ได้รับการโปรโมต",
            "tr": "Tanıtılan Web Sitelerini Gizle",
            "uk": "Приховати рекламовані сайти",
            "vi": "Ẩn trang web được quảng cáo"
          },
        id: "untrap_search_hide_ads_promoted_websites",
        defaultValue: true
    }
];

// MARK: - Builder

// Desktop

const searchPageDesktopGroups = [
    {
        groupName: {
            "ar": "نتائج البحث",
            "ca": "Resultats de la cerca",
            "zh-CN": "搜索结果",
            "zh-TW": "搜尋結果",
            "hr": "Rezultati pretraživanja",
            "cs": "Výsledky vyhledávání",
            "da": "Søgeresultater",
            "nl": "Zoekresultaten",
            "en": "Search Results",
            "fi": "Hakutulokset",
            "fr": "Résultats de recherche",
            "de": "Suchergebnisse",
            "el": "Αποτελέσματα αναζήτησης",
            "he": "תוצאות חיפוש",
            "hi": "खोज के परिणाम",
            "hu": "Keresési eredmények",
            "id": "Hasil Pencarian",
            "it": "Risultati di ricerca",
            "ja": "の検索結果",
            "ko": "검색 결과",
            "ms": "Keputusan Carian",
            "nb": "Søkeresultater",
            "pl": "Wyniki wyszukiwania",
            "pt": "Procurar Resultados",
            "ro": "Rezultatele cautarii",
            "ru": "Результаты поиска",
            "sk": "Výsledky vyhľadávania",
            "es": "Resultados de la búsqueda",
            "sv": "Sökresultat",
            "th": "ผลการค้นหา",
            "tr": "Arama Sonuçları",
            "uk": "Результати пошуку",
            "vi": "Kết quả tìm kiếm"
          },
        groupId: "results",
        parentCategoryId: "searchPage",
        options: searchPageDesktopGroups_Results
    },
    {
        groupName: {
            "ar": "أزرار",
            "ca": "Botons",
            "zh-CN": "纽扣",
            "zh-TW": "羈扣",
            "hr": "Gumbi",
            "cs": "Tlačítka",
            "da": "Knapper",
            "nl": "Toetsen",
            "en": "Buttons",
            "fi": "Painikkeet",
            "fr": "Boutons",
            "de": "Tasten",
            "el": "Κουμπιά",
            "he": "כפתורים",
            "hi": "बटन",
            "hu": "Gombok",
            "id": "Tombol",
            "it": "Pulsanti",
            "ja": "ボタン",
            "ko": "버튼",
            "ms": "Butang",
            "nb": "Knapper",
            "pl": "Guziki",
            "pt": "Botões",
            "ro": "Butoane",
            "ru": "Кнопки",
            "sk": "Tlačidlá",
            "es": "Botones",
            "sv": "Knappar",
            "th": "ปุ่ม",
            "tr": "Düğmeler",
            "uk": "Кнопки",
            "vi": "nút"
          },
        groupId: "buttons",
        parentCategoryId: "searchPage",
        options: searchPageDesktopGroups_Buttons
    },
    {
        groupName: {
            "ar": "إعلانات",
            "ca": "Publicitat",
            "zh-CN": "广告",
            "zh-TW": "廣告",
            "hr": "Oglas",
            "cs": "Reklama",
            "da": "Annonce",
            "nl": "Advertentie",
            "en": "Advertisment",
            "fi": "Mainos",
            "fr": "Publicité",
            "de": "Werbung",
            "el": "Διαφήμιση",
            "he": "פרסומת",
            "hi": "विज्ञापन",
            "hu": "Reklám",
            "id": "Iklan",
            "it": "Pubblicità",
            "ja": "広告",
            "ko": "광고",
            "ms": "Iklan",
            "nb": "Annonse",
            "pl": "Reklama",
            "pt": "Propaganda",
            "ro": "Reclamă",
            "ru": "Реклама",
            "sk": "Reklama",
            "es": "Anuncio",
            "sv": "Annons",
            "th": "โฆษณา",
            "tr": "Reklam",
            "uk": "Реклама",
            "vi": "Quảng cáo"
          },
        groupId: "ads",
        parentCategoryId: "searchPage",
        options: searchPageDesktopGroups_Ads
    }
];

// Mobile

const searchPageMobileGroups = [
    {
        groupName: {
            "ar": "نتائج البحث",
            "ca": "Resultats de la cerca",
            "zh-CN": "搜索结果",
            "zh-TW": "搜尋結果",
            "hr": "Rezultati pretraživanja",
            "cs": "Výsledky vyhledávání",
            "da": "Søgeresultater",
            "nl": "Zoekresultaten",
            "en": "Search Results",
            "fi": "Hakutulokset",
            "fr": "Résultats de recherche",
            "de": "Suchergebnisse",
            "el": "Αποτελέσματα αναζήτησης",
            "he": "תוצאות חיפוש",
            "hi": "खोज के परिणाम",
            "hu": "Keresési eredmények",
            "id": "Hasil Pencarian",
            "it": "Risultati di ricerca",
            "ja": "の検索結果",
            "ko": "검색 결과",
            "ms": "Keputusan Carian",
            "nb": "Søkeresultater",
            "pl": "Wyniki wyszukiwania",
            "pt": "Procurar Resultados",
            "ro": "Rezultatele cautarii",
            "ru": "Результаты поиска",
            "sk": "Výsledky vyhľadávania",
            "es": "Resultados de la búsqueda",
            "sv": "Sökresultat",
            "th": "ผลการค้นหา",
            "tr": "Arama Sonuçları",
            "uk": "Результати пошуку",
            "vi": "Kết quả tìm kiếm"
          },
        groupId: "results",
        parentCategoryId: "searchPage",
        options: searchPageMobileGroups_Results
    },
    {
        groupName: {
            "ar": "إعلانات",
            "ca": "Publicitat",
            "zh-CN": "广告",
            "zh-TW": "廣告",
            "hr": "Oglas",
            "cs": "Reklama",
            "da": "Annonce",
            "nl": "Advertentie",
            "en": "Advertisment",
            "fi": "Mainos",
            "fr": "Publicité",
            "de": "Werbung",
            "el": "Διαφήμιση",
            "he": "פרסומת",
            "hi": "विज्ञापन",
            "hu": "Reklám",
            "id": "Iklan",
            "it": "Pubblicità",
            "ja": "広告",
            "ko": "광고",
            "ms": "Iklan",
            "nb": "Annonse",
            "pl": "Reklama",
            "pt": "Propaganda",
            "ro": "Reclamă",
            "ru": "Реклама",
            "sk": "Reklama",
            "es": "Anuncio",
            "sv": "Annons",
            "th": "โฆษณา",
            "tr": "Reklam",
            "uk": "Реклама",
            "vi": "Quảng cáo"
          },
        groupId: "ads",
        parentCategoryId: "searchPage",
        options: searchPageMobileGroups_Ads
    }
]
