// MARK: - Desktop Groups

const shortsPageDesktopGroups_Other = [
    {
       type: "checkbox",
       name: {
           "ar": "تعطيل التمرير",
           "ca": "Desactiva el desplaçament",
           "zh-CN": "禁用滚动",
           "zh-TW": "禁用滾動",
           "hr": "Onemogući pomicanje",
           "cs": "Zakázat rolování",
           "da": "Deaktiver rulning",
           "nl": "Schakel scrollen uit",
           "en": "Disable Scrolling",
           "fi": "Poista vieritys käytöstä",
           "fr": "Désactiver le défilement",
           "de": "Scrollen deaktivieren",
           "el": "Απενεργοποίηση κύλισης",
           "he": "השבת את הגלילה",
           "hi": "स्क्रॉलिंग अक्षम करें",
           "hu": "Görgetés letiltása",
           "id": "Nonaktifkan Pengguliran",
           "it": "Disabilita scorrimento",
           "ja": "スクロールを無効にする",
           "ko": "스크롤 비활성화",
           "ms": "Lumpuhkan Penatalan",
           "no": "Deaktiver rulling",
           "pl": "Wyłącz przewijanie",
           "pt": "Desativar rolagem",
           "ro": "Dezactivați derularea",
           "ru": "Отключить прокрутку",
           "sk": "Zakázať posúvanie",
           "es": "Deshabilitar el desplazamiento",
           "sv": "Inaktivera rullning",
           "th": "ปิดการใช้งานการเลื่อน",
           "tr": "Kaydırmayı Devre Dışı Bırak",
           "uk": "Вимкнути прокручування",
           "vi": "Vô hiệu hóa cuộn"
         },
       id: "untrap_shorts_page_disable_scrolling",
       defaultValue: false
    }
]

const shortsPageDesktopGroups_Redirects = [
    {
        type: "checkbox",
        name: {
            "ar": "إعادة توجيه الشورتات إلى المشغل العادي",
            "ca": "Redirigeix ​​els curts al reproductor normal",
            "zh-CN": "将 Shorts 重定向到普通播放器",
            "zh-TW": "將 Shorts 重新導向到普通播放器",
            "hr": "Preusmjeri Shorts na Normal Player",
            "cs": "Přesměrujte Shorts na Normální přehrávač",
            "da": "Omdiriger shorts til normal afspiller",
            "nl": "Shorts omleiden naar normale speler",
            "en": "Redirect Shorts to Normal Player",
            "fi": "Ohjaa Shortsit normaaliin soittimeen",
            "fr": "Rediriger les courts métrages vers le joueur normal",
            "de": "Shorts zum normalen Spieler umleiten",
            "el": "Ανακατεύθυνση Shorts σε Κανονικό πρόγραμμα αναπαραγωγής",
            "he": "הפנה מחדש את הקצרים לנגן רגיל",
            "hi": "शॉर्ट्स को सामान्य प्लेयर पर रीडायरेक्ट करें",
            "hu": "A Shorts-ok átirányítása normál lejátszóra",
            "id": "Alihkan Shorts ke Pemutar Normal",
            "it": "Reindirizza i cortometraggi al giocatore normale",
            "ja": "ショート動画を通常のプレーヤーにリダイレクトする",
            "ko": "Shorts를 일반 플레이어로 리디렉션",
            "ms": "Ubah hala Shorts ke Normal Player",
            "nb": "Omdiriger shorts til normal spiller",
            "pl": "Przekieruj Shorts do normalnego gracza",
            "pt": "Redirecionar Shorts para Jogador Normal",
            "ro": "Redirecționează scurtmetraje către Player Normal",
            "ru": "Перенаправить шорты на обычный проигрыватель",
            "sk": "Presmerujte Shorts na Normal Player",
            "es": "Redirigir cortos al jugador normal",
            "sv": "Omdirigera kortfilmer till normal spelare",
            "th": "เปลี่ยนเส้นทางกางเกงขาสั้นไปยังผู้เล่นปกติ",
            "tr": "Shorts'u Normal Oynatıcıya Yönlendir",
            "uk": "Переспрямувати Shorts на звичайний програвач",
            "vi": "Chuyển hướng video ngắn sang trình phát bình thường"
          },
        id: "untrap_redirect_shorts_to_player",
        defaultValue: false
    }
]

const shortsPageDesktopGroups_Details = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الوصف",
            "ca": "Amaga la descripció",
            "zh-CN": "隐藏说明",
            "zh-TW": "隱藏說明",
            "hr": "Sakrij opis",
            "cs": "Skrýt popis",
            "da": "Skjul beskrivelse",
            "nl": "Beschrijving verbergen",
            "en": "Hide Description",
            "fi": "Piilota kuvaus",
            "fr": "Masquer la description",
            "de": "Beschreibung ausblenden",
            "el": "Απόκρυψη περιγραφής",
            "he": "הסתר תיאור",
            "hi": "विवरण छिपाएँ",
            "hu": "Leírás elrejtése",
            "id": "Sembunyikan Deskripsi",
            "it": "Nascondi descrizione",
            "ja": "説明を隠す",
            "ko": "설명 숨기기",
            "ms": "Sembunyikan Perihalan",
            "nb": "Skjul beskrivelse",
            "pl": "Ukryj opis",
            "pt": "Ocultar descrição",
            "ro": "Ascunde descrierea",
            "ru": "Скрыть описание",
            "sk": "Skryť popis",
            "es": "Ocultar descripción",
            "sv": "Dölj beskrivning",
            "th": "ซ่อนคำอธิบาย",
            "tr": "Açıklamayı Gizle",
            "uk": "Приховати опис",
            "vi": "Ẩn mô tả"
          },
        id: "untrap_shorts_page_hide_description",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الصورة الرمزية للقناة",
            "ca": "Amaga l'avatar del canal",
            "zh-CN": "隐藏频道头像",
            "zh-TW": "隱藏頻道頭像",
            "hr": "Sakrij avatar kanala",
            "cs": "Skrýt avatara kanálu",
            "da": "Skjul kanalsavatar",
            "nl": "Kanaalavatar verbergen",
            "en": "Hide Channel Avatar",
            "fi": "Piilota kanavan avatar",
            "fr": "Masquer l'avatar de la chaîne",
            "de": "Kanal-Avatar ausblenden",
            "el": "Απόκρυψη Avatar καναλιού",
            "he": "הסתר את אוואטר הערוץ",
            "hi": "चैनल अवतार छिपाएँ",
            "hu": "Csatorna Avatar elrejtése",
            "id": "Sembunyikan Avatar Saluran",
            "it": "Nascondi l'avatar del canale",
            "ja": "チャンネルアバターを隠す",
            "ko": "채널 아바타 숨기기",
            "ms": "Sembunyikan Avatar Saluran",
            "nb": "Skjul kanalavatar",
            "pl": "Ukryj awatar kanału",
            "pt": "Ocultar avatar do canal",
            "ro": "Ascundeți avatarul canalului",
            "ru": "Скрыть аватар канала",
            "sk": "Skryť avatara kanála",
            "es": "Ocultar avatar del canal",
            "sv": "Dölj kanalavatar",
            "th": "ซ่อนอวตารของช่อง",
            "tr": "Kanal Avatarını Gizle",
            "uk": "Приховати аватар каналу",
            "vi": "Ẩn hình đại diện kênh"
          },
        id: "untrap_shorts_page_hide_channel_avatar",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء اسم مستخدم القناة",
            "ca": "Amaga el nom d'usuari del canal",
            "zh-CN": "隐藏频道用户名",
            "zh-TW": "隱藏頻道使用者名稱",
            "hr": "Sakrij korisničko ime kanala",
            "cs": "Skrýt uživatelské jméno kanálu",
            "da": "Skjul kanalbrugernavn",
            "nl": "Kanaalgebruikersnaam verbergen",
            "en": "Hide Channel Username",
            "fi": "Piilota kanavan käyttäjänimi",
            "fr": "Masquer le nom d'utilisateur de la chaîne",
            "de": "Kanal-Benutzernamen ausblenden",
            "el": "Απόκρυψη ονόματος χρήστη καναλιού",
            "he": "הסתר את שם המשתמש של הערוץ",
            "hi": "चैनल उपयोगकर्ता नाम छिपाएँ",
            "hu": "Csatorna felhasználónév elrejtése",
            "id": "Sembunyikan Nama Pengguna Saluran",
            "it": "Nascondi nome utente canale",
            "ja": "チャンネルのユーザー名を非表示にする",
            "ko": "채널 사용자 이름 숨기기",
            "ms": "Sembunyikan Nama Pengguna Saluran",
            "nb": "Skjul kanalbrukernavn",
            "pl": "Ukryj nazwę użytkownika kanału",
            "pt": "Ocultar nome de usuário do canal",
            "ro": "Ascunde numele utilizatorului canalului",
            "ru": "Скрыть имя пользователя канала",
            "sk": "Skryť používateľské meno kanála",
            "es": "Ocultar nombre de usuario del canal",
            "sv": "Dölj kanalanvändarnamn",
            "th": "ซ่อนชื่อผู้ใช้ช่อง",
            "tr": "Kanal Kullanıcı Adını Gizle",
            "uk": "Приховати ім'я користувача каналу",
            "vi": "Ẩn tên người dùng kênh"
          },
        id: "untrap_shorts_page_hide_channel_username",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء عدد الإعجابات",
            "ca": "Amaga el recompte de likes",
            "zh-CN": "隐藏点赞数",
            "zh-TW": "隱藏按讚數",
            "hr": "Sakrij lajkove",
            "cs": "Skrýt počet lajků",
            "da": "Skjul antal likes",
            "nl": "Aantal likes verbergen",
            "en": "Hide Likes Count",
            "fi": "Piilota tykkäysten määrä",
            "fr": "Masquer le nombre de likes",
            "de": "Anzahl der Likes ausblenden",
            "el": "Απόκρυψη αριθμού 'Μου αρέσει'",
            "he": "הסתר ספירת לייקים",
            "hi": "पसंद की गिनती छुपाएं",
            "hu": "Hide Likes Count",
            "id": "Sembunyikan Jumlah Suka",
            "it": "Nascondi conteggio Mi piace",
            "ja": "いいね数を非表示にする",
            "ko": "좋아요 수 숨기기",
            "ms": "Sembunyikan Kiraan Suka",
            "nb": "Skjul antall likes",
            "pl": "Ukryj liczbę polubień",
            "pt": "Ocultar contagem de curtidas",
            "ro": "Ascunde Like Count",
            "ru": "Скрыть количество лайков",
            "sk": "Skryť počet rád",
            "es": "Ocultar recuento de Me gusta",
            "sv": "Dölj antal gilla-markeringar",
            "th": "ซ่อนจำนวนไลค์",
            "tr": "Beğeni Sayısını Gizle",
            "uk": "Приховати кількість лайків",
            "vi": "Ẩn số lượt thích"
          },
        id: "untrap_shorts_page_hide_likes_count",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء عدد التعليقات",
            "ca": "Amaga el recompte de comentaris",
            "zh-CN": "隐藏评论数",
            "zh-TW": "隱藏評論數",
            "hr": "Sakrij broj komentara",
            "cs": "Skrýt počet komentářů",
            "da": "Skjul antal kommentarer",
            "nl": "Opmerkingen verbergen Aantal",
            "en": "Hide Comments Count",
            "fi": "Piilota kommenttien määrä",
            "fr": "Masquer le nombre de commentaires",
            "de": "Anzahl der Kommentare ausblenden",
            "el": "Απόκρυψη αριθμού σχολίων",
            "he": "הסתר ספירת תגובות",
            "hi": "टिप्पणियाँ संख्या छिपाएँ",
            "hu": "Hozzászólások elrejtése Szám",
            "id": "Sembunyikan Jumlah Komentar",
            "it": "Nascondi conteggio commenti",
            "ja": "コメント数を隠す",
            "ko": "댓글 수 숨기기",
            "ms": "Sembunyikan Kiraan Komen",
            "nb": "Skjul antall kommentarer",
            "pl": "Ukryj liczbę komentarzy",
            "pt": "Ocultar contagem de comentários",
            "ro": "Ascunde numărul de comentarii",
            "ru": "Скрыть количество комментариев",
            "sk": "Skryť počet komentárov",
            "es": "Ocultar recuento de comentarios",
            "sv": "Dölj antal kommentarer",
            "th": "ซ่อนจำนวนความคิดเห็น",
            "tr": "Yorum Sayısını Gizle",
            "uk": "Приховати кількість коментарів",
            "vi": "Ẩn số lượng bình luận"
          },
        id: "untrap_shorts_page_hide_comments_count",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء عدم الإعجاب ومشاركة التسميات",
            "ca": "Amaga les etiquetes de No m'agrada i comparteix-les",
            "zh-CN": "隐藏不喜欢和分享标签",
            "zh-TW": "隱藏不喜歡和分享標籤",
            "hr": "Sakrij oznake Ne sviđa mi se i Dijeli oznake",
            "cs": "Skrýt štítky Nelíbí se mi a sdílet",
            "da": "Skjul Dislike og del etiketter",
            "nl": "Verberg afkeer en deel labels",
            "en": "Hide Dislike and Share Labels",
            "fi": "Piilota En tykkää ja Jaa tunnisteet",
            "fr": "Masquer les étiquettes de Je n'aime pas et de partage",
            "de": "Blenden Sie die Labels „Abneigung“ und „Teilen“ aus",
            "el": "Απόκρυψη ετικετών 'Δεν μου αρέσει' και 'Κοινή χρήση'",
            "he": "הסתר דיסלייק ושתף תוויות",
            "hi": "नापसंद छिपाएँ और लेबल साझा करें",
            "hu": "Nem tetszik elrejtése és címkék megosztása",
            "id": "Sembunyikan Label Tidak Suka dan Bagikan",
            "it": "Nascondi etichette Non mi piace e Condividi",
            "ja": "嫌いなラベルを非表示にしてラベルを共有する",
            "ko": "싫어요 및 공유 라벨 숨기기",
            "ms": "Sembunyikan Label Tidak Suka dan Kongsi",
            "nb": "Skjul ikke-liker og del-etiketter",
            "pl": "Ukryj etykiety „nie lubię” i udostępnij",
            "pt": "Ocultar rótulos de antipatia e compartilhamento",
            "ro": "Ascundeți Nu-mi place și distribuiți etichetele",
            "ru": "Скрыть ярлыки «Не нравится» и «Поделиться»",
            "sk": "Skryť štítky Nepáči sa mi a zdieľať",
            "es": "Ocultar etiquetas No me gusta y Compartir",
            "sv": "Dölj ogilla- och dela-etiketter",
            "th": "ซ่อนป้ายกำกับไม่ชอบและแชร์",
            "tr": "Beğenmemeyi ve Paylaşma Etiketlerini Gizle",
            "uk": "Приховати мітки «Не подобається» та «Поділитися»",
            "vi": "Ẩn nhãn Không thích và Chia sẻ"
          },
        id: "untrap_shorts_page_hide_dislike_share_labels",
        defaultValue: false
    }
]

const shortsPageDesktopGroups_Buttons = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'تشغيل'",
            "ca": "Amaga el botó 'Reproduir'",
            "zh-CN": "隐藏“播放”按钮",
            "zh-TW": "隱藏“播放”按鈕",
            "hr": "Sakrij gumb 'Reproduciraj'",
            "cs": "Skrýt tlačítko „Přehrát“",
            "da": "Skjul 'Afspil'-knappen",
            "nl": "Knop 'Afspelen' verbergen",
            "en": "Hide 'Play' Button",
            "fi": "Piilota 'Play'-painike",
            "fr": "Masquer le bouton « Lecture »",
            "de": "Schaltfläche „Play“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Αναπαραγωγή'",
            "he": "הסתר את כפתור 'הפעל'",
            "hi": "'चलाएँ' बटन छिपाएँ",
            "hu": "A „Play” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Mainkan'",
            "it": "Nascondi il pulsante 'Riproduci'",
            "ja": "「再生」ボタンを隠す",
            "ko": "'재생' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Main'",
            "nb": "Skjul 'Spill'-knappen",
            "pl": "Ukryj przycisk „Odtwórz”",
            "pt": "Ocultar o botão 'Play'",
            "ro": "Ascundeți butonul „Play”",
            "ru": "Скрыть кнопку «Играть»",
            "sk": "Skryť tlačidlo „Prehrať“",
            "es": "Ocultar el botón 'Reproducir'",
            "sv": "Dölj 'Spela'-knappen",
            "th": "ซ่อนปุ่ม 'เล่น'",
            "tr": "'Oynat' Düğmesini Gizle",
            "uk": "Сховати кнопку «Відтворити»",
            "vi": "Ẩn nút 'Phát'"
          },
        id: "untrap_shorts_page_hide_play_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'كتم الصوت'",
            "ca": "Amaga el botó 'Silenciar'",
            "zh-CN": "隐藏“静音”按钮",
            "zh-TW": "隱藏“靜音”按鈕",
            "hr": "Sakrij gumb 'Isključi zvuk'",
            "cs": "Skrýt tlačítko „Ztlumit“",
            "da": "Skjul 'Mute'-knappen",
            "nl": "Knop 'Dempen' verbergen",
            "en": "Hide 'Mute' Button",
            "fi": "Piilota 'Mykistys'-painike",
            "fr": "Masquer le bouton « Muet »",
            "de": "Schaltfläche „Stumm“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Σίγαση'",
            "he": "הסתר את כפתור 'השתק'",
            "hi": "'म्यूट' बटन छिपाएँ",
            "hu": "A „Némítás” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Bungkam'",
            "it": "Nascondi il pulsante 'Muto'",
            "ja": "「ミュート」ボタンを非表示にする",
            "ko": "'음소거' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Redam'",
            "nb": "Skjul 'Mute'-knappen",
            "pl": "Ukryj przycisk „Wycisz”",
            "pt": "Ocultar botão 'Mudo'",
            "ro": "Ascundeți butonul „Mute”",
            "ru": "Скрыть кнопку «Отключить звук»",
            "sk": "Skryť tlačidlo „Stlmiť“",
            "es": "Ocultar el botón 'Silenciar'",
            "sv": "Dölj 'Mute'-knappen",
            "th": "ซ่อนปุ่ม 'ปิดเสียง'",
            "tr": "'Sessiz' Düğmesini Gizle",
            "uk": "Сховати кнопку «Вимкнути звук»",
            "vi": "Ẩn nút 'Tắt tiếng'"
          },
        id: "untrap_shorts_page_hide_mute_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'الاشتراك'",
            "ca": "Amaga el botó 'Subscriure's'",
            "zh-CN": "隐藏“订阅”按钮",
            "zh-TW": "隱藏“訂閱”按鈕",
            "hr": "Sakrij gumb 'Pretplati se'",
            "cs": "Skrýt tlačítko „Přihlásit se k odběru“",
            "da": "Skjul knappen 'Abonner'",
            "nl": "Knop 'Abonneren' verbergen",
            "en": "Hide 'Subscribe' Button",
            "fi": "Piilota 'Tilaa'-painike",
            "fr": "Masquer le bouton 'S'abonner'",
            "de": "Schaltfläche „Abonnieren“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Εγγραφή'",
            "he": "הסתר את כפתור 'הירשם כמנוי'",
            "hi": "'सदस्यता लें' बटन छुपाएं",
            "hu": "A „Feliratkozás” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Berlangganan'",
            "it": "Nascondi il pulsante 'Iscriviti'",
            "ja": "「購読」ボタンを非表示にする",
            "ko": "'구독' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Langgan'",
            "nb": "Skjul 'Abonner'-knappen",
            "pl": "Ukryj przycisk „Subskrybuj”",
            "pt": "Ocultar o botão 'Inscrever-se'",
            "ro": "Ascundeți butonul „Abonare”",
            "ru": "Скрыть кнопку «Подписаться»",
            "sk": "Skryť tlačidlo „Prihlásiť sa na odber“",
            "es": "Ocultar el botón 'Suscribir'",
            "sv": "Dölj 'Prenumerera'-knappen",
            "th": "ซ่อนปุ่ม 'สมัครสมาชิก'",
            "tr": "'Abone Ol' Düğmesini Gizle",
            "uk": "Сховати кнопку «Підписатися»",
            "vi": "Ẩn nút 'Đăng ký'"
          },
        id: "untrap_shorts_page_hide_subscribe_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'أعجبني'",
            "ca": "Amaga el botó 'M'agrada'",
            "zh-CN": "隐藏“喜欢”按钮",
            "zh-TW": "隱藏“喜歡”按鈕",
            "hr": "Sakrij gumb 'Sviđa mi se'",
            "cs": "Skrýt tlačítko „To se mi líbí“",
            "da": "Skjul 'Synes godt om'-knappen",
            "nl": "Verberg de 'Vind ik leuk'-knop",
            "en": "Hide 'Like' Button",
            "fi": "Piilota 'Tykkää'-painike",
            "fr": "Masquer le bouton 'J'aime'",
            "de": "„Gefällt mir“-Button ausblenden",
            "el": "Απόκρυψη κουμπιού 'Μου αρέσει'",
            "he": "הסתר את כפתור 'אהבתי'",
            "hi": "'पसंद करें' बटन छुपाएं",
            "hu": "A „Tetszik” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Suka'",
            "it": "Nascondi il pulsante 'Mi piace'",
            "ja": "「いいね！」ボタンを非表示にする",
            "ko": "'좋아요' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Suka'",
            "nb": "Skjul 'Liker'-knappen",
            "pl": "Ukryj przycisk „Lubię to”",
            "pt": "Ocultar botão 'Curtir'",
            "ro": "Ascundeți butonul „Like”",
            "ru": "Скрыть кнопку «Мне нравится»",
            "sk": "Skryť tlačidlo „Páči sa mi to“",
            "es": "Ocultar el botón 'Me gusta'",
            "sv": "Dölj 'Gilla'-knappen",
            "th": "ซ่อนปุ่ม 'ถูกใจ'",
            "tr": "'Beğen' Butonunu Gizle",
            "uk": "Приховати кнопку «Подобається»",
            "vi": "Ẩn nút 'Thích'"
          },
        id: "untrap_shorts_page_hide_like_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'لم يعجبني'",
            "ca": "Amaga el botó 'No m'agrada'",
            "zh-CN": "隐藏“不喜欢”按钮",
            "zh-TW": "隱藏“不喜歡”按鈕",
            "hr": "Sakrij gumb 'Ne sviđa mi se'",
            "cs": "Skrýt tlačítko „Nelíbí se mi“",
            "da": "Skjul 'Kan ikke lide'-knappen",
            "nl": "Knop 'Niet leuk' verbergen",
            "en": "Hide 'Dislike' Button",
            "fi": "Piilota 'En pidä'-painike",
            "fr": "Masquer le bouton 'Je n'aime pas'",
            "de": "Schaltfläche „Gefällt mir nicht“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Δεν μου αρέσει'",
            "he": "הסתר את כפתור 'לא אהבתי'",
            "hi": "'नापसंद करें' बटन छिपाएँ",
            "hu": "A „Nem tetszik” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Tidak Suka'",
            "it": "Nascondi il pulsante 'Non mi piace'",
            "ja": "「嫌い」ボタンを非表示にする",
            "ko": "'좋아요' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Tidak Suka'",
            "nb": "Skjul 'Liker ikke'-knappen",
            "pl": "Ukryj przycisk „Nie podoba mi się”",
            "pt": "Ocultar botão 'Não gostei'",
            "ro": "Ascundeți butonul „Nu-mi place”",
            "ru": "Скрыть кнопку «Не нравится»",
            "sk": "Skryť tlačidlo „Nepáči sa mi“",
            "es": "Ocultar el botón 'No me gusta'",
            "sv": "Dölj 'ogilla'-knappen",
            "th": "ซ่อนปุ่ม 'ไม่ชอบ'",
            "tr": "'Beğenmedim' Düğmesini Gizle",
            "uk": "Приховати кнопку «Не подобається»",
            "vi": "Ẩn nút 'Không thích'"
          },
        id: "untrap_shorts_page_hide_dislike_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'التعليقات'",
            "ca": "Amaga el botó 'Comentaris'",
            "zh-CN": "隐藏“评论”按钮",
            "zh-TW": "隱藏“評論”按鈕",
            "hr": "Sakrij gumb 'Komentari'",
            "cs": "Skrýt tlačítko 'Komentáře'",
            "da": "Skjul knappen 'Kommentarer'",
            "nl": "Knop 'Opmerkingen' verbergen",
            "en": "Hide 'Comments' Button",
            "fi": "Piilota 'Kommentit'-painike",
            "fr": "Masquer le bouton « Commentaires »",
            "de": "Schaltfläche „Kommentare“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Σχόλια'",
            "he": "הסתר את כפתור 'הערות'",
            "hi": "'टिप्पणियाँ' बटन छिपाएँ",
            "hu": "'Megjegyzések' gomb elrejtése",
            "id": "Sembunyikan Tombol 'Komentar'",
            "it": "Nascondi il pulsante 'Commenti'",
            "ja": "「コメント」ボタンを非表示にする",
            "ko": "'댓글' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Ulasan'",
            "nb": "Skjul 'Kommentarer'-knappen",
            "pl": "Ukryj przycisk „Komentarze”",
            "pt": "Ocultar botão 'Comentários'",
            "ro": "Ascundeți butonul „Comentarii”",
            "ru": "Скрыть кнопку «Комментарии»",
            "sk": "Skryť tlačidlo 'Komentáre'",
            "es": "Ocultar el botón 'Comentarios'",
            "sv": "Dölj 'Kommentarer'-knappen",
            "th": "ซ่อนปุ่ม 'ความคิดเห็น'",
            "tr": "'Yorumlar' Düğmesini Gizle",
            "uk": "Приховати кнопку «Коментарі»",
            "vi": "Ẩn nút 'Nhận xét'"
          },
        id: "untrap_shorts_page_hide_comments_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'المشاركة'",
            "ca": "Amaga el botó 'Comparteix'",
            "zh-CN": "隐藏“分享”按钮",
            "zh-TW": "隱藏「分享」按鈕",
            "hr": "Sakrij gumb 'Dijeli'",
            "cs": "Skrýt tlačítko 'Sdílet'",
            "da": "Skjul knappen 'Del'",
            "nl": "Knop 'Delen' verbergen",
            "en": "Hide 'Share' Button",
            "fi": "Piilota 'Jaa' -painike",
            "fr": "Masquer le bouton « Partager »",
            "de": "Schaltfläche „Teilen“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Κοινή χρήση'",
            "he": "הסתר את כפתור 'שתף'",
            "hi": "'शेयर' बटन छिपाएँ",
            "hu": "A „Megosztás” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Bagikan'",
            "it": "Nascondi il pulsante 'Condividi'",
            "ja": "「共有」ボタンを非表示にする",
            "ko": "'공유' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Kongsi'",
            "nb": "Skjul 'Del'-knappen",
            "pl": "Ukryj przycisk „Udostępnij”",
            "pt": "Ocultar o botão 'Compartilhar'",
            "ro": "Ascundeți butonul „Partajare”",
            "ru": "Скрыть кнопку «Поделиться»",
            "sk": "Skryť tlačidlo 'Zdieľať'",
            "es": "Ocultar el botón 'Compartir'",
            "sv": "Dölj 'Dela'-knappen",
            "th": "ซ่อนปุ่ม 'แชร์'",
            "tr": "'Paylaş' Düğmesini Gizle",
            "uk": "Сховати кнопку «Поділитися»",
            "vi": "Ẩn nút 'Chia sẻ'"
          },
        id: "untrap_shorts_page_hide_share_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'المزيد'",
            "ca": "Amaga el botó 'Més'",
            "zh-CN": "隐藏“更多”按钮",
            "zh-TW": "隱藏“更多”按鈕",
            "hr": "Sakrij gumb 'Više'",
            "cs": "Skrýt tlačítko 'Více'",
            "da": "Skjul knappen 'Mere'",
            "nl": "Knop 'Meer' verbergen",
            "en": "Hide 'More' Button",
            "fi": "Piilota 'Lisää'-painike",
            "fr": "Masquer le bouton « Plus »",
            "de": "Schaltfläche „Mehr“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Περισσότερα'",
            "he": "הסתר את כפתור 'עוד'",
            "hi": "'अधिक' बटन छिपाएँ",
            "hu": "A 'Továbbiak' gomb elrejtése",
            "id": "Sembunyikan Tombol 'Lainnya'",
            "it": "Nascondi il pulsante 'Altro'",
            "ja": "「もっと見る」ボタンを隠す",
            "ko": "'더보기' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Lagi'",
            "nb": "Skjul 'Mer'-knappen",
            "pl": "Ukryj przycisk „Więcej”",
            "pt": "Ocultar botão 'Mais'",
            "ro": "Ascundeți butonul „Mai multe”",
            "ru": "Скрыть кнопку «Еще»",
            "sk": "Skryť tlačidlo 'Viac'",
            "es": "Ocultar el botón 'Más'",
            "sv": "Dölj 'Mer'-knappen",
            "th": "ซ่อนปุ่ม 'เพิ่มเติม'",
            "tr": "'Daha Fazla' Düğmesini Gizle",
            "uk": "Сховати кнопку «Ще»",
            "vi": "Ẩn nút 'Thêm'"
          },
        id: "untrap_shorts_page_hide_more_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'الصوت'",
            "ca": "Amaga el botó 'So'",
            "zh-CN": "隐藏“声音”按钮",
            "zh-TW": "隱藏“聲音”按鈕",
            "hr": "Sakrij gumb 'Zvuk'",
            "cs": "Skrýt tlačítko 'Zvuk'",
            "da": "Skjul knappen 'Lyd'",
            "nl": "Knop 'Geluid' verbergen",
            "en": "Hide 'Sound' Button",
            "fi": "Piilota 'Ääni' -painike",
            "fr": "Masquer le bouton « Son »",
            "de": "Schaltfläche „Sound“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Ήχος'",
            "he": "הסתר את כפתור 'צליל'",
            "hi": "'ध्वनि' बटन छुपाएं",
            "hu": "A „Hang” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Suara'",
            "it": "Nascondi il pulsante 'Suono'",
            "ja": "「サウンド」ボタンを隠す",
            "ko": "'소리' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Bunyi'",
            "nb": "Skjul 'Lyd'-knappen",
            "pl": "Ukryj przycisk „Dźwięk”",
            "pt": "Ocultar botão 'Som'",
            "ro": "Ascundeți butonul „Sunet”",
            "ru": "Скрыть кнопку «Звук»",
            "sk": "Skryť tlačidlo „Zvuk“",
            "es": "Ocultar el botón 'Sonido'",
            "sv": "Dölj 'Ljud'-knappen",
            "th": "ซ่อนปุ่ม 'เสียง'",
            "tr": "'Ses' Düğmesini Gizle",
            "uk": "Приховати кнопку «Звук»",
            "vi": "Ẩn nút 'Âm thanh'"
          },
        id: "untrap_shorts_page_hide_sound_button",
        defaultValue: false
    }
]

// MARK: - Mobile Groups

const shortsPageMobileGroups_Redirects = [
    {
      type: "checkbox",
      name: {
          "ar": "إعادة توجيه الشورتات إلى المشغل العادي",
          "ca": "Redirigeix ​​els curts al reproductor normal",
          "zh-CN": "将 Shorts 重定向到普通播放器",
          "zh-TW": "將 Shorts 重新導向到普通播放器",
          "hr": "Preusmjeri Shorts na Normal Player",
          "cs": "Přesměrujte Shorts na Normální přehrávač",
          "da": "Omdiriger shorts til normal afspiller",
          "nl": "Shorts omleiden naar normale speler",
          "en": "Redirect Shorts to Normal Player",
          "fi": "Ohjaa Shortsit normaaliin soittimeen",
          "fr": "Rediriger les courts métrages vers le joueur normal",
          "de": "Shorts zum normalen Spieler umleiten",
          "el": "Ανακατεύθυνση Shorts σε Κανονικό πρόγραμμα αναπαραγωγής",
          "he": "הפנה מחדש את הקצרים לנגן רגיל",
          "hi": "शॉर्ट्स को सामान्य प्लेयर पर रीडायरेक्ट करें",
          "hu": "A Shorts-ok átirányítása normál lejátszóra",
          "id": "Alihkan Shorts ke Pemutar Normal",
          "it": "Reindirizza i cortometraggi al giocatore normale",
          "ja": "ショート動画を通常のプレーヤーにリダイレクトする",
          "ko": "Shorts를 일반 플레이어로 리디렉션",
          "ms": "Ubah hala Shorts ke Normal Player",
          "nb": "Omdiriger shorts til normal spiller",
          "pl": "Przekieruj Shorts do normalnego gracza",
          "pt": "Redirecionar Shorts para Jogador Normal",
          "ro": "Redirecționează scurtmetraje către Player Normal",
          "ru": "Перенаправить шорты на обычный проигрыватель",
          "sk": "Presmerujte Shorts na Normal Player",
          "es": "Redirigir cortos al jugador normal",
          "sv": "Omdirigera kortfilmer till normal spelare",
          "th": "เปลี่ยนเส้นทางกางเกงขาสั้นไปยังผู้เล่นปกติ",
          "tr": "Shorts'u Normal Oynatıcıya Yönlendir",
          "uk": "Переспрямувати Shorts на звичайний програвач",
          "vi": "Chuyển hướng video ngắn sang trình phát bình thường"
        },
      id: "untrap_redirect_shorts_to_player",
      defaultValue: false
    }
];

const shortsPageMobileGroups_Details = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الوصف",
            "ca": "Amaga la descripció",
            "zh-CN": "隐藏说明",
            "zh-TW": "隱藏說明",
            "hr": "Sakrij opis",
            "cs": "Skrýt popis",
            "da": "Skjul beskrivelse",
            "nl": "Beschrijving verbergen",
            "en": "Hide Description",
            "fi": "Piilota kuvaus",
            "fr": "Masquer la description",
            "de": "Beschreibung ausblenden",
            "el": "Απόκρυψη περιγραφής",
            "he": "הסתר תיאור",
            "hi": "विवरण छिपाएँ",
            "hu": "Leírás elrejtése",
            "id": "Sembunyikan Deskripsi",
            "it": "Nascondi descrizione",
            "ja": "説明を隠す",
            "ko": "설명 숨기기",
            "ms": "Sembunyikan Perihalan",
            "nb": "Skjul beskrivelse",
            "pl": "Ukryj opis",
            "pt": "Ocultar descrição",
            "ro": "Ascunde descrierea",
            "ru": "Скрыть описание",
            "sk": "Skryť popis",
            "es": "Ocultar descripción",
            "sv": "Dölj beskrivning",
            "th": "ซ่อนคำอธิบาย",
            "tr": "Açıklamayı Gizle",
            "uk": "Приховати опис",
            "vi": "Ẩn mô tả"
          },
        id: "untrap_shorts_page_hide_description",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الصورة الرمزية للقناة",
            "ca": "Amaga l'avatar del canal",
            "zh-CN": "隐藏频道头像",
            "zh-TW": "隱藏頻道頭像",
            "hr": "Sakrij avatar kanala",
            "cs": "Skrýt avatara kanálu",
            "da": "Skjul kanalsavatar",
            "nl": "Kanaalavatar verbergen",
            "en": "Hide Channel Avatar",
            "fi": "Piilota kanavan avatar",
            "fr": "Masquer l'avatar de la chaîne",
            "de": "Kanal-Avatar ausblenden",
            "el": "Απόκρυψη Avatar καναλιού",
            "he": "הסתר את אוואטר הערוץ",
            "hi": "चैनल अवतार छिपाएँ",
            "hu": "Csatorna Avatar elrejtése",
            "id": "Sembunyikan Avatar Saluran",
            "it": "Nascondi l'avatar del canale",
            "ja": "チャンネルアバターを隠す",
            "ko": "채널 아바타 숨기기",
            "ms": "Sembunyikan Avatar Saluran",
            "nb": "Skjul kanalavatar",
            "pl": "Ukryj awatar kanału",
            "pt": "Ocultar avatar do canal",
            "ro": "Ascundeți avatarul canalului",
            "ru": "Скрыть аватар канала",
            "sk": "Skryť avatara kanála",
            "es": "Ocultar avatar del canal",
            "sv": "Dölj kanalavatar",
            "th": "ซ่อนอวตารของช่อง",
            "tr": "Kanal Avatarını Gizle",
            "uk": "Приховати аватар каналу",
            "vi": "Ẩn hình đại diện kênh"
          },
        id: "untrap_shorts_page_hide_channel_avatar",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء اسم مستخدم القناة",
            "ca": "Amaga el nom d'usuari del canal",
            "zh-CN": "隐藏频道用户名",
            "zh-TW": "隱藏頻道使用者名稱",
            "hr": "Sakrij korisničko ime kanala",
            "cs": "Skrýt uživatelské jméno kanálu",
            "da": "Skjul kanalbrugernavn",
            "nl": "Kanaalgebruikersnaam verbergen",
            "en": "Hide Channel Username",
            "fi": "Piilota kanavan käyttäjänimi",
            "fr": "Masquer le nom d'utilisateur de la chaîne",
            "de": "Kanal-Benutzernamen ausblenden",
            "el": "Απόκρυψη ονόματος χρήστη καναλιού",
            "he": "הסתר את שם המשתמש של הערוץ",
            "hi": "चैनल उपयोगकर्ता नाम छिपाएँ",
            "hu": "Csatorna felhasználónév elrejtése",
            "id": "Sembunyikan Nama Pengguna Saluran",
            "it": "Nascondi nome utente canale",
            "ja": "チャンネルのユーザー名を非表示にする",
            "ko": "채널 사용자 이름 숨기기",
            "ms": "Sembunyikan Nama Pengguna Saluran",
            "nb": "Skjul kanalbrukernavn",
            "pl": "Ukryj nazwę użytkownika kanału",
            "pt": "Ocultar nome de usuário do canal",
            "ro": "Ascunde numele utilizatorului canalului",
            "ru": "Скрыть имя пользователя канала",
            "sk": "Skryť používateľské meno kanála",
            "es": "Ocultar nombre de usuario del canal",
            "sv": "Dölj kanalanvändarnamn",
            "th": "ซ่อนชื่อผู้ใช้ช่อง",
            "tr": "Kanal Kullanıcı Adını Gizle",
            "uk": "Приховати ім'я користувача каналу",
            "vi": "Ẩn tên người dùng kênh"
          },
        id: "untrap_shorts_page_hide_channel_username",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء عدد الإعجابات",
            "ca": "Amaga el recompte de likes",
            "zh-CN": "隐藏点赞数",
            "zh-TW": "隱藏按讚數",
            "hr": "Sakrij lajkove",
            "cs": "Skrýt počet lajků",
            "da": "Skjul antal likes",
            "nl": "Aantal likes verbergen",
            "en": "Hide Likes Count",
            "fi": "Piilota tykkäysten määrä",
            "fr": "Masquer le nombre de likes",
            "de": "Anzahl der Likes ausblenden",
            "el": "Απόκρυψη αριθμού 'Μου αρέσει'",
            "he": "הסתר ספירת לייקים",
            "hi": "पसंद की गिनती छुपाएं",
            "hu": "Hide Likes Count",
            "id": "Sembunyikan Jumlah Suka",
            "it": "Nascondi conteggio Mi piace",
            "ja": "いいね数を非表示にする",
            "ko": "좋아요 수 숨기기",
            "ms": "Sembunyikan Kiraan Suka",
            "nb": "Skjul antall likes",
            "pl": "Ukryj liczbę polubień",
            "pt": "Ocultar contagem de curtidas",
            "ro": "Ascunde Like Count",
            "ru": "Скрыть количество лайков",
            "sk": "Skryť počet rád",
            "es": "Ocultar recuento de Me gusta",
            "sv": "Dölj antal gilla-markeringar",
            "th": "ซ่อนจำนวนไลค์",
            "tr": "Beğeni Sayısını Gizle",
            "uk": "Приховати кількість лайків",
            "vi": "Ẩn số lượt thích"
          },
        id: "untrap_shorts_page_hide_likes_count",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء عدد التعليقات",
            "ca": "Amaga el recompte de comentaris",
            "zh-CN": "隐藏评论数",
            "zh-TW": "隱藏評論數",
            "hr": "Sakrij broj komentara",
            "cs": "Skrýt počet komentářů",
            "da": "Skjul antal kommentarer",
            "nl": "Opmerkingen verbergen Aantal",
            "en": "Hide Comments Count",
            "fi": "Piilota kommenttien määrä",
            "fr": "Masquer le nombre de commentaires",
            "de": "Anzahl der Kommentare ausblenden",
            "el": "Απόκρυψη αριθμού σχολίων",
            "he": "הסתר ספירת תגובות",
            "hi": "टिप्पणियाँ संख्या छिपाएँ",
            "hu": "Hozzászólások elrejtése Szám",
            "id": "Sembunyikan Jumlah Komentar",
            "it": "Nascondi conteggio commenti",
            "ja": "コメント数を隠す",
            "ko": "댓글 수 숨기기",
            "ms": "Sembunyikan Kiraan Komen",
            "nb": "Skjul antall kommentarer",
            "pl": "Ukryj liczbę komentarzy",
            "pt": "Ocultar contagem de comentários",
            "ro": "Ascunde numărul de comentarii",
            "ru": "Скрыть количество комментариев",
            "sk": "Skryť počet komentárov",
            "es": "Ocultar recuento de comentarios",
            "sv": "Dölj antal kommentarer",
            "th": "ซ่อนจำนวนความคิดเห็น",
            "tr": "Yorum Sayısını Gizle",
            "uk": "Приховати кількість коментарів",
            "vi": "Ẩn số lượng bình luận"
          },
        id: "untrap_shorts_page_hide_comments_count",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء عدم الإعجاب ومشاركة التسميات",
            "ca": "Amaga les etiquetes de No m'agrada i comparteix-les",
            "zh-CN": "隐藏不喜欢和分享标签",
            "zh-TW": "隱藏不喜歡和分享標籤",
            "hr": "Sakrij oznake Ne sviđa mi se i Dijeli oznake",
            "cs": "Skrýt štítky Nelíbí se mi a sdílet",
            "da": "Skjul Dislike og del etiketter",
            "nl": "Verberg afkeer en deel labels",
            "en": "Hide Dislike and Share Labels",
            "fi": "Piilota En tykkää ja Jaa tunnisteet",
            "fr": "Masquer les étiquettes de Je n'aime pas et de partage",
            "de": "Blenden Sie die Labels „Abneigung“ und „Teilen“ aus",
            "el": "Απόκρυψη ετικετών 'Δεν μου αρέσει' και 'Κοινή χρήση'",
            "he": "הסתר דיסלייק ושתף תוויות",
            "hi": "नापसंद छिपाएँ और लेबल साझा करें",
            "hu": "Nem tetszik elrejtése és címkék megosztása",
            "id": "Sembunyikan Label Tidak Suka dan Bagikan",
            "it": "Nascondi etichette Non mi piace e Condividi",
            "ja": "嫌いなラベルを非表示にしてラベルを共有する",
            "ko": "싫어요 및 공유 라벨 숨기기",
            "ms": "Sembunyikan Label Tidak Suka dan Kongsi",
            "nb": "Skjul ikke-liker og del-etiketter",
            "pl": "Ukryj etykiety „nie lubię” i udostępnij",
            "pt": "Ocultar rótulos de antipatia e compartilhamento",
            "ro": "Ascundeți Nu-mi place și distribuiți etichetele",
            "ru": "Скрыть ярлыки «Не нравится» и «Поделиться»",
            "sk": "Skryť štítky Nepáči sa mi a zdieľať",
            "es": "Ocultar etiquetas No me gusta y Compartir",
            "sv": "Dölj ogilla- och dela-etiketter",
            "th": "ซ่อนป้ายกำกับไม่ชอบและแชร์",
            "tr": "Beğenmemeyi ve Paylaşma Etiketlerini Gizle",
            "uk": "Приховати мітки «Не подобається» та «Поділитися»",
            "vi": "Ẩn nhãn Không thích và Chia sẻ"
          },
        id: "untrap_shorts_page_hide_dislike_share_labels",
        defaultValue: false
    }
];

const shortsPageMobileGroups_Buttons = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'الاشتراك'",
            "ca": "Amaga el botó 'Subscriure's'",
            "zh-CN": "隐藏“订阅”按钮",
            "zh-TW": "隱藏“訂閱”按鈕",
            "hr": "Sakrij gumb 'Pretplati se'",
            "cs": "Skrýt tlačítko „Přihlásit se k odběru“",
            "da": "Skjul knappen 'Abonner'",
            "nl": "Knop 'Abonneren' verbergen",
            "en": "Hide 'Subscribe' Button",
            "fi": "Piilota 'Tilaa'-painike",
            "fr": "Masquer le bouton 'S'abonner'",
            "de": "Schaltfläche „Abonnieren“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Εγγραφή'",
            "he": "הסתר את כפתור 'הירשם כמנוי'",
            "hi": "'सदस्यता लें' बटन छुपाएं",
            "hu": "A „Feliratkozás” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Berlangganan'",
            "it": "Nascondi il pulsante 'Iscriviti'",
            "ja": "「購読」ボタンを非表示にする",
            "ko": "'구독' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Langgan'",
            "nb": "Skjul 'Abonner'-knappen",
            "pl": "Ukryj przycisk „Subskrybuj”",
            "pt": "Ocultar o botão 'Inscrever-se'",
            "ro": "Ascundeți butonul „Abonare”",
            "ru": "Скрыть кнопку «Подписаться»",
            "sk": "Skryť tlačidlo „Prihlásiť sa na odber“",
            "es": "Ocultar el botón 'Suscribir'",
            "sv": "Dölj 'Prenumerera'-knappen",
            "th": "ซ่อนปุ่ม 'สมัครสมาชิก'",
            "tr": "'Abone Ol' Düğmesini Gizle",
            "uk": "Сховати кнопку «Підписатися»",
            "vi": "Ẩn nút 'Đăng ký'"
          },
        id: "untrap_shorts_page_hide_subscribe_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'أعجبني'",
            "ca": "Amaga el botó 'M'agrada'",
            "zh-CN": "隐藏“喜欢”按钮",
            "zh-TW": "隱藏“喜歡”按鈕",
            "hr": "Sakrij gumb 'Sviđa mi se'",
            "cs": "Skrýt tlačítko „To se mi líbí“",
            "da": "Skjul 'Synes godt om'-knappen",
            "nl": "Verberg de 'Vind ik leuk'-knop",
            "en": "Hide 'Like' Button",
            "fi": "Piilota 'Tykkää'-painike",
            "fr": "Masquer le bouton 'J'aime'",
            "de": "„Gefällt mir“-Button ausblenden",
            "el": "Απόκρυψη κουμπιού 'Μου αρέσει'",
            "he": "הסתר את כפתור 'אהבתי'",
            "hi": "'पसंद करें' बटन छुपाएं",
            "hu": "A „Tetszik” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Suka'",
            "it": "Nascondi il pulsante 'Mi piace'",
            "ja": "「いいね！」ボタンを非表示にする",
            "ko": "'좋아요' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Suka'",
            "nb": "Skjul 'Liker'-knappen",
            "pl": "Ukryj przycisk „Lubię to”",
            "pt": "Ocultar botão 'Curtir'",
            "ro": "Ascundeți butonul „Like”",
            "ru": "Скрыть кнопку «Мне нравится»",
            "sk": "Skryť tlačidlo „Páči sa mi to“",
            "es": "Ocultar el botón 'Me gusta'",
            "sv": "Dölj 'Gilla'-knappen",
            "th": "ซ่อนปุ่ม 'ถูกใจ'",
            "tr": "'Beğen' Butonunu Gizle",
            "uk": "Приховати кнопку «Подобається»",
            "vi": "Ẩn nút 'Thích'"
          },
        id: "untrap_shorts_page_hide_like_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'لم يعجبني'",
            "ca": "Amaga el botó 'No m'agrada'",
            "zh-CN": "隐藏“不喜欢”按钮",
            "zh-TW": "隱藏“不喜歡”按鈕",
            "hr": "Sakrij gumb 'Ne sviđa mi se'",
            "cs": "Skrýt tlačítko „Nelíbí se mi“",
            "da": "Skjul 'Kan ikke lide'-knappen",
            "nl": "Knop 'Niet leuk' verbergen",
            "en": "Hide 'Dislike' Button",
            "fi": "Piilota 'En pidä'-painike",
            "fr": "Masquer le bouton 'Je n'aime pas'",
            "de": "Schaltfläche „Gefällt mir nicht“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Δεν μου αρέσει'",
            "he": "הסתר את כפתור 'לא אהבתי'",
            "hi": "'नापसंद करें' बटन छिपाएँ",
            "hu": "A „Nem tetszik” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Tidak Suka'",
            "it": "Nascondi il pulsante 'Non mi piace'",
            "ja": "「嫌い」ボタンを非表示にする",
            "ko": "'좋아요' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Tidak Suka'",
            "nb": "Skjul 'Liker ikke'-knappen",
            "pl": "Ukryj przycisk „Nie podoba mi się”",
            "pt": "Ocultar botão 'Não gostei'",
            "ro": "Ascundeți butonul „Nu-mi place”",
            "ru": "Скрыть кнопку «Не нравится»",
            "sk": "Skryť tlačidlo „Nepáči sa mi“",
            "es": "Ocultar el botón 'No me gusta'",
            "sv": "Dölj 'ogilla'-knappen",
            "th": "ซ่อนปุ่ม 'ไม่ชอบ'",
            "tr": "'Beğenmedim' Düğmesini Gizle",
            "uk": "Приховати кнопку «Не подобається»",
            "vi": "Ẩn nút 'Không thích'"
          },
        id: "untrap_shorts_page_hide_dislike_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'التعليقات'",
            "ca": "Amaga el botó 'Comentaris'",
            "zh-CN": "隐藏“评论”按钮",
            "zh-TW": "隱藏“評論”按鈕",
            "hr": "Sakrij gumb 'Komentari'",
            "cs": "Skrýt tlačítko 'Komentáře'",
            "da": "Skjul knappen 'Kommentarer'",
            "nl": "Knop 'Opmerkingen' verbergen",
            "en": "Hide 'Comments' Button",
            "fi": "Piilota 'Kommentit'-painike",
            "fr": "Masquer le bouton « Commentaires »",
            "de": "Schaltfläche „Kommentare“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Σχόλια'",
            "he": "הסתר את כפתור 'הערות'",
            "hi": "'टिप्पणियाँ' बटन छिपाएँ",
            "hu": "'Megjegyzések' gomb elrejtése",
            "id": "Sembunyikan Tombol 'Komentar'",
            "it": "Nascondi il pulsante 'Commenti'",
            "ja": "「コメント」ボタンを非表示にする",
            "ko": "'댓글' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Ulasan'",
            "nb": "Skjul 'Kommentarer'-knappen",
            "pl": "Ukryj przycisk „Komentarze”",
            "pt": "Ocultar botão 'Comentários'",
            "ro": "Ascundeți butonul „Comentarii”",
            "ru": "Скрыть кнопку «Комментарии»",
            "sk": "Skryť tlačidlo 'Komentáre'",
            "es": "Ocultar el botón 'Comentarios'",
            "sv": "Dölj 'Kommentarer'-knappen",
            "th": "ซ่อนปุ่ม 'ความคิดเห็น'",
            "tr": "'Yorumlar' Düğmesini Gizle",
            "uk": "Приховати кнопку «Коментарі»",
            "vi": "Ẩn nút 'Nhận xét'"
          },
        id: "untrap_shorts_page_hide_comments_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'المشاركة'",
            "ca": "Amaga el botó 'Comparteix'",
            "zh-CN": "隐藏“分享”按钮",
            "zh-TW": "隱藏「分享」按鈕",
            "hr": "Sakrij gumb 'Dijeli'",
            "cs": "Skrýt tlačítko 'Sdílet'",
            "da": "Skjul knappen 'Del'",
            "nl": "Knop 'Delen' verbergen",
            "en": "Hide 'Share' Button",
            "fi": "Piilota 'Jaa' -painike",
            "fr": "Masquer le bouton « Partager »",
            "de": "Schaltfläche „Teilen“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Κοινή χρήση'",
            "he": "הסתר את כפתור 'שתף'",
            "hi": "'शेयर' बटन छिपाएँ",
            "hu": "A „Megosztás” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Bagikan'",
            "it": "Nascondi il pulsante 'Condividi'",
            "ja": "「共有」ボタンを非表示にする",
            "ko": "'공유' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Kongsi'",
            "nb": "Skjul 'Del'-knappen",
            "pl": "Ukryj przycisk „Udostępnij”",
            "pt": "Ocultar o botão 'Compartilhar'",
            "ro": "Ascundeți butonul „Partajare”",
            "ru": "Скрыть кнопку «Поделиться»",
            "sk": "Skryť tlačidlo 'Zdieľať'",
            "es": "Ocultar el botón 'Compartir'",
            "sv": "Dölj 'Dela'-knappen",
            "th": "ซ่อนปุ่ม 'แชร์'",
            "tr": "'Paylaş' Düğmesini Gizle",
            "uk": "Сховати кнопку «Поділитися»",
            "vi": "Ẩn nút 'Chia sẻ'"
          },
        id: "untrap_shorts_page_hide_share_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'المزيد'",
            "ca": "Amaga el botó 'Més'",
            "zh-CN": "隐藏“更多”按钮",
            "zh-TW": "隱藏“更多”按鈕",
            "hr": "Sakrij gumb 'Više'",
            "cs": "Skrýt tlačítko 'Více'",
            "da": "Skjul knappen 'Mere'",
            "nl": "Knop 'Meer' verbergen",
            "en": "Hide 'More' Button",
            "fi": "Piilota 'Lisää'-painike",
            "fr": "Masquer le bouton « Plus »",
            "de": "Schaltfläche „Mehr“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Περισσότερα'",
            "he": "הסתר את כפתור 'עוד'",
            "hi": "'अधिक' बटन छिपाएँ",
            "hu": "A 'Továbbiak' gomb elrejtése",
            "id": "Sembunyikan Tombol 'Lainnya'",
            "it": "Nascondi il pulsante 'Altro'",
            "ja": "「もっと見る」ボタンを隠す",
            "ko": "'더보기' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Lagi'",
            "nb": "Skjul 'Mer'-knappen",
            "pl": "Ukryj przycisk „Więcej”",
            "pt": "Ocultar botão 'Mais'",
            "ro": "Ascundeți butonul „Mai multe”",
            "ru": "Скрыть кнопку «Еще»",
            "sk": "Skryť tlačidlo 'Viac'",
            "es": "Ocultar el botón 'Más'",
            "sv": "Dölj 'Mer'-knappen",
            "th": "ซ่อนปุ่ม 'เพิ่มเติม'",
            "tr": "'Daha Fazla' Düğmesini Gizle",
            "uk": "Сховати кнопку «Ще»",
            "vi": "Ẩn nút 'Thêm'"
          },
        id: "untrap_shorts_page_hide_more_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'الصوت'",
            "ca": "Amaga el botó 'So'",
            "zh-CN": "隐藏“声音”按钮",
            "zh-TW": "隱藏“聲音”按鈕",
            "hr": "Sakrij gumb 'Zvuk'",
            "cs": "Skrýt tlačítko 'Zvuk'",
            "da": "Skjul knappen 'Lyd'",
            "nl": "Knop 'Geluid' verbergen",
            "en": "Hide 'Sound' Button",
            "fi": "Piilota 'Ääni' -painike",
            "fr": "Masquer le bouton « Son »",
            "de": "Schaltfläche „Sound“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Ήχος'",
            "he": "הסתר את כפתור 'צליל'",
            "hi": "'ध्वनि' बटन छुपाएं",
            "hu": "A „Hang” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Suara'",
            "it": "Nascondi il pulsante 'Suono'",
            "ja": "「サウンド」ボタンを隠す",
            "ko": "'소리' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Bunyi'",
            "nb": "Skjul 'Lyd'-knappen",
            "pl": "Ukryj przycisk „Dźwięk”",
            "pt": "Ocultar botão 'Som'",
            "ro": "Ascundeți butonul „Sunet”",
            "ru": "Скрыть кнопку «Звук»",
            "sk": "Skryť tlačidlo „Zvuk“",
            "es": "Ocultar el botón 'Sonido'",
            "sv": "Dölj 'Ljud'-knappen",
            "th": "ซ่อนปุ่ม 'เสียง'",
            "tr": "'Ses' Düğmesini Gizle",
            "uk": "Приховати кнопку «Звук»",
            "vi": "Ẩn nút 'Âm thanh'"
          },
        id: "untrap_shorts_page_hide_sound_button",
        defaultValue: false
    }
];

// MARK: - Builder

// Desktop

const shortsPageDesktopGroups = [
    {
        groupName: {
            "ar": "إعادة توجيه",
            "ca": "Redirigeix",
            "zh-CN": "重定向",
            "zh-TW": "重定向",
            "hr": "Preusmjeri",
            "cs": "Přesměrování",
            "da": "Omdirigere",
            "nl": "Omleiden",
            "en": "Redirect",
            "fi": "Uudelleenohjaus",
            "fr": "Réorienter",
            "de": "Umleiten",
            "el": "Διευθύνω πάλιν",
            "he": "הפניה מחדש",
            "hi": "पुनर्निर्देशन",
            "hu": "Átirányítás",
            "id": "Pengalihan",
            "it": "Reindirizzare",
            "ja": "リダイレクト",
            "ko": "리디렉션",
            "ms": "Ubah hala",
            "no": "Omdirigere",
            "pl": "Przeadresować",
            "pt": "Redirecionar",
            "ro": "Redirecţiona",
            "ru": "Перенаправление",
            "sk": "Presmerovať",
            "es": "Redirigir",
            "sv": "Dirigera om",
            "th": "เปลี่ยนเส้นทาง",
            "tr": "Yönlendir",
            "uk": "Перенаправлення",
            "vi": "Chuyển hướng"
          },
        groupId: "redirects",
        parentCategoryId: "shortsPage",
        options: shortsPageDesktopGroups_Redirects
    },
    {
        groupName: {
            "ar": "آحرون",
            "ca": "Altres",
            "zh-CN": "其他的",
            "zh-TW": "其他的",
            "hr": "Drugi",
            "cs": "Ostatní",
            "da": "Andre",
            "nl": "Anderen",
            "en": "Others",
            "fi": "muut",
            "fr": "Autres",
            "de": "Andere",
            "el": "Οι υπολοιποι",
            "he": "אחרים",
            "hi": "अन्य",
            "hu": "Mások",
            "id": "Yang lain",
            "it": "Altri",
            "ja": "その他",
            "ko": "기타",
            "ms": "Lain-lain",
            "nb": "Andre",
            "pl": "Inni",
            "pt": "Outros",
            "ro": "Alții",
            "ru": "Другие",
            "sk": "Iní",
            "es": "Otros",
            "sv": "Andra",
            "th": "คนอื่น",
            "tr": "Diğerleri",
            "uk": "Інші",
            "vi": "Người khác"
          },
        groupId: "other",
        parentCategoryId: "shortsPage",
        options: shortsPageDesktopGroups_Other
    },
    {
        groupName: {
            "ar": "تفاصيل",
            "ca": "Detalls",
            "zh-CN": "细节",
            "zh-TW": "細節",
            "hr": "Pojedinosti",
            "cs": "Podrobnosti",
            "da": "Detaljer",
            "nl": "Details",
            "en": "Details",
            "fi": "Yksityiskohdat",
            "fr": "Détails",
            "de": "Einzelheiten",
            "el": "Λεπτομέριες",
            "he": "פרטים",
            "hi": "विवरण",
            "hu": "Részletek",
            "id": "Detail",
            "it": "Dettagli",
            "ja": "詳細",
            "ko": "세부",
            "ms": "Butiran",
            "nb": "Detaljer",
            "pl": "Detale",
            "pt": "Detalhes",
            "ro": "Detalii",
            "ru": "Подробности",
            "sk": "Podrobnosti",
            "es": "Detalles",
            "sv": "Detaljer",
            "th": "รายละเอียด",
            "tr": "Detaylar",
            "uk": "Подробиці",
            "vi": "Chi tiết"
          },
        groupId: "details",
        parentCategoryId: "shortsPage",
        options: shortsPageDesktopGroups_Details
    },
    {
        groupName: {
            "ar": "أزرار",
            "ca": "Botons",
            "zh-CN": "纽扣",
            "zh-TW": "羈扣",
            "hr": "Gumbi",
            "cs": "Tlačítka",
            "da": "Knapper",
            "nl": "Toetsen",
            "en": "Buttons",
            "fi": "Painikkeet",
            "fr": "Boutons",
            "de": "Tasten",
            "el": "Κουμπιά",
            "he": "כפתורים",
            "hi": "बटन",
            "hu": "Gombok",
            "id": "Tombol",
            "it": "Pulsanti",
            "ja": "ボタン",
            "ko": "버튼",
            "ms": "Butang",
            "nb": "Knapper",
            "pl": "Guziki",
            "pt": "Botões",
            "ro": "Butoane",
            "ru": "Кнопки",
            "sk": "Tlačidlá",
            "es": "Botones",
            "sv": "Knappar",
            "th": "ปุ่ม",
            "tr": "Düğmeler",
            "uk": "Кнопки",
            "vi": "Nút"
          },
        groupId: "buttons",
        parentCategoryId: "shortsPage",
        options: shortsPageDesktopGroups_Buttons
    }
];

// Mobile

const shortsPageMobileGroups = [
    {
        groupName: {
            "ar": "إعادة توجيه",
            "ca": "Redirigeix",
            "zh-CN": "重定向",
            "zh-TW": "重定向",
            "hr": "Preusmjeri",
            "cs": "Přesměrování",
            "da": "Omdirigere",
            "nl": "Omleiden",
            "en": "Redirect",
            "fi": "Uudelleenohjaus",
            "fr": "Réorienter",
            "de": "Umleiten",
            "el": "Διευθύνω πάλιν",
            "he": "הפניה מחדש",
            "hi": "पुनर्निर्देशन",
            "hu": "Átirányítás",
            "id": "Pengalihan",
            "it": "Reindirizzare",
            "ja": "リダイレクト",
            "ko": "리디렉션",
            "ms": "Ubah hala",
            "no": "Omdirigere",
            "pl": "Przeadresować",
            "pt": "Redirecionar",
            "ro": "Redirecţiona",
            "ru": "Перенаправление",
            "sk": "Presmerovať",
            "es": "Redirigir",
            "sv": "Dirigera om",
            "th": "เปลี่ยนเส้นทาง",
            "tr": "Yönlendir",
            "uk": "Перенаправлення",
            "vi": "Chuyển hướng"
          },
        groupId: "redirects",
        parentCategoryId: "shortsPage",
        options: shortsPageMobileGroups_Redirects
    },
    {
        groupName: {
            "ar": "تفاصيل",
            "ca": "Detalls",
            "zh-CN": "细节",
            "zh-TW": "細節",
            "hr": "pojedinosti",
            "cs": "Podrobnosti",
            "da": "Detaljer",
            "nl": "Details",
            "en": "Details",
            "fi": "Yksityiskohdat",
            "fr": "Détails",
            "de": "Einzelheiten",
            "el": "Λεπτομέριες",
            "he": "פרטים",
            "hi": "विवरण",
            "hu": "Részletek",
            "id": "Detail",
            "it": "Dettagli",
            "ja": "詳細",
            "ko": "세부",
            "ms": "Butiran",
            "nb": "Detaljer",
            "pl": "Detale",
            "pt": "Detalhes",
            "ro": "Detalii",
            "ru": "Подробности",
            "sk": "Podrobnosti",
            "es": "Detalles",
            "sv": "Detaljer",
            "th": "รายละเอียด",
            "tr": "Detaylar",
            "uk": "Подробиці",
            "vi": "Chi tiết"
          },
        groupId: "details",
        parentCategoryId: "shortsPage",
        options: shortsPageMobileGroups_Details
    },
    {
        groupName: {
            "ar": "أزرار",
            "ca": "Botons",
            "zh-CN": "纽扣",
            "zh-TW": "羈扣",
            "hr": "Gumbi",
            "cs": "Tlačítka",
            "da": "Knapper",
            "nl": "Toetsen",
            "en": "Buttons",
            "fi": "Painikkeet",
            "fr": "Boutons",
            "de": "Tasten",
            "el": "Κουμπιά",
            "he": "כפתורים",
            "hi": "बटन",
            "hu": "Gombok",
            "id": "Tombol",
            "it": "Pulsanti",
            "ja": "ボタン",
            "ko": "버튼",
            "ms": "Butang",
            "nb": "Knapper",
            "pl": "Guziki",
            "pt": "Botões",
            "ro": "Butoane",
            "ru": "Кнопки",
            "sk": "Tlačidlá",
            "es": "Botones",
            "sv": "Knappar",
            "th": "ปุ่ม",
            "tr": "Düğmeler",
            "uk": "Кнопки",
            "vi": "Nút"
          },
        groupId: "buttons",
        parentCategoryId: "shortsPage",
        options: shortsPageMobileGroups_Buttons
    }
]
