// MARK: - Desktop Groups

const subscriptionsPageDesktopGroups_Other = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء مقاطع الفيديو التي تمت مشاهدتها",
            "ca": "Amaga els vídeos vists",
            "zh-CN": "隐藏观看过的视频",
            "zh-TW": "隱藏觀看過的視頻",
            "hr": "Sakrij gledane videozapise",
            "cs": "Skrýt sledovaná videa",
            "da": "Skjul sete videoer",
            "nl": "Verberg bekeken video's",
            "en": "Hide Watched Videos",
            "fi": "Piilota katsotut videot",
            "fr": "Masquer les vidéos regardées",
            "de": "Angesehene Videos ausblenden",
            "el": "Απόκρυψη βίντεο που παρακολουθήσατε",
            "he": "הסתר סרטונים שנצפו",
            "hi": "देखे गए वीडियो छुपाएं",
            "hu": "Megtekintett videók elrejtése",
            "id": "Sembunyikan Video yang Ditonton",
            "it": "Nascondi i video guardati",
            "ja": "視聴したビデオを非表示にする",
            "ko": "시청한 동영상 숨기기",
            "ms": "Sembunyikan Video yang Ditonton",
            "nb": "Skjul sett videoer",
            "pl": "Ukryj oglądane filmy",
            "pt": "Ocultar vídeos assistidos",
            "ro": "Ascunde videoclipurile vizionate",
            "ru": "Скрыть просмотренные видео",
            "sk": "Skryť sledované videá",
            "es": "Ocultar vídeos vistos",
            "sv": "Dölj sedda videor",
            "th": "ซ่อนวิดีโอที่ดู",
            "tr": "İzlenen Videoları Gizle",
            "uk": "Приховати переглянуті відео",
            "vi": "Ẩn video đã xem"
          },
        id: "untrap_subscriptions_hide_watched_videos",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء مقاطع الفيديو المباشرة والعرض الأول",
            "ca": "Amaga vídeos en directe i estrena",
            "zh-CN": "隐藏直播和首映视频",
            "zh-TW": "隱藏直播和首映視頻",
            "hr": "Sakrij videozapise uživo i premijere",
            "cs": "Skrýt živá a premiérová videa",
            "da": "Skjul live- og premierevideoer",
            "nl": "Live- en premièrevideo's verbergen",
            "en": "Hide Live and Premiere Videos",
            "fi": "Piilota live- ja ensiesitysvideot",
            "fr": "Masquer les vidéos en direct et en première",
            "de": "Live- und Premiere-Videos ausblenden",
            "el": "Απόκρυψη ζωντανών βίντεο και βίντεο πρεμιέρας",
            "he": "הסתר סרטונים בשידור חי ובכורה",
            "hi": "लाइव और प्रीमियर वीडियो छुपाएं",
            "hu": "Élő és premier videók elrejtése",
            "id": "Sembunyikan Video Langsung dan Tayang Perdana",
            "it": "Nascondi video dal vivo e in anteprima",
            "ja": "ライブビデオとプレミアビデオを非表示にする",
            "ko": "라이브 및 프리미어 비디오 숨기기",
            "ms": "Sembunyikan Video Langsung dan Tayangan Perdana",
            "nb": "Skjul live- og premierevideoer",
            "pl": "Ukryj filmy na żywo i premiery",
            "pt": "Ocultar vídeos ao vivo e de estreia",
            "ro": "Ascundeți videoclipurile live și în premieră",
            "ru": "Скрыть видео прямых трансляций и премьер",
            "sk": "Skryť živé a premiérové ​​videá",
            "es": "Ocultar vídeos en directo y de estreno",
            "sv": "Dölj live- och premiärvideor",
            "th": "ซ่อนวิดีโอสดและวิดีโอรอบปฐมทัศน์",
            "tr": "Canlı ve İlk Gösterim Videolarını Gizle",
            "uk": "Приховати прямі трансляції та прем'єрні відео",
            "vi": "Ẩn video trực tiếp và công chiếu"
          },
        id: "untrap_subscriptions_hide_live_videos",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء مقاطع الفيديو القادمة",
            "ca": "Amaga els propers vídeos",
            "zh-CN": "隐藏即将播放的视频",
            "zh-TW": "隱藏即將播放的視頻",
            "hr": "Sakrij nadolazeće videozapise",
            "cs": "Skrýt nadcházející videa",
            "da": "Skjul kommende videoer",
            "nl": "Aankomende video's verbergen",
            "en": "Hide Upcoming Videos",
            "fi": "Piilota tulevat videot",
            "fr": "Masquer les vidéos à venir",
            "de": "Kommende Videos ausblenden",
            "el": "Απόκρυψη επερχόμενων βίντεο",
            "he": "הסתר סרטונים קרובים",
            "hi": "आगामी वीडियो छिपाएँ",
            "hu": "Közelgő videók elrejtése",
            "id": "Sembunyikan Video Mendatang",
            "it": "Nascondi i prossimi video",
            "ja": "今後のビデオを隠す",
            "ko": "다가오는 비디오 숨기기",
            "ms": "Sembunyikan Video Akan Datang",
            "nb": "Skjul kommende videoer",
            "pl": "Ukryj nadchodzące filmy",
            "pt": "Ocultar os próximos vídeos",
            "ro": "Ascunde videoclipurile viitoare",
            "ru": "Скрыть предстоящие видео",
            "sk": "Skryť nadchádzajúce videá",
            "es": "Ocultar próximos vídeos",
            "sv": "Dölj kommande videor",
            "th": "ซ่อนวิดีโอที่กำลังจะมีขึ้น",
            "tr": "Gelecek Videoları Gizle",
            "uk": "Приховати майбутні відео",
            "vi": "Ẩn video sắp tới"
          },
        id: "untrap_subscriptions_hide_upcoming_videos",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء السراويل القصيرة",
            "ca": "Amaga pantalons curts",
            "zh-CN": "隐藏短裤",
            "zh-TW": "隱藏短褲",
            "hr": "Sakrij kratke hlače",
            "cs": "Skrýt šortky",
            "da": "Skjul shorts",
            "nl": "Shorts verbergen",
            "en": "Hide Shorts",
            "fi": "Piilota shortsit",
            "fr": "Masquer les courts métrages",
            "de": "Shorts verstecken",
            "el": "Απόκρυψη σορτς",
            "he": "הסתר מכנסיים קצרים",
            "hi": "शॉर्ट्स छुपाएं",
            "hu": "Rövidnadrágok elrejtése",
            "id": "Sembunyikan Celana Pendek",
            "it": "Nascondi pantaloncini",
            "ja": "ショートパンツを隠す",
            "ko": "쇼츠 숨기기",
            "ms": "Sembunyikan Seluar Pendek",
            "nb": "Skjul shorts",
            "pl": "Ukryj szorty",
            "pt": "Ocultar Shorts",
            "ro": "Ascunde pantaloni scurți",
            "ru": "Скрыть шорты",
            "sk": "Skryť šortky",
            "es": "Ocultar pantalones cortos",
            "sv": "Göm shorts",
            "th": "ซ่อนวิดีโอสั้น",
            "tr": "Kısaları Gizle",
            "uk": "Сховати шорти",
            "vi": "Ẩn video ngắn"
          },
        id: "untrap_subscriptions_hide_shorts",
        defaultValue: false
    }
]

// MARK: - Mobile Groups

const subscriptionsPageMobileGroups_SubscriptionsList = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قائمة الاشتراكات",
            "ca": "Amaga la llista de subscripcions",
            "zh-CN": "隐藏订阅列表",
            "zh-TW": "隱藏訂閱列表",
            "hr": "Sakrij popis pretplata",
            "cs": "Skrýt seznam odběrů",
            "da": "Skjul abonnementsliste",
            "nl": "Lijst met abonnementen verbergen",
            "en": "Hide Subscriptions List",
            "fi": "Piilota tilausluettelo",
            "fr": "Masquer la liste des abonnements",
            "de": "Abonnementliste ausblenden",
            "el": "Απόκρυψη λίστας συνδρομών",
            "he": "הסתר רשימת מנויים",
            "hi": "सदस्यता सूची छिपाएँ",
            "hu": "Feliratkozási lista elrejtése",
            "id": "Sembunyikan Daftar Langganan",
            "it": "Nascondi elenco abbonamenti",
            "ja": "サブスクリプションリストを非表示にする",
            "ko": "구독 목록 숨기기",
            "ms": "Sembunyikan Senarai Langganan",
            "nb": "Skjul abonnementslisten",
            "pl": "Ukryj listę subskrypcji",
            "pt": "Ocultar lista de assinaturas",
            "ro": "Ascunde lista de abonamente",
            "ru": "Скрыть список подписок",
            "sk": "Skryť zoznam odberov",
            "es": "Ocultar lista de suscripciones",
            "sv": "Dölj prenumerationslistan",
            "th": "ซ่อนรายการสมัครสมาชิก",
            "tr": "Abonelik Listesini Gizle",
            "uk": "Приховати список підписок",
            "vi": "Ẩn danh sách đăng ký"
          },
        id: "untrap_subscriptions_hide_channels_list",
        defaultValue: false,
        childOffOptions: [
            {
                type: "checkbox",
                name: {
                    "ar": "قائمة الاشتراكات ذات التدرج الرمادي",
                    "ca": "Llista de subscripcions en escala de grisos",
                    "zh-CN": "灰度订阅列表",
                    "zh-TW": "灰階訂閱列表",
                    "hr": "Popis pretplata u sivim tonovima",
                    "cs": "Seznam předplatných ve stupních šedi",
                    "da": "Liste over abonnementer i gråtoner",
                    "nl": "Lijst met grijswaardenabonnementen",
                    "en": "Grayscale Subscriptions List",
                    "fi": "Harmaasävytilausluettelo",
                    "fr": "Liste des abonnements en niveaux de gris",
                    "de": "Graustufen-Abonnementliste",
                    "el": "Λίστα συνδρομών σε κλίμακα του γκρι",
                    "he": "רשימת מנויים בגווני אפור",
                    "hi": "ग्रेस्केल सदस्यता सूची",
                    "hu": "Szürkeárnyalatos előfizetések listája",
                    "id": "Daftar Langganan Grayscale",
                    "it": "Elenco abbonamenti in scala di grigi",
                    "ja": "グレースケール サブスクリプション リスト",
                    "ko": "그레이스케일 구독 목록",
                    "ms": "Senarai Langganan Skala Kelabu",
                    "nb": "Abonnementsliste i gråtoner",
                    "pl": "Lista subskrypcji w skali szarości",
                    "pt": "Lista de assinaturas em tons de cinza",
                    "ro": "Lista de abonamente în tonuri de gri",
                    "ru": "Список подписок на оттенки серого",
                    "sk": "Zoznam odberov v odtieňoch sivej",
                    "es": "Lista de suscripciones en escala de grises",
                    "sv": "Prenumerationslista i gråskala",
                    "th": "รายการสมัครสมาชิกระดับสีเทา",
                    "tr": "Gri Tonlamalı Abonelikler Listesi",
                    "uk": "Список підписок у відтінках сірого",
                    "vi": "Danh sách đăng ký thang độ xám"
                  },
                id: "untrap_subscriptions_grayscale_channels_list",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء نقاط إشعارات الاشتراكات",
                    "ca": "Amaga els punts de notificacions de subscripcions",
                    "zh-CN": "隐藏订阅通知点",
                    "zh-TW": "隱藏訂閱通知點",
                    "hr": "Sakrij točke obavijesti o pretplatama",
                    "cs": "Skrýt tečky upozornění na odběry",
                    "da": "Skjul abonnementsmeddelelser prikker",
                    "nl": "Verberg abonnementen Meldingen Punten",
                    "en": "Hide Subscriptions Notifications Dots",
                    "fi": "Piilota tilausten ilmoituspisteet",
                    "fr": "Masquer les points de notification des abonnements",
                    "de": "Abonnementbenachrichtigungspunkte ausblenden",
                    "el": "Απόκρυψη κουκκίδων ειδοποιήσεων συνδρομών",
                    "he": "הסתר נקודות התראות על מינויים",
                    "hi": "सदस्यता अधिसूचना बिंदु छिपाएँ",
                    "hu": "Az előfizetések értesítési pontjainak elrejtése",
                    "id": "Sembunyikan Titik Notifikasi Langganan",
                    "it": "Nascondi punti notifiche iscrizioni",
                    "ja": "サブスクリプション通知ドットを非表示にする",
                    "ko": "구독 알림 점 숨기기",
                    "ms": "Sembunyikan Titik Pemberitahuan Langganan",
                    "nb": "Skjul abonnementsvarslingspunkter",
                    "pl": "Ukryj kropki powiadomień o subskrypcjach",
                    "pt": "Ocultar pontos de notificações de assinaturas",
                    "ro": "Ascunde punctele de notificări pentru abonamente",
                    "ru": "Скрыть точки уведомлений о подписках",
                    "sk": "Hide Subscriptions Notifications Bodky",
                    "es": "Ocultar puntos de notificaciones de suscripciones",
                    "sv": "Dölj prickar för prenumerationsaviseringar",
                    "th": "ซ่อนจุดการแจ้งเตือนการสมัครสมาชิก",
                    "tr": "Abonelik Bildirim Noktalarını Gizle",
                    "uk": "Приховати крапки сповіщень про підписки",
                    "vi": "Ẩn dấu chấm thông báo đăng ký"
                  },
                id: "untrap_subscriptions_hide_subscriptions_notifications_dots",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء الاشتراكات النقاط الحية",
                    "ca": "Amaga les subscripcions Live Dots",
                    "zh-CN": "隐藏订阅实时点",
                    "zh-TW": "隱藏訂閱即時點",
                    "hr": "Sakrij pretplate Live Dots",
                    "cs": "Skrýt živé tečky odběrů",
                    "da": "Skjul abonnementer Live Dots",
                    "nl": "Abonnementen verbergen Live Dots",
                    "en": "Hide Subscriptions Live Dots",
                    "fi": "Piilota tilaukset Live Dots",
                    "fr": "Masquer les points en direct des abonnements",
                    "de": "Live-Punkte für Abonnements ausblenden",
                    "el": "Απόκρυψη Συνδρομών Live Dots",
                    "he": "הסתר מנויים Live Dots",
                    "hi": "सब्सक्रिप्शन लाइव डॉट्स छिपाएँ",
                    "hu": "Előfizetések elrejtése élő pontok",
                    "id": "Sembunyikan Titik Langsung Langganan",
                    "it": "Nascondi abbonamenti Live Dots",
                    "ja": "サブスクリプションを非表示にする Live Dots",
                    "ko": "구독 라이브 도트 숨기기",
                    "ms": "Sembunyikan Titik Langsung Langganan",
                    "nb": "Skjul abonnementer Live Dots",
                    "pl": "Ukryj aktywne kropki subskrypcji",
                    "pt": "Ocultar pontos ativos de assinaturas",
                    "ro": "Ascunde punctele live abonamente",
                    "ru": "Скрыть подписки Живые точки",
                    "sk": "Skryť živé bodky odberov",
                    "es": "Ocultar suscripciones Live Dots",
                    "sv": "Dölj prenumerationer Live Dots",
                    "th": "ซ่อนการสมัครสมาชิก Live Dots",
                    "tr": "Abonelikleri Gizle Canlı Noktalar",
                    "uk": "Приховати живі точки підписок",
                    "vi": "Ẩn đăng ký Dấu chấm trực tiếp"
                  },
                id: "untrap_subscriptions_hide_subscriptions_live_dots",
                defaultValue: false
            }
        ]
    }
];

const subscriptionsPageMobileGroups_Suggestions = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء مقاطع الفيديو التي تمت مشاهدتها",
            "ca": "Amaga els vídeos vists",
            "zh-CN": "隐藏观看过的视频",
            "zh-TW": "隱藏觀看過的視頻",
            "hr": "Sakrij gledane videozapise",
            "cs": "Skrýt sledovaná videa",
            "da": "Skjul sete videoer",
            "nl": "Verberg bekeken video's",
            "en": "Hide Watched Videos",
            "fi": "Piilota katsotut videot",
            "fr": "Masquer les vidéos regardées",
            "de": "Angesehene Videos ausblenden",
            "el": "Απόκρυψη βίντεο που παρακολουθήσατε",
            "he": "הסתר סרטונים שנצפו",
            "hi": "देखे गए वीडियो छुपाएं",
            "hu": "Megtekintett videók elrejtése",
            "id": "Sembunyikan Video yang Ditonton",
            "it": "Nascondi i video guardati",
            "ja": "視聴したビデオを非表示にする",
            "ko": "시청한 동영상 숨기기",
            "ms": "Sembunyikan Video yang Ditonton",
            "nb": "Skjul sett videoer",
            "pl": "Ukryj oglądane filmy",
            "pt": "Ocultar vídeos assistidos",
            "ro": "Ascunde videoclipurile vizionate",
            "ru": "Скрыть просмотренные видео",
            "sk": "Skryť sledované videá",
            "es": "Ocultar vídeos vistos",
            "sv": "Dölj sedda videor",
            "th": "ซ่อนวิดีโอที่ดู",
            "tr": "İzlenen Videoları Gizle",
            "uk": "Приховати переглянуті відео",
            "vi": "Ẩn video đã xem"
          },
        id: "untrap_subscriptions_hide_watched_videos",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء مقاطع الفيديو المباشرة والعرض الأول",
            "ca": "Amaga vídeos en directe i estrena",
            "zh-CN": "隐藏直播和首映视频",
            "zh-TW": "隱藏直播和首映視頻",
            "hr": "Sakrij videozapise uživo i premijere",
            "cs": "Skrýt živá a premiérová videa",
            "da": "Skjul live- og premierevideoer",
            "nl": "Live- en premièrevideo's verbergen",
            "en": "Hide Live and Premiere Videos",
            "fi": "Piilota live- ja ensiesitysvideot",
            "fr": "Masquer les vidéos en direct et en première",
            "de": "Live- und Premiere-Videos ausblenden",
            "el": "Απόκρυψη ζωντανών βίντεο και βίντεο πρεμιέρας",
            "he": "הסתר סרטונים בשידור חי ובכורה",
            "hi": "लाइव और प्रीमियर वीडियो छुपाएं",
            "hu": "Élő és premier videók elrejtése",
            "id": "Sembunyikan Video Langsung dan Tayang Perdana",
            "it": "Nascondi video dal vivo e in anteprima",
            "ja": "ライブビデオとプレミアビデオを非表示にする",
            "ko": "라이브 및 프리미어 비디오 숨기기",
            "ms": "Sembunyikan Video Langsung dan Tayangan Perdana",
            "nb": "Skjul live- og premierevideoer",
            "pl": "Ukryj filmy na żywo i premiery",
            "pt": "Ocultar vídeos ao vivo e de estreia",
            "ro": "Ascundeți videoclipurile live și în premieră",
            "ru": "Скрыть видео прямых трансляций и премьер",
            "sk": "Skryť živé a premiérové ​​videá",
            "es": "Ocultar vídeos en directo y de estreno",
            "sv": "Dölj live- och premiärvideor",
            "th": "ซ่อนวิดีโอสดและวิดีโอรอบปฐมทัศน์",
            "tr": "Canlı ve İlk Gösterim Videolarını Gizle",
            "uk": "Приховати прямі трансляції та прем'єрні відео",
            "vi": "Ẩn video trực tiếp và công chiếu"
          },
        id: "untrap_subscriptions_hide_live_videos",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء مقاطع الفيديو القادمة",
            "ca": "Amaga els propers vídeos",
            "zh-CN": "隐藏即将播放的视频",
            "zh-TW": "隱藏即將播放的視頻",
            "hr": "Sakrij nadolazeće videozapise",
            "cs": "Skrýt nadcházející videa",
            "da": "Skjul kommende videoer",
            "nl": "Aankomende video's verbergen",
            "en": "Hide Upcoming Videos",
            "fi": "Piilota tulevat videot",
            "fr": "Masquer les vidéos à venir",
            "de": "Kommende Videos ausblenden",
            "el": "Απόκρυψη επερχόμενων βίντεο",
            "he": "הסתר סרטונים קרובים",
            "hi": "आगामी वीडियो छिपाएँ",
            "hu": "Közelgő videók elrejtése",
            "id": "Sembunyikan Video Mendatang",
            "it": "Nascondi i prossimi video",
            "ja": "今後のビデオを隠す",
            "ko": "다가오는 비디오 숨기기",
            "ms": "Sembunyikan Video Akan Datang",
            "nb": "Skjul kommende videoer",
            "pl": "Ukryj nadchodzące filmy",
            "pt": "Ocultar os próximos vídeos",
            "ro": "Ascunde videoclipurile viitoare",
            "ru": "Скрыть предстоящие видео",
            "sk": "Skryť nadchádzajúce videá",
            "es": "Ocultar próximos vídeos",
            "sv": "Dölj kommande videor",
            "th": "ซ่อนวิดีโอที่กำลังจะมีขึ้น",
            "tr": "Gelecek Videoları Gizle",
            "uk": "Приховати майбутні відео",
            "vi": "Ẩn video sắp tới"
          },
        id: "untrap_subscriptions_hide_upcoming_videos",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء السراويل القصيرة",
            "ca": "Amaga pantalons curts",
            "zh-CN": "隐藏短裤",
            "zh-TW": "隱藏短褲",
            "hr": "Sakrij kratke hlače",
            "cs": "Skrýt šortky",
            "da": "Skjul shorts",
            "nl": "Shorts verbergen",
            "en": "Hide Shorts",
            "fi": "Piilota shortsit",
            "fr": "Masquer les courts métrages",
            "de": "Shorts verstecken",
            "el": "Απόκρυψη σορτς",
            "he": "הסתר מכנסיים קצרים",
            "hi": "शॉर्ट्स छुपाएं",
            "hu": "Rövidnadrágok elrejtése",
            "id": "Sembunyikan Celana Pendek",
            "it": "Nascondi pantaloncini",
            "ja": "ショートパンツを隠す",
            "ko": "쇼츠 숨기기",
            "ms": "Sembunyikan Seluar Pendek",
            "nb": "Skjul shorts",
            "pl": "Ukryj szorty",
            "pt": "Ocultar Shorts",
            "ro": "Ascunde pantaloni scurți",
            "ru": "Скрыть шорты",
            "sk": "Skryť šortky",
            "es": "Ocultar pantalones cortos",
            "sv": "Göm shorts",
            "th": "ซ่อนวิดีโอสั้น",
            "tr": "Kısaları Gizle",
            "uk": "Сховати шорти",
            "vi": "Ẩn video ngắn"
          },
        id: "untrap_subscriptions_hide_shorts",
        defaultValue: false
    }
];

// MARK: - Builder

// Desktop

const subscriptionsPageDesktopGroups = [
    {
        groupName: {
            "ar": "آحرون",
            "ca": "Altres",
            "zh-CN": "其他的",
            "zh-TW": "其他的",
            "hr": "Drugi",
            "cs": "Ostatní",
            "da": "Andre",
            "nl": "Anderen",
            "en": "Others",
            "fi": "Muut",
            "fr": "Autres",
            "de": "Andere",
            "el": "Οι υπολοιποι",
            "he": "אחרים",
            "hi": "अन्य",
            "hu": "Mások",
            "id": "Yang lain",
            "it": "Altri",
            "ja": "その他",
            "ko": "기타",
            "ms": "Lain-lain",
            "nb": "Andre",
            "pl": "Inni",
            "pt": "Outros",
            "ro": "Alții",
            "ru": "Другие",
            "sk": "Iní",
            "es": "Otros",
            "sv": "Andra",
            "th": "คนอื่น",
            "tr": "Diğerleri",
            "uk": "Інші",
            "vi": "Người khác"
          },
        groupId: "other",
        parentCategoryId: "subscriptionsPage",
        options: subscriptionsPageDesktopGroups_Other
    }
];

// Mobile

const subscriptionsPageMobileGroups = [
    {
        groupName: {
            "ar": "قائمة الاشتراكات",
            "ca": "Llista de subscripcions",
            "zh-CN": "订阅列表",
            "zh-TW": "訂閱列表",
            "hr": "Popis pretplata",
            "cs": "Seznam předplatných",
            "da": "Abonnementsliste",
            "nl": "Abonnementenlijst",
            "en": "Subscriptions List",
            "fi": "Tilausluettelo",
            "fr": "Liste des abonnements",
            "de": "Abonnementliste",
            "el": "Λίστα συνδρομών",
            "he": "רשימת מנויים",
            "hi": "सदस्यता सूची",
            "hu": "Előfizetések listája",
            "id": "Daftar Langganan",
            "it": "Elenco abbonamenti",
            "ja": "購読リスト",
            "ko": "구독 목록",
            "ms": "Senarai Langganan",
            "nb": "Abonnementsliste",
            "pl": "Lista subskrypcji",
            "pt": "Lista de assinaturas",
            "ro": "Lista abonamentelor",
            "ru": "Список подписок",
            "sk": "Zoznam odberov",
            "es": "Lista de suscripciones",
            "sv": "Prenumerationslista",
            "th": "รายการสมัครสมาชิก",
            "tr": "Abonelikler Listesi",
            "uk": "Список підписок",
            "vi": "Danh sách đăng ký"
          },
        groupId: "subscriptionsList",
        parentCategoryId: "subscriptionsPage",
        options: subscriptionsPageMobileGroups_SubscriptionsList
    },
    {
        groupName: {
            "ar": "اقتراحات",
            "ca": "Suggeriments",
            "zh-CN": "建议",
            "zh-TW": "建議",
            "hr": "Prijedlozi",
            "cs": "Návrhy",
            "da": "Forslag",
            "nl": "Suggesties",
            "en": "Suggestions",
            "fi": "Ehdotukset",
            "fr": "Suggestions",
            "de": "Vorschläge",
            "el": "Προτάσεις",
            "he": "הצעות",
            "hi": "सुझाव",
            "hu": "Javaslatok",
            "id": "Saran",
            "it": "Suggerimenti",
            "ja": "提案",
            "ko": "제안",
            "ms": "Cadangan",
            "nb": "Forslag",
            "pl": "Propozycje",
            "pt": "Sugestões",
            "ro": "Sugestii",
            "ru": "Предложения",
            "sk": "Návrhy",
            "es": "Sugerencias",
            "sv": "Förslag",
            "th": "ข้อเสนอแนะ",
            "tr": "Öneriler",
            "uk": "Пропозиції",
            "vi": "Đề xuất"
          },
        groupId: "suggestions",
        parentCategoryId: "subscriptionsPage",
        options: subscriptionsPageMobileGroups_Suggestions
    }
];
