// MARK: - Desktop Groups

const headerDesktopGroups_SearchBar = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء شريط البحث",
            "ca": "Amaga la barra de cerca",
            "zh-CN": "隐藏搜索栏",
            "zh-TW": "隱藏搜尋欄",
            "hr": "Sakrij traku za pretraživanje",
            "cs": "Skrýt vyhledávací lištu",
            "da": "Skjul søgelinjen",
            "nl": "Zoekbalk verbergen",
            "en": "Hide Search Bar",
            "fi": "Piilota hakupalkki",
            "fr": "Masquer la barre de recherche",
            "de": "Suchleiste ausblenden",
            "el": "Απόκρυψη γραμμής αναζήτησης",
            "he": "הסתר את שורת החיפוש",
            "hi": "खोज बार छिपाएँ",
            "hu": "Keresősáv elrejtése",
            "id": "Sembunyikan Bilah Pencarian",
            "it": "Nascondi la barra di ricerca",
            "ja": "検索バーを非表示にする",
            "ko": "검색창 숨기기",
            "ms": "Sembunyikan Bar Carian",
            "nb": "Skjul søkefeltet",
            "pl": "Ukryj pasek wyszukiwania",
            "pt": "Ocultar barra de pesquisa",
            "ro": "Ascundeți bara de căutare",
            "ru": "Скрыть панель поиска",
            "sk": "Skryť panel vyhľadávania",
            "es": "Ocultar barra de búsqueda",
            "sv": "Dölj sökfältet",
            "th": "ซ่อนแถบค้นหา",
            "tr": "Arama Çubuğunu Gizle",
            "uk": "Приховати панель пошуку",
            "vi": "Ẩn thanh tìm kiếm"
          },
        id: "untrap_header_hide_search_bar",
        defaultValue: false,
        childOffOptions: [
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء اقتراحات البحث",
                    "ca": "Amaga els suggeriments de cerca",
                    "zh-CN": "隐藏搜索建议",
                    "zh-TW": "隱藏搜尋建議",
                    "hr": "Sakrij prijedloge pretraživanja",
                    "cs": "Skrýt návrhy vyhledávání",
                    "da": "Skjul søgeforslag",
                    "nl": "Zoeksuggesties verbergen",
                    "en": "Hide Search Suggestions",
                    "fi": "Piilota hakuehdotukset",
                    "fr": "Masquer les suggestions de recherche",
                    "de": "Suchvorschläge ausblenden",
                    "el": "Απόκρυψη προτάσεων αναζήτησης",
                    "he": "הסתר הצעות חיפוש",
                    "hi": "खोज सुझाव छिपाएँ",
                    "hu": "Keresési javaslatok elrejtése",
                    "id": "Sembunyikan Saran Pencarian",
                    "it": "Nascondi suggerimenti di ricerca",
                    "ja": "検索候補を非表示にする",
                    "ko": "검색 제안 숨기기",
                    "ms": "Sembunyikan Cadangan Carian",
                    "nb": "Skjul søkeforslag",
                    "pl": "Ukryj sugestie wyszukiwania",
                    "pt": "Ocultar sugestões de pesquisa",
                    "ro": "Ascundeți sugestiile de căutare",
                    "ru": "Скрыть поисковые предложения",
                    "sk": "Skryť návrhy vyhľadávania",
                    "es": "Ocultar sugerencias de búsqueda",
                    "sv": "Dölj sökförslag",
                    "th": "ซ่อนคำแนะนำการค้นหา",
                    "tr": "Arama Önerilerini Gizle",
                    "uk": "Приховати підказки пошуку",
                    "vi": "Ẩn đề xuất tìm kiếm"
                  },
                id: "untrap_search_bar_hide_suggestions",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء عمليات البحث السابقة",
                    "ca": "Amaga les cerques anteriors",
                    "zh-CN": "隐藏以前的搜索",
                    "zh-TW": "隱藏先前的搜索",
                    "hr": "Sakrij prethodna pretraživanja",
                    "cs": "Skrýt předchozí hledání",
                    "da": "Skjul tidligere søgninger",
                    "nl": "Verberg eerdere zoekopdrachten",
                    "en": "Hide Previous Searches",
                    "fi": "Piilota aiemmat haut",
                    "fr": "Masquer les recherches précédentes",
                    "de": "Vorherige Suchen ausblenden",
                    "el": "Απόκρυψη προηγούμενων αναζητήσεων",
                    "he": "הסתר חיפושים קודמים",
                    "hi": "पिछली खोजें छिपाएँ",
                    "hu": "Korábbi keresések elrejtése",
                    "id": "Sembunyikan Pencarian Sebelumnya",
                    "it": "Nascondi ricerche precedenti",
                    "ja": "以前の検索を非表示にする",
                    "ko": "이전 검색 숨기기",
                    "ms": "Sembunyikan Carian Sebelumnya",
                    "nb": "Skjul tidligere søk",
                    "pl": "Ukryj poprzednie wyszukiwania",
                    "pt": "Ocultar pesquisas anteriores",
                    "ro": "Ascunde căutările anterioare",
                    "ru": "Скрыть предыдущие поиски",
                    "sk": "Skryť predchádzajúce vyhľadávania",
                    "es": "Ocultar búsquedas anteriores",
                    "sv": "Dölj tidigare sökningar",
                    "th": "ซ่อนการค้นหาก่อนหน้า",
                    "tr": "Önceki Aramaları Gizle",
                    "uk": "Приховати попередні пошуки",
                    "vi": "Ẩn các tìm kiếm trước đó"
                  },
                id: "untrap_search_bar_hide_previous_searches",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء زر 'البحث الصوتي'",
                    "ca": "Amaga el botó 'Cerca per veu'",
                    "zh-CN": "隐藏“语音搜索”按钮",
                    "zh-TW": "隱藏「語音搜尋」按鈕",
                    "hr": "Sakrij gumb 'Glasovno pretraživanje'",
                    "cs": "Skrýt tlačítko „Hlasové vyhledávání“",
                    "da": "Skjul knappen 'Stemmesøgning'",
                    "nl": "Knop 'Gesproken zoekopdracht' verbergen",
                    "en": "Hide 'Voice Search' Button",
                    "fi": "Piilota 'Puhehaku' -painike",
                    "fr": "Masquer le bouton « Recherche vocale »",
                    "de": "Schaltfläche „Sprachsuche“ ausblenden",
                    "el": "Απόκρυψη του κουμπιού 'Φωνητική αναζήτηση'",
                    "he": "הסתר את לחצן 'חיפוש קולי'",
                    "hi": "'ध्वनि खोज' बटन छिपाएँ",
                    "hu": "A „Hangalapú keresés” gomb elrejtése",
                    "id": "Sembunyikan Tombol 'Pencarian Suara'",
                    "it": "Nascondi il pulsante 'Ricerca vocale'",
                    "ja": "「音声検索」ボタンを非表示にする",
                    "ko": "'음성검색' 버튼 숨기기",
                    "ms": "Sembunyikan Butang 'Carian Suara'",
                    "nb": "Skjul 'Stemmesøk'-knappen",
                    "pl": "Ukryj przycisk „Wyszukiwanie głosowe”",
                    "pt": "Ocultar o botão 'Pesquisa por voz'",
                    "ro": "Ascundeți butonul „Căutare vocală”",
                    "ru": "Скрыть кнопку «Голосовой поиск»",
                    "sk": "Skryť tlačidlo „Hlasové vyhľadávanie“",
                    "es": "Ocultar el botón 'Búsqueda por voz'",
                    "sv": "Dölj knappen 'Röstsökning'",
                    "th": "ซ่อนปุ่ม 'ค้นหาด้วยเสียง'",
                    "tr": "'Sesli Arama' Düğmesini Gizle",
                    "uk": "Сховати кнопку «Голосовий пошук»",
                    "vi": "Ẩn nút 'Tìm kiếm bằng giọng nói'"
                  },
                id: "untrap_header_hide_voice_search_button",
                defaultValue: false
            }
        ]
    }
]

const headerDesktopGroups_Logo = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الشعار",
            "ca": "Amaga el logotip",
            "zh-CN": "隐藏标志",
            "zh-TW": "隱藏標誌",
            "hr": "Sakrij logotip",
            "cs": "Skrýt logo",
            "da": "Skjul logo",
            "nl": "Logo verbergen",
            "en": "Hide Logo",
            "fi": "Piilota logo",
            "fr": "Masquer le logo",
            "de": "Logo ausblenden",
            "el": "Απόκρυψη λογότυπου",
            "he": "הסתר לוגו",
            "hi": "लोगो छिपाएँ",
            "hu": "Logó elrejtése",
            "id": "Sembunyikan Logo",
            "it": "Nascondi logo",
            "ja": "ロゴを隠す",
            "ko": "로고 숨기기",
            "ms": "Sembunyikan Logo",
            "nb": "Skjul logo",
            "pl": "Ukryj logo",
            "pt": "Ocultar logotipo",
            "ro": "Ascunde sigla",
            "ru": "Скрыть логотип",
            "sk": "Skryť logo",
            "es": "Ocultar logotipo",
            "sv": "Dölj logotyp",
            "th": "ซ่อนโลโก้",
            "tr": "Logoyu Gizle",
            "uk": "Приховати логотип",
            "vi": "Ẩn biểu tượng"
          },
        id: "untrap_header_hide_logo",
        defaultValue: false,
        childOffOptions: [
            {
                type: "select",
                
                name: {
                    "ar": "لون الشعار",
                    "ca": "Color del logotip",
                    "zh-CN": "标志颜色",
                    "zh-TW": "標誌顏色",
                    "hr": "Boja logotipa",
                    "cs": "Barva loga",
                    "da": "Logo farve",
                    "nl": "Logokleur",
                    "en": "Logo Color",
                    "fi": "Logon väri",
                    "fr": "Couleur du logo",
                    "de": "Logofarbe",
                    "el": "Χρώμα λογότυπου",
                    "he": "צבע לוגו",
                    "hi": "लोगो का रंग",
                    "hu": "Logó színe",
                    "id": "Warna Logo",
                    "it": "Colore del logo",
                    "ja": "ロゴの色",
                    "ko": "로고 색상",
                    "ms": "Warna Logo",
                    "no": "Logo farge",
                    "pl": "Kolor logo",
                    "pt": "Cor do logotipo",
                    "ro": "Culoare logo",
                    "ru": "Цвет логотипа",
                    "sk": "Farba loga",
                    "es": "Color del logotipo",
                    "sv": "Logotyp färg",
                    "th": "สีโลโก้",
                    "tr": "Logo Rengi",
                    "uk": "Колір логотипу",
                    "vi": "Màu biểu tượng"
                },
                id: "untrap_header_logo_color",
                defaultValue: "defualt",
                selects: [
                    {
                        name: {
                            "ar": "تقصير",
                            "ca": "Per defecte",
                            "zh-CN": "默认",
                            "zh-TW": "預設",
                            "hr": "Zadano",
                            "cs": "Výchozí",
                            "da": "Standard",
                            "nl": "Standaard",
                            "en": "Default",
                            "fi": "Oletus",
                            "fr": "Défaut",
                            "de": "Standard",
                            "el": "Προκαθορισμένο",
                            "he": "בְּרִירַת מֶחדָל",
                            "hi": "गलती करना",
                            "hu": "Alapértelmezett",
                            "id": "Bawaan",
                            "it": "Predefinito",
                            "ja": "デフォルト",
                            "ko": "기본",
                            "ms": "Lalai",
                            "nb": "Misligholde",
                            "pl": "Domyślny",
                            "pt": "Padrão",
                            "ro": "Mod implicit",
                            "ru": "По умолчанию",
                            "sk": "Predvolené",
                            "es": "Por defecto",
                            "sv": "Standard",
                            "th": "ค่าเริ่มต้น",
                            "tr": "Varsayılan",
                            "uk": "За замовчуванням",
                            "vi": "Mặc định"
                          },
                        id: "default"
                    },
                      {
                          type: "checkbox",
                          name: {
                              "ar": "أحادية اللون",
                              "ca": "Monocrom",
                              "zh-CN": "单色",
                              "zh-TW": "單色",
                              "hr": "Jednobojni",
                              "cs": "Černobílý",
                              "da": "Monokrom",
                              "nl": "Monochroom",
                              "en": "Monochrome",
                              "fi": "Yksivärinen",
                              "fr": "Monochromes",
                              "de": "Einfarbig",
                              "el": "Μονόχρωμος",
                              "he": "מונוכרום",
                              "hi": "एक रंग का",
                              "hu": "Monokróm",
                              "id": "Satu warna",
                              "it": "Monocromo",
                              "ja": "モノクロ",
                              "ko": "단색화",
                              "ms": "Monokrom",
                              "no": "Monokrom",
                              "pl": "Monochromia",
                              "pt": "Monocromático",
                              "ro": "Monocrom",
                              "ru": "Монохромный",
                              "sk": "Monochromatický",
                              "es": "Monocromo",
                              "sv": "Svartvit",
                              "th": "ขาวดำ",
                              "tr": "Tek renkli",
                              "uk": "Монохромний",
                              "vi": "Đơn sắc"
                            },
                          id: "monochrome"
                      },
                      {
                          type: "checkbox",
                          name: {
                              "ar": "تدرج الرمادي",
                              "ca": "Escala de grisos",
                              "zh-CN": "灰度",
                              "zh-TW": "灰階",
                              "hr": "Sivi tonovi",
                              "cs": "Stupně šedi",
                              "da": "Gråtoner",
                              "nl": "Grijstinten",
                              "en": "Grayscale",
                              "fi": "Harmaasävy",
                              "fr": "Niveaux de gris",
                              "de": "Graustufen",
                              "el": "Κλίμακα του γκρι",
                              "he": "גווני אפור",
                              "hi": "स्केल",
                              "hu": "Szürkeárnyalatos",
                              "id": "Skala abu-abu",
                              "it": "Scala di grigi",
                              "ja": "グレースケール",
                              "ko": "그레이스케일",
                              "ms": "Skala kelabu",
                              "no": "Gråtoner",
                              "pl": "Skala szarości",
                              "pt": "Tons de cinza",
                              "ro": "Scara tonurilor de gri",
                              "ru": "Оттенки серого",
                              "sk": "Odtiene šedej",
                              "es": "Escala de grises",
                              "sv": "Gråskala",
                              "th": "ระดับสีเทา",
                              "tr": "Gri tonlamalı",
                              "uk": "Відтінки сірого",
                              "vi": "Thang độ xám"
                            },
                          id: "grayscale"
                      }
                ]
            },
            {
                type: "checkbox",
                name: {
                    "ar": "تعطيل رابط الشعار",
                    "ca": "Desactiva l'enllaç del logotip",
                    "zh-CN": "禁用徽标链接",
                    "zh-TW": "禁用徽標連結",
                    "hr": "Onemogući vezu s logotipom",
                    "cs": "Zakázat odkaz na logo",
                    "da": "Deaktiver logolink",
                    "nl": "Schakel Logolink uit",
                    "en": "Disable Logo Link",
                    "fi": "Poista logolinkki käytöstä",
                    "fr": "Désactiver le lien du logo",
                    "de": "Logo-Link deaktivieren",
                    "el": "Απενεργοποιήστε τη σύνδεση λογότυπου",
                    "he": "השבת קישור לוגו",
                    "hi": "लोगो लिंक अक्षम करें",
                    "hu": "Logo Link letiltása",
                    "id": "Nonaktifkan Tautan Logo",
                    "it": "Disabilita collegamento logo",
                    "ja": "ロゴリンクを無効にする",
                    "ko": "로고 링크 비활성화",
                    "ms": "Lumpuhkan Pautan Logo",
                    "nb": "Deaktiver logokobling",
                    "pl": "Wyłącz łącze do logo",
                    "pt": "Desativar link do logotipo",
                    "ro": "Dezactivați linkul pentru logo",
                    "ru": "Отключить ссылку на логотип",
                    "sk": "Zakázať odkaz na logo",
                    "es": "Deshabilitar enlace de logotipo",
                    "sv": "Inaktivera logotyplänk",
                    "th": "ปิดการใช้งานลิงค์โลโก้",
                    "tr": "Logo Bağlantısını Devre Dışı Bırak",
                    "uk": "Вимкнути посилання на логотип",
                    "vi": "Vô hiệu hóa liên kết logo"
                  },
                id: "untrap_header_disable_logo_link",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء رمز البلد الشعار",
                    "ca": "Amaga el codi de país del logotip",
                    "zh-CN": "隐藏徽标国家代码",
                    "zh-TW": "隱藏標誌國家代碼",
                    "hr": "Sakrij kod države logotipa",
                    "cs": "Skrýt kód země s logem",
                    "da": "Skjul logoets landekode",
                    "nl": "Landcode logo verbergen",
                    "en": "Hide Logo Country Code",
                    "fi": "Piilota logon maakoodi",
                    "fr": "Masquer le logo Code pays",
                    "de": "Logo-Ländercode ausblenden",
                    "el": "Απόκρυψη λογότυπου κωδικού χώρας",
                    "he": "הסתר קוד מדינה של לוגו",
                    "hi": "लोगो देश कोड छिपाएँ",
                    "hu": "A logó országkódjának elrejtése",
                    "id": "Sembunyikan Logo Kode Negara",
                    "it": "Nascondi il codice paese del logo",
                    "ja": "ロゴの国コードを非表示にする",
                    "ko": "로고 국가 코드 숨기기",
                    "ms": "Sembunyikan Kod Negara Logo",
                    "nb": "Skjul logoens landskode",
                    "pl": "Ukryj kod kraju logo",
                    "pt": "Ocultar código do país do logotipo",
                    "ro": "Ascunde codul de țară al siglei",
                    "ru": "Скрыть логотип Код страны",
                    "sk": "Skryť kód krajiny s logom",
                    "es": "Ocultar logotipo Código de país",
                    "sv": "Dölj logotypens landskod",
                    "th": "ซ่อนรหัสประเทศโลโก้",
                    "tr": "Logo Ülke Kodunu Gizle",
                    "uk": "Приховати код країни логотипу",
                    "vi": "Ẩn mã quốc gia của logo"
                  },
                id: "untrap_header_hide_logo_country_code",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء الكلمة في الشعار",
                    "ca": "Amaga la paraula al logotip",
                    "zh-CN": "隐藏徽标中的文字",
                    "zh-TW": "隱藏徽標中的文字",
                    "hr": "Sakrij riječ u logotipu",
                    "cs": "Skrýt slovo v logu",
                    "da": "Skjul ord i logoet",
                    "nl": "Woord in logo verbergen",
                    "en": "Hide Word in Logo",
                    "fi": "Piilota Word logossa",
                    "fr": "Masquer le mot dans le logo",
                    "de": "Wort im Logo ausblenden",
                    "el": "Απόκρυψη του Word στο λογότυπο",
                    "he": "הסתר את Word בלוגו",
                    "hi": "लोगो में शब्द छिपाएँ",
                    "hu": "Szó elrejtése a logóban",
                    "id": "Sembunyikan Kata di Logo",
                    "it": "Nascondi la parola nel logo",
                    "ja": "ロゴ内の単語を非表示にする",
                    "ko": "로고에 단어 숨기기",
                    "ms": "Sembunyikan Word dalam Logo",
                    "nb": "Skjul Word i logoen",
                    "pl": "Ukryj słowo w logo",
                    "pt": "Ocultar palavra no logotipo",
                    "ro": "Ascundeți cuvântul în logo",
                    "ru": "Скрыть слово в логотипе",
                    "sk": "Skryť slovo v logu",
                    "es": "Ocultar palabra en el logotipo",
                    "sv": "Göm Word i logotypen",
                    "th": "ซ่อนคำในโลโก้",
                    "tr": "Logodaki Kelimeyi Gizle",
                    "uk": "Приховати слово в логотипі",
                    "vi": "Ẩn từ trong Logo"
                  },
                id: "untrap_header_hide_logo_wordmark",
                defaultValue: false
            }
        ]
    }
]

const headerDesktopGroups_Buttons = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'إنشاء'",
            "ca": "Amaga el botó 'Crea'",
            "zh-CN": "隐藏“创建”按钮",
            "zh-TW": "隱藏“創建”按鈕",
            "hr": "Sakrij gumb 'Stvori'",
            "cs": "Skrýt tlačítko 'Vytvořit'",
            "da": "Skjul knappen 'Opret'",
            "nl": "Knop 'Maken' verbergen",
            "en": "Hide 'Create' Button",
            "fi": "Piilota 'Luo'-painike",
            "fr": "Masquer le bouton « Créer »",
            "de": "Schaltfläche „Erstellen“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Δημιουργία'",
            "he": "הסתר את כפתור 'צור'",
            "hi": "'बनाएँ' बटन छिपाएँ",
            "hu": "A 'Létrehozás' gomb elrejtése",
            "id": "Sembunyikan Tombol 'Buat'",
            "it": "Nascondi il pulsante 'Crea'",
            "ja": "「作成」ボタンを非表示にする",
            "ko": "'만들기' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Buat'",
            "nb": "Skjul 'Opprett'-knappen",
            "pl": "Ukryj przycisk „Utwórz”",
            "pt": "Ocultar botão 'Criar'",
            "ro": "Ascundeți butonul „Creați”",
            "ru": "Скрыть кнопку «Создать»",
            "sk": "Skryť tlačidlo „Vytvoriť“",
            "es": "Ocultar el botón 'Crear'",
            "sv": "Dölj 'Skapa'-knappen",
            "th": "ซ่อนปุ่ม 'สร้าง'",
            "tr": "'Oluştur' Düğmesini Gizle",
            "uk": "Сховати кнопку «Створити»",
            "vi": "Ẩn nút 'Tạo'"
          },
        id: "untrap_header_hide_create_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'تحميل'",
            "ca": "Amaga el botó 'Pujar'",
            "zh-CN": "隐藏“上传”按钮",
            "zh-TW": "隱藏“上傳”按鈕",
            "hr": "Sakrij gumb 'Učitaj'",
            "cs": "Skrýt tlačítko „Nahrát“",
            "da": "Skjul knappen 'Upload'",
            "nl": "Knop 'Uploaden' verbergen",
            "en": "Hide 'Upload' Button",
            "fi": "Piilota 'Lataa'-painike",
            "fr": "Masquer le bouton « Télécharger »",
            "de": "Schaltfläche „Hochladen“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Μεταφόρτωση'",
            "he": "הסתר את לחצן 'העלה'",
            "hi": "'अपलोड' बटन छुपाएं",
            "hu": "A „Feltöltés” ​​gomb elrejtése",
            "id": "Sembunyikan Tombol 'Unggah'",
            "it": "Nascondi il pulsante 'Carica'",
            "ja": "「アップロード」ボタンを非表示にする",
            "ko": "'업로드' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Muat Naik'",
            "no": "Skjul 'Last opp'-knappen",
            "pl": "Ukryj przycisk „Prześlij”",
            "pt": "Ocultar botão 'Upload'",
            "ro": "Ascundeți butonul „Încărcare”",
            "ru": "Скрыть кнопку «Загрузить»",
            "sk": "Skryť tlačidlo „Nahrať“",
            "es": "Ocultar el botón 'Subir'",
            "sv": "Dölj 'Ladda upp'-knappen",
            "th": "ซ่อนปุ่ม 'อัปโหลด'",
            "tr": "'Yükle' Düğmesini Gizle",
            "uk": "Сховати кнопку «Завантажити»",
            "vi": "Ẩn nút 'Tải lên'"
          },
        id: "untrap_header_hide_upload_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'الإخطارات'",
            "ca": "Amaga el botó 'Notificacions'",
            "zh-CN": "隐藏“通知”按钮",
            "zh-TW": "隱藏「通知」按鈕",
            "hr": "Sakrij gumb 'Obavijesti'",
            "cs": "Skrýt tlačítko 'Oznámení'",
            "da": "Skjul knappen 'Meddelelser'",
            "nl": "Knop 'Meldingen' verbergen",
            "en": "Hide 'Notifications' Button",
            "fi": "Piilota 'Ilmoitukset'-painike",
            "fr": "Masquer le bouton « Notifications »",
            "de": "Schaltfläche „Benachrichtigungen“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Ειδοποιήσεις'",
            "he": "הסתר את לחצן 'התראות'",
            "hi": "'सूचनाएँ' बटन छिपाएँ",
            "hu": "Az „Értesítések” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Pemberitahuan'",
            "it": "Nascondi il pulsante 'Notifiche'",
            "ja": "「通知」ボタンを非表示にする",
            "ko": "'알림' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Pemberitahuan'",
            "nb": "Skjul 'Varsler'-knappen",
            "pl": "Ukryj przycisk „Powiadomienia”",
            "pt": "Ocultar botão 'Notificações'",
            "ro": "Ascundeți butonul „Notificări”",
            "ru": "Скрыть кнопку «Уведомления»",
            "sk": "Skryť tlačidlo „Upozornenia“",
            "es": "Ocultar el botón 'Notificaciones'",
            "sv": "Dölj 'Meddelanden'-knappen",
            "th": "ซ่อนปุ่ม 'การแจ้งเตือน'",
            "tr": "'Bildirimler' Düğmesini Gizle",
            "uk": "Приховати кнопку «Сповіщення»",
            "vi": "Ẩn nút 'Thông báo'"
          },
        id: "untrap_header_hide_notifications_bell",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الصورة الرمزية",
            "ca": "Amaga l'avatar",
            "zh-CN": "隐藏头像",
            "zh-TW": "隱藏頭像",
            "hr": "Sakrij avatar",
            "cs": "Skrýt Avatara",
            "da": "Skjul Avatar",
            "nl": "Avatar verbergen",
            "en": "Hide Avatar",
            "fi": "Piilota Avatar",
            "fr": "Masquer l'avatar",
            "de": "Avatar ausblenden",
            "el": "Απόκρυψη Avatar",
            "he": "הסתר אווטאר",
            "hi": "अवतार छिपाएँ",
            "hu": "Avatar elrejtése",
            "id": "Sembunyikan Avatar",
            "it": "Nascondi l'avatar",
            "ja": "アバターを隠す",
            "ko": "아바타 숨기기",
            "ms": "Sembunyikan Avatar",
            "nb": "Skjul Avatar",
            "pl": "Ukryj awatara",
            "pt": "Ocultar Avatar",
            "ro": "Ascundeți avatarul",
            "ru": "Скрыть аватар",
            "sk": "Skryť Avatara",
            "es": "Ocultar avatar",
            "sv": "Göm Avatar",
            "th": "ซ่อนอวตาร",
            "tr": "Avatarı Gizle",
            "uk": "Приховати аватар",
            "vi": "Ẩn hình đại diện"
          },
        id: "untrap_header_hide_button_avatar",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "الصورة الرمزية ذات التدرج الرمادي",
            "ca": "Avatar en escala de grisos",
            "zh-CN": "灰度头像",
            "zh-TW": "灰階頭像",
            "hr": "Avatar u sivim tonovima",
            "cs": "Avatar ve stupních šedi",
            "da": "Avatar i gråtoner",
            "nl": "Grijswaardenavatar",
            "en": "Grayscale Avatar",
            "fi": "Harmaasävy Avatar",
            "fr": "Avatar en niveaux de gris",
            "de": "Graustufen-Avatar",
            "el": "Avatar σε κλίμακα του γκρι",
            "he": "אוואטר בגווני אפור",
            "hi": "ग्रेस्केल अवतार",
            "hu": "Szürkeárnyalatos Avatar",
            "id": "Avatar Skala Abu-Abu",
            "it": "Avatar in scala di grigi",
            "ja": "グレースケールのアバター",
            "ko": "그레이스케일 아바타",
            "ms": "Avatar Skala Kelabu",
            "nb": "Avatar i gråtoner",
            "pl": "Awatar w skali szarości",
            "pt": "Avatar em tons de cinza",
            "ro": "Avatar în tonuri de gri",
            "ru": "Аватар в оттенках серого",
            "sk": "Avatar v odtieňoch sivej",
            "es": "Avatar en escala de grises",
            "sv": "Avatar i gråskala",
            "th": "อวาตาร์ระดับสีเทา",
            "tr": "Gri Tonlamalı Avatar",
            "uk": "Аватар у відтінках сірого",
            "vi": "Hình đại diện thang độ xám"
          },
        id: "untrap_header_grayscale_button_avatar",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'تسجيل الدخول'",
            "ca": "Amaga el botó 'Iniciar sessió'",
            "zh-CN": "隐藏“登录”按钮",
            "zh-TW": "隱藏「登入」按鈕",
            "hr": "Sakrij gumb 'Prijava'",
            "cs": "Skrýt tlačítko „Přihlásit se“",
            "da": "Skjul 'Log ind'-knappen",
            "nl": "Knop 'Aanmelden' verbergen",
            "en": "Hide 'Sign In' Button",
            "fi": "Piilota 'Kirjaudu sisään' -painike",
            "fr": "Masquer le bouton « Connexion »",
            "de": "Schaltfläche „Anmelden“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Είσοδος'",
            "he": "הסתר את כפתור 'היכנס'",
            "hi": "'साइन इन' बटन छिपाएँ",
            "hu": "A „Bejelentkezés” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Masuk'",
            "it": "Nascondi il pulsante 'Accedi'",
            "ja": "「サインイン」ボタンを非表示にする",
            "ko": "'로그인' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Log Masuk'",
            "nb": "Skjul 'Logg på'-knappen",
            "pl": "Ukryj przycisk „Zaloguj się”",
            "pt": "Ocultar o botão 'Entrar'",
            "ro": "Ascundeți butonul „Conectați-vă”",
            "ru": "Скрыть кнопку «Войти»",
            "sk": "Skryť tlačidlo „Prihlásiť sa“",
            "es": "Ocultar el botón 'Iniciar sesión'",
            "sv": "Dölj 'Logga in'-knappen",
            "th": "ซ่อนปุ่ม 'ลงชื่อเข้าใช้'",
            "tr": "'Oturum Aç' Düğmesini Gizle",
            "uk": "Приховати кнопку «Увійти»",
            "vi": "Ẩn nút 'Đăng nhập'"
          },
        id: "untrap_header_hide_button_sign_in",
        defaultValue: false
    }
]

const headerDesktopGroups_Other = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الرأس",
            "ca": "Amaga la capçalera",
            "zh-CN": "隐藏标题",
            "zh-TW": "隱藏標題",
            "hr": "Sakrij zaglavlje",
            "cs": "Skrýt záhlaví",
            "da": "Skjul overskrift",
            "nl": "Koptekst verbergen",
            "en": "Hide Header",
            "fi": "Piilota otsikko",
            "fr": "Masquer l'en-tête",
            "de": "Kopfzeile ausblenden",
            "el": "Απόκρυψη κεφαλίδας",
            "he": "הסתר כותרת",
            "hi": "हेडर छुपाएं",
            "hu": "Fejléc elrejtése",
            "id": "Sembunyikan Tajuk",
            "it": "Nascondi intestazione",
            "ja": "ヘッダーを非表示にする",
            "ko": "헤더 숨기기",
            "ms": "Sembunyikan Pengepala",
            "nb": "Skjul topptekst",
            "pl": "Ukryj nagłówek",
            "pt": "Ocultar cabeçalho",
            "ro": "Ascunde antetul",
            "ru": "Скрыть заголовок",
            "sk": "Skryť hlavičku",
            "es": "Ocultar encabezado",
            "sv": "Dölj sidhuvud",
            "th": "ซ่อนส่วนหัว",
            "tr": "Başlığı Gizle",
            "uk": "Приховати заголовок",
            "vi": "Ẩn tiêu đề"
          },
        id: "untrap_header_hide_top_header",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء عدد الإخطارات",
            "ca": "Amaga el recompte de notificacions",
            "zh-CN": "隐藏通知计数",
            "zh-TW": "隱藏通知計數",
            "hr": "Sakrij broj obavijesti",
            "cs": "Skrýt počet upozornění",
            "da": "Skjul antal meddelelser",
            "nl": "Aantal meldingen verbergen",
            "en": "Hide Notifications Count",
            "fi": "Piilota ilmoitusten määrä",
            "fr": "Masquer le nombre de notifications",
            "de": "Anzahl der Benachrichtigungen ausblenden",
            "el": "Απόκρυψη αριθμού ειδοποιήσεων",
            "he": "הסתר את ספירת ההתראות",
            "hi": "अधिसूचनाओं की संख्या छिपाएँ",
            "hu": "Értesítések számának elrejtése",
            "id": "Sembunyikan Jumlah Notifikasi",
            "it": "Nascondi conteggio notifiche",
            "ja": "通知数を非表示にする",
            "ko": "알림 수 숨기기",
            "ms": "Sembunyikan Kiraan Pemberitahuan",
            "nb": "Skjul antall varsler",
            "pl": "Ukryj liczbę powiadomień",
            "pt": "Ocultar contagem de notificações",
            "ro": "Ascunde numărul de notificări",
            "ru": "Скрыть количество уведомлений",
            "sk": "Skryť počet upozornení",
            "es": "Ocultar recuento de notificaciones",
            "sv": "Dölj antal aviseringar",
            "th": "ซ่อนจำนวนการแจ้งเตือน",
            "tr": "Bildirim Sayısını Gizle",
            "uk": "Приховати кількість сповіщень",
            "vi": "Ẩn số lượng thông báo"
          },
        id: "untrap_header_hide_notifications_counter",
        defaultValue: false
    }
]

// MARK: - Mobile Groups

const headerMobileGroups_SearchBar = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'البحث'",
            "ca": "Amaga el botó 'Cerca'",
            "zh-CN": "隐藏“搜索”按钮",
            "zh-TW": "隱藏“搜尋”按鈕",
            "hr": "Sakrij gumb 'Traži'",
            "cs": "Skrýt tlačítko 'Hledat'",
            "da": "Skjul knappen 'Søg'",
            "nl": "Knop 'Zoeken' verbergen",
            "en": "Hide 'Search' Button",
            "fi": "Piilota 'Haku' -painike",
            "fr": "Masquer le bouton « Rechercher »",
            "de": "Schaltfläche „Suchen“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Αναζήτηση'",
            "he": "הסתר את כפתור 'חיפוש'",
            "hi": "'खोज' बटन छिपाएँ",
            "hu": "A „Keresés” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Cari'",
            "it": "Nascondi il pulsante 'Cerca'",
            "ja": "「検索」ボタンを非表示にする",
            "ko": "'검색' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Cari'",
            "nb": "Skjul 'Søk'-knappen",
            "pl": "Ukryj przycisk „Szukaj”",
            "pt": "Ocultar botão 'Pesquisar'",
            "ro": "Ascundeți butonul „Căutare”",
            "ru": "Скрыть кнопку «Поиск»",
            "sk": "Skryť tlačidlo „Hľadať“",
            "es": "Ocultar el botón 'Buscar'",
            "sv": "Dölj 'Sök'-knappen",
            "th": "ซ่อนปุ่ม 'ค้นหา'",
            "tr": "'Ara' Düğmesini Gizle",
            "uk": "Приховати кнопку «Пошук»",
            "vi": "Ẩn nút 'Tìm kiếm'"
          },
        id: "untrap_header_mobile_hide_search_button",
        defaultValue: false,
        childOffOptions: [
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء اقتراحات البحث",
                    "ca": "Amaga els suggeriments de cerca",
                    "zh-CN": "隐藏搜索建议",
                    "zh-TW": "隱藏搜尋建議",
                    "hr": "Sakrij prijedloge pretraživanja",
                    "cs": "Skrýt návrhy vyhledávání",
                    "da": "Skjul søgeforslag",
                    "nl": "Zoeksuggesties verbergen",
                    "en": "Hide Search Suggestions",
                    "fi": "Piilota hakuehdotukset",
                    "fr": "Masquer les suggestions de recherche",
                    "de": "Suchvorschläge ausblenden",
                    "el": "Απόκρυψη προτάσεων αναζήτησης",
                    "he": "הסתר הצעות חיפוש",
                    "hi": "खोज सुझाव छिपाएँ",
                    "hu": "Keresési javaslatok elrejtése",
                    "id": "Sembunyikan Saran Pencarian",
                    "it": "Nascondi suggerimenti di ricerca",
                    "ja": "検索候補を非表示にする",
                    "ko": "검색 제안 숨기기",
                    "ms": "Sembunyikan Cadangan Carian",
                    "nb": "Skjul søkeforslag",
                    "pl": "Ukryj sugestie wyszukiwania",
                    "pt": "Ocultar sugestões de pesquisa",
                    "ro": "Ascundeți sugestiile de căutare",
                    "ru": "Скрыть поисковые предложения",
                    "sk": "Skryť návrhy vyhľadávania",
                    "es": "Ocultar sugerencias de búsqueda",
                    "sv": "Dölj sökförslag",
                    "th": "ซ่อนคำแนะนำการค้นหา",
                    "tr": "Arama Önerilerini Gizle",
                    "uk": "Приховати підказки пошуку",
                    "vi": "Ẩn đề xuất tìm kiếm"
                  },
                id: "untrap_search_bar_hide_suggestions",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء عمليات البحث السابقة",
                    "ca": "Amaga les cerques anteriors",
                    "zh-CN": "隐藏以前的搜索",
                    "zh-TW": "隱藏先前的搜索",
                    "hr": "Sakrij prethodna pretraživanja",
                    "cs": "Skrýt předchozí hledání",
                    "da": "Skjul tidligere søgninger",
                    "nl": "Verberg eerdere zoekopdrachten",
                    "en": "Hide Previous Searches",
                    "fi": "Piilota aiemmat haut",
                    "fr": "Masquer les recherches précédentes",
                    "de": "Vorherige Suchen ausblenden",
                    "el": "Απόκρυψη προηγούμενων αναζητήσεων",
                    "he": "הסתר חיפושים קודמים",
                    "hi": "पिछली खोजें छिपाएँ",
                    "hu": "Korábbi keresések elrejtése",
                    "id": "Sembunyikan Pencarian Sebelumnya",
                    "it": "Nascondi ricerche precedenti",
                    "ja": "以前の検索を非表示にする",
                    "ko": "이전 검색 숨기기",
                    "ms": "Sembunyikan Carian Sebelumnya",
                    "nb": "Skjul tidligere søk",
                    "pl": "Ukryj poprzednie wyszukiwania",
                    "pt": "Ocultar pesquisas anteriores",
                    "ro": "Ascunde căutările anterioare",
                    "ru": "Скрыть предыдущие поиски",
                    "sk": "Skryť predchádzajúce vyhľadávania",
                    "es": "Ocultar búsquedas anteriores",
                    "sv": "Dölj tidigare sökningar",
                    "th": "ซ่อนการค้นหาก่อนหน้า",
                    "tr": "Önceki Aramaları Gizle",
                    "uk": "Приховати попередні пошуки",
                    "vi": "Ẩn các tìm kiếm trước đó"
                  },
                id: "untrap_search_bar_hide_previous_searches",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء زر 'البحث الصوتي'",
                    "ca": "Amaga el botó 'Cerca per veu'",
                    "zh-CN": "隐藏“语音搜索”按钮",
                    "zh-TW": "隱藏「語音搜尋」按鈕",
                    "hr": "Sakrij gumb 'Glasovno pretraživanje'",
                    "cs": "Skrýt tlačítko „Hlasové vyhledávání“",
                    "da": "Skjul knappen 'Stemmesøgning'",
                    "nl": "Knop 'Gesproken zoekopdracht' verbergen",
                    "en": "Hide 'Voice Search' Button",
                    "fi": "Piilota 'Puhehaku' -painike",
                    "fr": "Masquer le bouton « Recherche vocale »",
                    "de": "Schaltfläche „Sprachsuche“ ausblenden",
                    "el": "Απόκρυψη του κουμπιού 'Φωνητική αναζήτηση'",
                    "he": "הסתר את לחצן 'חיפוש קולי'",
                    "hi": "'ध्वनि खोज' बटन छिपाएँ",
                    "hu": "A „Hangalapú keresés” gomb elrejtése",
                    "id": "Sembunyikan Tombol 'Pencarian Suara'",
                    "it": "Nascondi il pulsante 'Ricerca vocale'",
                    "ja": "「音声検索」ボタンを非表示にする",
                    "ko": "'음성검색' 버튼 숨기기",
                    "ms": "Sembunyikan Butang 'Carian Suara'",
                    "nb": "Skjul 'Stemmesøk'-knappen",
                    "pl": "Ukryj przycisk „Wyszukiwanie głosowe”",
                    "pt": "Ocultar o botão 'Pesquisa por voz'",
                    "ro": "Ascundeți butonul „Căutare vocală”",
                    "ru": "Скрыть кнопку «Голосовой поиск»",
                    "sk": "Skryť tlačidlo „Hlasové vyhľadávanie“",
                    "es": "Ocultar el botón 'Búsqueda por voz'",
                    "sv": "Dölj knappen 'Röstsökning'",
                    "th": "ซ่อนปุ่ม 'ค้นหาด้วยเสียง'",
                    "tr": "'Sesli Arama' Düğmesini Gizle",
                    "uk": "Сховати кнопку «Голосовий пошук»",
                    "vi": "Ẩn nút 'Tìm kiếm bằng giọng nói'"
                  },
                id: "untrap_header_hide_voice_search_button",
                defaultValue: false
            }
        ]
    }
]

const headerMobileGroups_Logo = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الشعار",
            "ca": "Amaga el logotip",
            "zh-CN": "隐藏标志",
            "zh-TW": "隱藏標誌",
            "hr": "Sakrij logotip",
            "cs": "Skrýt logo",
            "da": "Skjul logo",
            "nl": "Logo verbergen",
            "en": "Hide Logo",
            "fi": "Piilota logo",
            "fr": "Masquer le logo",
            "de": "Logo ausblenden",
            "el": "Απόκρυψη λογότυπου",
            "he": "הסתר לוגו",
            "hi": "लोगो छिपाएँ",
            "hu": "Logó elrejtése",
            "id": "Sembunyikan Logo",
            "it": "Nascondi logo",
            "ja": "ロゴを隠す",
            "ko": "로고 숨기기",
            "ms": "Sembunyikan Logo",
            "nb": "Skjul logo",
            "pl": "Ukryj logo",
            "pt": "Ocultar logotipo",
            "ro": "Ascunde sigla",
            "ru": "Скрыть логотип",
            "sk": "Skryť logo",
            "es": "Ocultar logotipo",
            "sv": "Dölj logotyp",
            "th": "ซ่อนโลโก้",
            "tr": "Logoyu Gizle",
            "uk": "Приховати логотип",
            "vi": "Ẩn biểu tượng"
          },
        id: "untrap_header_hide_logo",
        defaultValue: false,
        childOffOptions: [
            {
                type: "checkbox",
                name: {
                    "ar": "تعطيل رابط الشعار",
                    "ca": "Desactiva l'enllaç del logotip",
                    "zh-CN": "禁用徽标链接",
                    "zh-TW": "禁用徽標連結",
                    "hr": "Onemogući vezu s logotipom",
                    "cs": "Zakázat odkaz na logo",
                    "da": "Deaktiver logolink",
                    "nl": "Schakel Logolink uit",
                    "en": "Disable Logo Link",
                    "fi": "Poista logolinkki käytöstä",
                    "fr": "Désactiver le lien du logo",
                    "de": "Logo-Link deaktivieren",
                    "el": "Απενεργοποιήστε τη σύνδεση λογότυπου",
                    "he": "השבת קישור לוגו",
                    "hi": "लोगो लिंक अक्षम करें",
                    "hu": "Logo Link letiltása",
                    "id": "Nonaktifkan Tautan Logo",
                    "it": "Disabilita collegamento logo",
                    "ja": "ロゴリンクを無効にする",
                    "ko": "로고 링크 비활성화",
                    "ms": "Lumpuhkan Pautan Logo",
                    "nb": "Deaktiver logokobling",
                    "pl": "Wyłącz łącze do logo",
                    "pt": "Desativar link do logotipo",
                    "ro": "Dezactivați linkul pentru logo",
                    "ru": "Отключить ссылку на логотип",
                    "sk": "Zakázať odkaz na logo",
                    "es": "Deshabilitar enlace de logotipo",
                    "sv": "Inaktivera logotyplänk",
                    "th": "ปิดการใช้งานลิงค์โลโก้",
                    "tr": "Logo Bağlantısını Devre Dışı Bırak",
                    "uk": "Вимкнути посилання на логотип",
                    "vi": "Vô hiệu hóa liên kết logo"
                  },
                id: "untrap_header_disable_logo_link",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء الكلمة في الشعار",
                    "ca": "Amaga la paraula al logotip",
                    "zh-CN": "隐藏徽标中的文字",
                    "zh-TW": "隱藏徽標中的文字",
                    "hr": "Sakrij riječ u logotipu",
                    "cs": "Skrýt slovo v logu",
                    "da": "Skjul ord i logoet",
                    "nl": "Woord in logo verbergen",
                    "en": "Hide Word in Logo",
                    "fi": "Piilota Word logossa",
                    "fr": "Masquer le mot dans le logo",
                    "de": "Wort im Logo ausblenden",
                    "el": "Απόκρυψη του Word στο λογότυπο",
                    "he": "הסתר את Word בלוגו",
                    "hi": "लोगो में शब्द छिपाएँ",
                    "hu": "Szó elrejtése a logóban",
                    "id": "Sembunyikan Kata di Logo",
                    "it": "Nascondi la parola nel logo",
                    "ja": "ロゴ内の単語を非表示にする",
                    "ko": "로고에 단어 숨기기",
                    "ms": "Sembunyikan Word dalam Logo",
                    "nb": "Skjul Word i logoen",
                    "pl": "Ukryj słowo w logo",
                    "pt": "Ocultar palavra no logotipo",
                    "ro": "Ascundeți cuvântul în logo",
                    "ru": "Скрыть слово в логотипе",
                    "sk": "Skryť slovo v logu",
                    "es": "Ocultar palabra en el logotipo",
                    "sv": "Göm Word i logotypen",
                    "th": "ซ่อนคำในโลโก้",
                    "tr": "Logodaki Kelimeyi Gizle",
                    "uk": "Приховати слово в логотипі",
                    "vi": "Ẩn từ trong Logo"
                  },
                id: "untrap_header_hide_logo_wordmark",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "شعار التدرج الرمادي",
                    "ca": "Logotip en escala de grisos",
                    "zh-CN": "灰度标志",
                    "zh-TW": "灰階標誌",
                    "hr": "Logo u sivim tonovima",
                    "cs": "Logo ve stupních šedi",
                    "da": "Logo i gråtoner",
                    "nl": "Grijswaardenlogo",
                    "en": "Grayscale Logo",
                    "fi": "Harmaasävy logo",
                    "fr": "Logo en niveaux de gris",
                    "de": "Graustufen-Logo",
                    "el": "Λογότυπο σε κλίμακα του γκρι",
                    "he": "לוגו בגווני אפור",
                    "hi": "ग्रेस्केल लोगो",
                    "hu": "Szürkeárnyalatos logó",
                    "id": "Logo Skala Abu-Abu",
                    "it": "Logo in scala di grigi",
                    "ja": "グレースケールのロゴ",
                    "ko": "그레이스케일 로고",
                    "ms": "Logo Skala Kelabu",
                    "no": "Gråtonelogo",
                    "pl": "Logo w skali szarości",
                    "pt": "Logotipo em tons de cinza",
                    "ro": "Logo în tonuri de gri",
                    "ru": "Логотип в оттенках серого",
                    "sk": "Logo v odtieňoch šedej",
                    "es": "Logotipo en escala de grises",
                    "sv": "Gråskala logotyp",
                    "th": "โลโก้ระดับสีเทา",
                    "tr": "Gri tonlamalı Logo",
                    "uk": "Логотип у відтінках сірого",
                    "vi": "Logo thang độ xám"
                  },
                id: "untrap_header_grayscale_logo",
                defaultValue: false
            }
        ]
    }
]

const headerMobileGroups_Buttons = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'تصفية'",
            "ca": "Amaga el botó 'Filtre'",
            "zh-CN": "隐藏“过滤器”按钮",
            "zh-TW": "隱藏“過濾器”按鈕",
            "hr": "Sakrij gumb 'Filtar'",
            "cs": "Skrýt tlačítko 'Filtr'",
            "da": "Skjul knappen 'Filter'",
            "nl": "Knop 'Filter' verbergen",
            "en": "Hide 'Filter' Button",
            "fi": "Piilota 'Suodatin'-painike",
            "fr": "Masquer le bouton « Filtre »",
            "de": "Schaltfläche „Filter“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Φίλτρο'",
            "he": "הסתר את לחצן 'מסנן'",
            "hi": "'फ़िल्टर' बटन छिपाएँ",
            "hu": "A „Szűrő” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Filter'",
            "it": "Nascondi il pulsante 'Filtro'",
            "ja": "「フィルター」ボタンを非表示にする",
            "ko": "'필터' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Penapis'",
            "nb": "Skjul 'Filter'-knappen",
            "pl": "Ukryj przycisk „Filtruj”",
            "pt": "Ocultar botão 'Filtro'",
            "ro": "Ascundeți butonul „Filtrare”",
            "ru": "Скрыть кнопку «Фильтр»",
            "sk": "Skryť tlačidlo 'Filter'",
            "es": "Ocultar el botón 'Filtro'",
            "sv": "Dölj 'Filter'-knappen",
            "th": "ซ่อนปุ่ม 'ตัวกรอง'",
            "tr": "'Filtre' Düğmesini Gizle",
            "uk": "Сховати кнопку «Фільтр»",
            "vi": "Ẩn nút 'Bộ lọc'"
          },
        id: "untrap_header_hide_filter_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء زر 'القائمة'",
            "ca": "Amaga el botó 'Menú'",
            "zh-CN": "隐藏“菜单”按钮",
            "zh-TW": "隱藏“選單”按鈕",
            "hr": "Sakrij gumb 'Izbornik'",
            "cs": "Skrýt tlačítko 'Menu'",
            "da": "Skjul 'Menu'-knap",
            "nl": "Knop 'Menu' verbergen",
            "en": "Hide 'Menu' Button",
            "fi": "Piilota 'Valikko'-painike",
            "fr": "Masquer le bouton « Menu »",
            "de": "Schaltfläche „Menü“ ausblenden",
            "el": "Απόκρυψη κουμπιού 'Μενού'",
            "he": "הסתר את לחצן 'תפריט'",
            "hi": "'मेनू' बटन छिपाएँ",
            "hu": "A „Menü” gomb elrejtése",
            "id": "Sembunyikan Tombol 'Menu'",
            "it": "Nascondi il pulsante 'Menu'",
            "ja": "「メニュー」ボタンを隠す",
            "ko": "'메뉴' 버튼 숨기기",
            "ms": "Sembunyikan Butang 'Menu'",
            "nb": "Skjul 'Meny'-knappen",
            "pl": "Ukryj przycisk „Menu”",
            "pt": "Ocultar botão 'Menu'",
            "ro": "Ascundeți butonul „Meniu”",
            "ru": "Скрыть кнопку «Меню»",
            "sk": "Skryť tlačidlo 'Menu'",
            "es": "Ocultar el botón 'Menú'",
            "sv": "Dölj 'Meny'-knappen",
            "th": "ซ่อนปุ่ม 'เมนู'",
            "tr": "'Menü' Düğmesini Gizle",
            "uk": "Приховати кнопку «Меню»",
            "vi": "Ẩn nút 'Menu'"
          },
        id: "untrap_header_hide_menu_button",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الصورة الرمزية",
            "ca": "Amaga l'avatar",
            "zh-CN": "隐藏头像",
            "zh-TW": "隱藏頭像",
            "hr": "Sakrij avatar",
            "cs": "Skrýt Avatara",
            "da": "Skjul Avatar",
            "nl": "Avatar verbergen",
            "en": "Hide Avatar",
            "fi": "Piilota Avatar",
            "fr": "Masquer l'avatar",
            "de": "Avatar ausblenden",
            "el": "Απόκρυψη Avatar",
            "he": "הסתר אווטאר",
            "hi": "अवतार छिपाएँ",
            "hu": "Avatar elrejtése",
            "id": "Sembunyikan Avatar",
            "it": "Nascondi l'avatar",
            "ja": "アバターを隠す",
            "ko": "아바타 숨기기",
            "ms": "Sembunyikan Avatar",
            "nb": "Skjul Avatar",
            "pl": "Ukryj awatara",
            "pt": "Ocultar avatar",
            "ro": "Ascundeți avatarul",
            "ru": "Скрыть аватар",
            "sk": "Skryť Avatara",
            "es": "Ocultar avatar",
            "sv": "Göm Avatar",
            "th": "ซ่อนอวตาร",
            "tr": "Avatarı Gizle",
            "uk": "Приховати аватар",
            "vi": "Ẩn hình đại diện"
          },
        id: "untrap_header_hide_button_avatar",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "الصورة الرمزية ذات التدرج الرمادي",
            "ca": "Avatar en escala de grisos",
            "zh-CN": "灰度头像",
            "zh-TW": "灰階頭像",
            "hr": "Avatar u sivim tonovima",
            "cs": "Avatar ve stupních šedi",
            "da": "Avatar i gråtoner",
            "nl": "Grijswaardenavatar",
            "en": "Grayscale Avatar",
            "fi": "Harmaasävy Avatar",
            "fr": "Avatar en niveaux de gris",
            "de": "Graustufen-Avatar",
            "el": "Avatar σε κλίμακα του γκρι",
            "he": "אוואטר בגווני אפור",
            "hi": "ग्रेस्केल अवतार",
            "hu": "Szürkeárnyalatos Avatar",
            "id": "Avatar Skala Abu-Abu",
            "it": "Avatar in scala di grigi",
            "ja": "グレースケールのアバター",
            "ko": "그레이스케일 아바타",
            "ms": "Avatar Skala Kelabu",
            "nb": "Avatar i gråtoner",
            "pl": "Awatar w skali szarości",
            "pt": "Avatar em tons de cinza",
            "ro": "Avatar în tonuri de gri",
            "ru": "Аватар в оттенках серого",
            "sk": "Avatar v odtieňoch sivej",
            "es": "Avatar en escala de grises",
            "sv": "Avatar i gråskala",
            "th": "อวาตาร์ระดับสีเทา",
            "tr": "Gri Tonlamalı Avatar",
            "uk": "Аватар у відтінках сірого",
            "vi": "Hình đại diện thang độ xám"
          },
        id: "untrap_header_grayscale_button_avatar",
        defaultValue: false
    },
]

const headerMobileGroups_Other = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الرأس",
            "ca": "Amaga la capçalera",
            "zh-CN": "隐藏标题",
            "zh-TW": "隱藏標題",
            "hr": "Sakrij zaglavlje",
            "cs": "Skrýt záhlaví",
            "da": "Skjul overskrift",
            "nl": "Koptekst verbergen",
            "en": "Hide Header",
            "fi": "Piilota otsikko",
            "fr": "Masquer l'en-tête",
            "de": "Kopfzeile ausblenden",
            "el": "Απόκρυψη κεφαλίδας",
            "he": "הסתר כותרת",
            "hi": "हेडर छुपाएं",
            "hu": "Fejléc elrejtése",
            "id": "Sembunyikan Tajuk",
            "it": "Nascondi intestazione",
            "ja": "ヘッダーを非表示にする",
            "ko": "헤더 숨기기",
            "ms": "Sembunyikan Pengepala",
            "nb": "Skjul topptekst",
            "pl": "Ukryj nagłówek",
            "pt": "Ocultar cabeçalho",
            "ro": "Ascunde antetul",
            "ru": "Скрыть заголовок",
            "sk": "Skryť hlavičku",
            "es": "Ocultar encabezado",
            "sv": "Dölj sidhuvud",
            "th": "ซ่อนส่วนหัว",
            "tr": "Başlığı Gizle",
            "uk": "Приховати заголовок",
            "vi": "Ẩn tiêu đề"
          },
        id: "untrap_header_hide_top_header",
        defaultValue: false
    }
]


// MARK: - Builder

// Desktop

const headerDesktopGroups = [
    
    {
        groupName: {
            "ar": "شريط البحث",
            "ca": "Barra de cerca",
            "zh-CN": "搜索栏",
            "zh-TW": "搜尋欄",
            "hr": "Traka za pretraživanje",
            "cs": "Panel vyhledávání",
            "da": "Søgelinje",
            "nl": "Zoekbalk",
            "en": "Search Bar",
            "fi": "Hakupalkki",
            "fr": "Barre de recherche",
            "de": "Suchleiste",
            "el": "Μπαρα αναζήτησης",
            "he": "סרגל החיפוש",
            "hi": "खोज पट्टी",
            "hu": "Kereső sáv",
            "id": "Bilah Pencarian",
            "it": "Barra di ricerca",
            "ja": "検索バー",
            "ko": "검색 창",
            "ms": "Bar Carian",
            "nb": "Søkelinje",
            "pl": "Pasek wyszukiwania",
            "pt": "Barra de pesquisa",
            "ro": "Bara de căutare",
            "ru": "Панель поиска",
            "sk": "Panel vyhľadávania",
            "es": "Barra de búsqueda",
            "sv": "Sökruta",
            "th": "แถบค้นหา",
            "tr": "Arama çubuğu",
            "uk": "Панель пошуку",
            "vi": "Thanh tìm kiếm"
          },
        groupId: "searchBar",
        parentCategoryId: "header",
        options: headerDesktopGroups_SearchBar
    },
    {
        groupName: {
            "ar": "شعار",
            "ca": "Logotip",
            "zh-CN": "标识",
            "zh-TW": "標識",
            "hr": "Logo",
            "cs": "Logo",
            "da": "Logo",
            "nl": "Logo",
            "en": "Logo",
            "fi": "Logo",
            "fr": "Logo",
            "de": "Logo",
            "el": "Λογότυπο",
            "he": "סֵמֶל",
            "hi": "प्रतीक चिन्ह",
            "hu": "Logó",
            "id": "Logo",
            "it": "Logo",
            "ja": "ロゴ",
            "ko": "심벌 마크",
            "ms": "Logo",
            "nb": "Logo",
            "pl": "Logo",
            "pt": "Logotipo",
            "ro": "Siglă",
            "ru": "Логотип",
            "sk": "Logo",
            "es": "Logo",
            "sv": "Logotyp",
            "th": "โลโก้",
            "tr": "Logo",
            "uk": "Логотип",
            "vi": "Logo"
          },
        groupId: "logo",
        parentCategoryId: "header",
        options: headerDesktopGroups_Logo
    },
    {
        groupName: {
            "ar": "أزرار",
            "ca": "Botons",
            "zh-CN": "纽扣",
            "zh-TW": "羈扣",
            "hr": "Gumbi",
            "cs": "Tlačítka",
            "da": "Knapper",
            "nl": "Toetsen",
            "en": "Buttons",
            "fi": "Painikkeet",
            "fr": "Boutons",
            "de": "Tasten",
            "el": "Κουμπιά",
            "he": "כפתורים",
            "hi": "बटन",
            "hu": "Gombok",
            "id": "Tombol",
            "it": "Pulsanti",
            "ja": "ボタン",
            "ko": "버튼",
            "ms": "Butang",
            "nb": "Knapper",
            "pl": "Guziki",
            "pt": "Botões",
            "ro": "Butoane",
            "ru": "Кнопки",
            "sk": "Tlačidlá",
            "es": "Botones",
            "sv": "Knappar",
            "th": "ปุ่ม",
            "tr": "Düğmeler",
            "uk": "Кнопки",
            "vi": "Nút"
          },
        groupId: "buttons",
        parentCategoryId: "header",
        options: headerDesktopGroups_Buttons
    },
    {
        groupName: {
            "ar": "آحرون",
            "ca": "Altres",
            "zh-CN": "其他的",
            "zh-TW": "其他的",
            "hr": "Drugi",
            "cs": "Ostatní",
            "da": "Andre",
            "nl": "Anderen",
            "en": "Others",
            "fi": "Muut",
            "fr": "Autres",
            "de": "Andere",
            "el": "Οι υπολοιποι",
            "he": "אחרים",
            "hi": "अन्य",
            "hu": "Mások",
            "id": "Yang lain",
            "it": "Altri",
            "ja": "その他",
            "ko": "기타",
            "ms": "Lain-lain",
            "nb": "Andre",
            "pl": "Inni",
            "pt": "Outros",
            "ro": "Alții",
            "ru": "Другие",
            "sk": "Iní",
            "es": "Otros",
            "sv": "Andra",
            "th": "คนอื่น",
            "tr": "Diğerleri",
            "uk": "Інші",
            "vi": "Người khác"
          },
        groupId: "other",
        parentCategoryId: "header",
        options: headerDesktopGroups_Other
    }
];

// Mobile

const headerMobileGroups = [
    {
        groupName: {
            "ar": "شريط البحث",
            "ca": "Barra de cerca",
            "zh-CN": "搜索栏",
            "zh-TW": "搜尋欄",
            "hr": "Traka za pretraživanje",
            "cs": "Panel vyhledávání",
            "da": "Søgelinje",
            "nl": "Zoekbalk",
            "en": "Search Bar",
            "fi": "Hakupalkki",
            "fr": "Barre de recherche",
            "de": "Suchleiste",
            "el": "Μπαρα αναζήτησης",
            "he": "סרגל החיפוש",
            "hi": "खोज पट्टी",
            "hu": "Kereső sáv",
            "id": "Bilah Pencarian",
            "it": "Barra di ricerca",
            "ja": "検索バー",
            "ko": "검색 창",
            "ms": "Bar Carian",
            "nb": "Søkelinje",
            "pl": "Pasek wyszukiwania",
            "pt": "Barra de pesquisa",
            "ro": "Bara de căutare",
            "ru": "Панель поиска",
            "sk": "Panel vyhľadávania",
            "es": "Barra de búsqueda",
            "sv": "Sökruta",
            "th": "แถบค้นหา",
            "tr": "Arama çubuğu",
            "uk": "Панель пошуку",
            "vi": "Thanh tìm kiếm"
          },
        groupId: "searchBar",
        parentCategoryId: "header",
        options: headerMobileGroups_SearchBar
    },
    {
        groupName: {
            "ar": "شعار",
            "ca": "Logotip",
            "zh-CN": "标识",
            "zh-TW": "標識",
            "hr": "Logo",
            "cs": "Logo",
            "da": "Logo",
            "nl": "Logo",
            "en": "Logo",
            "fi": "Logo",
            "fr": "Logo",
            "de": "Logo",
            "el": "Λογότυπο",
            "he": "סֵמֶל",
            "hi": "प्रतीक चिन्ह",
            "hu": "Logó",
            "id": "Logo",
            "it": "Logo",
            "ja": "ロゴ",
            "ko": "심벌 마크",
            "ms": "Logo",
            "nb": "Logo",
            "pl": "Logo",
            "pt": "Logotipo",
            "ro": "Siglă",
            "ru": "Логотип",
            "sk": "Logo",
            "es": "Logo",
            "sv": "Logotyp",
            "th": "โลโก้",
            "tr": "Logo",
            "uk": "Логотип",
            "vi": "Logo"
          },
        groupId: "logo",
        parentCategoryId: "header",
        options: headerMobileGroups_Logo
    },
    {
        groupName: {
            "ar": "أزرار",
            "ca": "Botons",
            "zh-CN": "纽扣",
            "zh-TW": "羈扣",
            "hr": "Gumbi",
            "cs": "Tlačítka",
            "da": "Knapper",
            "nl": "Toetsen",
            "en": "Buttons",
            "fi": "Painikkeet",
            "fr": "Boutons",
            "de": "Tasten",
            "el": "Κουμπιά",
            "he": "כפתורים",
            "hi": "बटन",
            "hu": "Gombok",
            "id": "Tombol",
            "it": "Pulsanti",
            "ja": "ボタン",
            "ko": "버튼",
            "ms": "Butang",
            "nb": "Knapper",
            "pl": "Guziki",
            "pt": "Botões",
            "ro": "Butoane",
            "ru": "Кнопки",
            "sk": "Tlačidlá",
            "es": "Botones",
            "sv": "Knappar",
            "th": "ปุ่ม",
            "tr": "Düğmeler",
            "uk": "Кнопки",
            "vi": "Nút"
          },
        groupId: "buttons",
        parentCategoryId: "header",
        options: headerMobileGroups_Buttons
    },
    {
        groupName: {
            "ar": "آحرون",
            "ca": "Altres",
            "zh-CN": "其他的",
            "zh-TW": "其他的",
            "hr": "Drugi",
            "cs": "Ostatní",
            "da": "Andre",
            "nl": "Anderen",
            "en": "Others",
            "fi": "Muut",
            "fr": "Autres",
            "de": "Andere",
            "el": "Οι υπολοιποι",
            "he": "אחרים",
            "hi": "अन्य",
            "hu": "Mások",
            "id": "Yang lain",
            "it": "Altri",
            "ja": "その他",
            "ko": "기타",
            "ms": "Lain-lain",
            "nb": "Andre",
            "pl": "Inni",
            "pt": "Outros",
            "ro": "Alții",
            "ru": "Другие",
            "sk": "Iní",
            "es": "Otros",
            "sv": "Andra",
            "th": "คนอื่น",
            "tr": "Diğerleri",
            "uk": "Інші",
            "vi": "Người khác"
          },
        groupId: "other",
        parentCategoryId: "header",
        options: headerMobileGroups_Other
    }
]
