// MARK: - Desktop Groups

const youPageDesktopGroups_Sections = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الصورة الرمزية الخاصة بك",
            "ca": "Amaga el teu avatar",
            "zh-CN": "隐藏你的头像",
            "zh-TW": "隱藏你的頭像",
            "hr": "Sakrij svoj avatar",
            "cs": "Skryjte svého avatara",
            "da": "Skjul din avatar",
            "nl": "Verberg je avatar",
            "en": "Hide Your Avatar",
            "fi": "Piilota avatarisi",
            "fr": "Cachez votre avatar",
            "de": "Verstecke deinen Avatar",
            "el": "Απόκρυψη του Avatar σας",
            "he": "הסתר את הדמות שלך",
            "hi": "अपना अवतार छुपाएं",
            "hu": "Rejtsd el az Avatarod",
            "id": "Sembunyikan Avatar Anda",
            "it": "Nascondi il tuo avatar",
            "ja": "アバターを隠す",
            "ko": "아바타 숨기기",
            "ms": "Sembunyikan Avatar Anda",
            "nb": "Skjul avataren din",
            "pl": "Ukryj swój awatar",
            "pt": "Esconda seu avatar",
            "ro": "Ascunde-ți avatarul",
            "ru": "Скрыть свой аватар",
            "sk": "Skryte svojho avatara",
            "es": "Oculta tu avatar",
            "sv": "Göm din avatar",
            "th": "ซ่อนอวตารของคุณ",
            "tr": "Avatarınızı Gizleyin",
            "uk": "Приховати свій аватар",
            "vi": "Ẩn hình đại diện của bạn"
          },
        id: "untrap_you_page_hide_your_avatar",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'التاريخ'",
            "ca": "Amaga la secció 'Historial'",
            "zh-CN": "隐藏“历史”部分",
            "zh-TW": "隱藏「歷史」部分",
            "hr": "Sakrij odjeljak 'Povijest'",
            "cs": "Skrýt sekci 'Historie'",
            "da": "Skjul afsnittet 'Historie'",
            "nl": "Sectie 'Geschiedenis' verbergen",
            "en": "Hide 'History' Section",
            "fi": "Piilota 'Historia'-osio",
            "fr": "Masquer la section « Historique »",
            "de": "Abschnitt „Verlauf“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Ιστορικό'",
            "he": "הסתר קטע 'היסטוריה'",
            "hi": "'इतिहास' अनुभाग छिपाएँ",
            "hu": "Az „Előzmények” szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Riwayat'",
            "it": "Nascondi la sezione 'Cronologia'",
            "ja": "「履歴」セクションを非表示にする",
            "ko": "'기록' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Sejarah'",
            "nb": "Skjul 'Historikk'-delen",
            "pl": "Ukryj sekcję „Historia”",
            "pt": "Ocultar a seção 'Histórico'",
            "ro": "Ascundeți secțiunea „Istoric”",
            "ru": "Скрыть раздел «История»",
            "sk": "Skryť sekciu História",
            "es": "Ocultar la sección 'Historial'",
            "sv": "Dölj avsnittet 'Historik'",
            "th": "ซ่อนส่วน 'ประวัติ'",
            "tr": "'Geçmiş' Bölümünü Gizle",
            "uk": "Сховати розділ «Історія»",
            "vi": "Ẩn phần 'Lịch sử'"
          },
        id: "untrap_you_page_hide_section_history",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'المشاهدة لاحقًا'",
            "ca": "Amaga la secció 'Mira més tard'",
            "zh-CN": "隐藏“稍后观看”部分",
            "zh-TW": "隱藏“稍後觀看”部分",
            "hr": "Sakrij odjeljak 'Gledaj kasnije'",
            "cs": "Skrýt sekci Přehrát později",
            "da": "Skjul afsnittet 'Se senere'",
            "nl": "Sectie 'Later bekijken' verbergen",
            "en": "Hide 'Watch Later' Section",
            "fi": "Piilota Katso myöhemmin -osio",
            "fr": "Masquer la section « Regarder plus tard »",
            "de": "Abschnitt „Später ansehen“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Παρακολούθηση αργότερα'",
            "he": "הסתר את הקטע 'צפה מאוחר יותר'",
            "hi": "'बाद में देखें' अनुभाग छिपाएँ",
            "hu": "A „Megnézendő videók” szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Tonton Nanti'",
            "it": "Nascondi la sezione 'Guarda più tardi'",
            "ja": "「後で見る」セクションを非表示にする",
            "ko": "'나중에 보기' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Tonton Kemudian'",
            "nb": "Skjul 'Se senere'-delen",
            "pl": "Ukryj sekcję „Do obejrzenia”",
            "pt": "Ocultar a seção 'Assistir mais tarde'",
            "ro": "Ascundeți secțiunea „Vizionați mai târziu”",
            "ru": "Скрыть раздел «Посмотреть позже»",
            "sk": "Skryť sekciu Pozrieť neskôr",
            "es": "Ocultar la sección 'Ver más tarde'",
            "sv": "Dölj avsnittet 'Titta senare'",
            "th": "ซ่อนส่วน 'ดูภายหลัง'",
            "tr": "'Daha Sonra İzle' Bölümünü Gizle",
            "uk": "Сховати розділ «Переглянути пізніше»",
            "vi": "Ẩn phần 'Xem sau'"
          },
        id: "untrap_you_page_hide_section_watch_later",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'قوائم التشغيل'",
            "ca": "Amaga la secció 'Llistes de reproducció'",
            "zh-CN": "隐藏“播放列表”部分",
            "zh-TW": "隱藏“播放清單”部分",
            "hr": "Sakrij odjeljak 'Popisi za reprodukciju'",
            "cs": "Skrýt sekci „Seznamy skladeb“",
            "da": "Skjul sektionen 'Playlister'",
            "nl": "Sectie 'Afspeellijsten' verbergen",
            "en": "Hide 'Playlists' Section",
            "fi": "Piilota Soittolistat-osio",
            "fr": "Masquer la section « Playlists »",
            "de": "Abschnitt „Playlists“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Λίστες αναπαραγωγής'",
            "he": "הסתר את הקטע 'פלייליסטים'",
            "hi": "'प्लेलिस्ट' अनुभाग छिपाएँ",
            "hu": "A „Lejátszási listák” szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Daftar Putar'",
            "it": "Nascondi la sezione 'Playlist'",
            "ja": "「プレイリスト」セクションを非表示にする",
            "ko": "'재생 목록' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Senarai Main'",
            "nb": "Skjul delen 'Spillelister'",
            "pl": "Ukryj sekcję „Playlisty”",
            "pt": "Ocultar a seção 'Playlists'",
            "ro": "Ascundeți secțiunea „Playlisturi”",
            "ru": "Скрыть раздел «Плейлисты»",
            "sk": "Skryť sekciu Zoznamy skladieb",
            "es": "Ocultar la sección 'Listas de reproducción'",
            "sv": "Dölj avsnittet 'Spellistor'",
            "th": "ซ่อนส่วน 'เพลย์ลิสต์'",
            "tr": "'Oynatma Listeleri' Bölümünü Gizle",
            "uk": "Сховати розділ «Списки відтворення»",
            "vi": "Ẩn phần 'Danh sách phát'"
          },
        id: "untrap_you_page_hide_section_playlists",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'مقاطع الفيديو التي أعجبتني'",
            "ca": "Amaga la secció 'Vídeos que m'agraden'",
            "zh-CN": "隐藏“喜欢的视频”部分",
            "zh-TW": "隱藏「喜歡的影片」部分",
            "hr": "Sakrij odjeljak 'Sviđa mi se'",
            "cs": "Skrýt sekci „Oblíbená videa“",
            "da": "Skjul afsnittet 'Likede videoer'",
            "nl": "Verberg het gedeelte 'Gelikete video's'",
            "en": "Hide 'Liked Videos' Section",
            "fi": "Piilota 'Pidätyt videot' -osio",
            "fr": "Masquer la section « Vidéos aimées »",
            "de": "Abschnitt „Gefällt mir Videos“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Βίντεο που αρέσουν'",
            "he": "הסתר את הקטע 'סרטונים שאהבתי'",
            "hi": "'पसंद किए गए वीडियो' अनुभाग छुपाएं",
            "hu": "A „Kedvelt videók” szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Video yang Disukai'",
            "it": "Nascondi la sezione 'Video piaciuti'",
            "ja": "「いいね！」セクションを非表示にする",
            "ko": "'좋아요 표시한 동영상' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Video Suka'",
            "nb": "Skjul delen 'Likte videoer'",
            "pl": "Ukryj sekcję „Polubione filmy”",
            "pt": "Ocultar a seção 'Vídeos curtidos'",
            "ro": "Ascundeți secțiunea „Videoclipuri apreciate”",
            "ru": "Скрыть раздел «Понравившиеся видео»",
            "sk": "Skryť sekciu „Páči sa mi videá“",
            "es": "Ocultar la sección 'Videos que me gustan'",
            "sv": "Dölj avsnittet 'Gillade videor'",
            "th": "ซ่อนส่วน 'วิดีโอที่ชอบ'",
            "tr": "'Beğenilen Videolar' Bölümünü Gizle",
            "uk": "Сховати розділ «Сподобалися відео»",
            "vi": "Ẩn phần 'Video đã thích'"
          },
        id: "untrap_you_page_hide_section_liked_videos",
        defaultValue: false
    },
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء قسم 'مقاطعك'",
            "ca": "Amaga la secció 'Els teus clips'",
            "zh-CN": "隐藏“您的剪辑”部分",
            "zh-TW": "隱藏“您的剪輯”部分",
            "hr": "Sakrij odjeljak 'Vaši isječci'",
            "cs": "Skrýt sekci „Vaše klipy“",
            "da": "Skjul afsnittet 'Dine klip'",
            "nl": "Verberg het gedeelte 'Uw clips'",
            "en": "Hide 'Your Clips' Section",
            "fi": "Piilota 'Omat leikkeet' -osio",
            "fr": "Masquer la section « Vos clips »",
            "de": "Bereich „Deine Clips“ ausblenden",
            "el": "Απόκρυψη ενότητας 'Τα κλιπ σας'",
            "he": "הסתר את הקטע 'הקליפים שלך'",
            "hi": "'आपकी क्लिप्स' अनुभाग छिपाएँ",
            "hu": "A 'Saját klipek' szakasz elrejtése",
            "id": "Sembunyikan Bagian 'Klip Anda'",
            "it": "Nascondi la sezione 'I tuoi clip'",
            "ja": "「あなたのクリップ」セクションを非表示にする",
            "ko": "'내 클립' 섹션 숨기기",
            "ms": "Sembunyikan Bahagian 'Klip Anda'",
            "nb": "Skjul delen 'Dine klipp'",
            "pl": "Ukryj sekcję „Twoje klipy”",
            "pt": "Ocultar a seção 'Seus clipes'",
            "ro": "Ascundeți secțiunea „Clipurile dvs.”",
            "ru": "Скрыть раздел «Ваши клипы»",
            "sk": "Skryť sekciu „Vaše klipy“",
            "es": "Ocultar la sección 'Tus clips'",
            "sv": "Dölj avsnittet 'Dina klipp'",
            "th": "ซ่อนส่วน 'คลิปของคุณ'",
            "tr": "'Klipleriniz' Bölümünü Gizle",
            "uk": "Сховати розділ «Ваші кліпи»",
            "vi": "Ẩn phần 'Clip của bạn'"
          },
        id: "untrap_you_page_hide_section_your_clips",
        defaultValue: false
    }
];

// MARK: - Mobile Groups

const youPageMobileGroups_MyInfo = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء معلوماتي",
            "ca": "Amaga la meva informació",
            "zh-CN": "隐藏我的信息",
            "zh-TW": "隱藏我的訊息",
            "hr": "Sakrij moje podatke",
            "cs": "Skrýt moje informace",
            "da": "Skjul mine oplysninger",
            "nl": "Verberg mijn informatie",
            "en": "Hide My Info",
            "fi": "Piilota tietoni",
            "fr": "Masquer mes informations",
            "de": "Meine Informationen ausblenden",
            "el": "Απόκρυψη των πληροφοριών μου",
            "he": "הסתר את המידע שלי",
            "hi": "मेरी जानकारी छिपाएँ",
            "hu": "Saját adatok elrejtése",
            "id": "Sembunyikan Info Saya",
            "it": "Nascondi le mie informazioni",
            "ja": "私の情報を隠す",
            "ko": "내 정보 숨기기",
            "ms": "Sembunyikan Maklumat Saya",
            "no": "Skjul min informasjon",
            "pl": "Ukryj moje informacje",
            "pt": "Ocultar minhas informações",
            "ro": "Ascunde informațiile mele",
            "ru": "Скрыть мою информацию",
            "sk": "Skryť moje informácie",
            "es": "Ocultar mi información",
            "sv": "Dölj min information",
            "th": "ซ่อนข้อมูลของฉัน",
            "tr": "Bilgilerimi Gizle",
            "uk": "Приховати мою інформацію",
            "vi": "Ẩn thông tin của tôi"
          },
        id: "untrap_you_page_hide_my_info",
        defaultValue: false,
        childOffOptions: [
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء الصورة الرمزية",
                    "ca": "Amaga l'avatar",
                    "zh-CN": "隐藏头像",
                    "zh-TW": "隱藏頭像",
                    "hr": "Sakrij avatar",
                    "cs": "Skrýt Avatara",
                    "da": "Skjul Avatar",
                    "nl": "Avatar verbergen",
                    "en": "Hide Avatar",
                    "fi": "Piilota Avatar",
                    "fr": "Masquer l'avatar",
                    "de": "Avatar ausblenden",
                    "el": "Απόκρυψη Avatar",
                    "he": "הסתר אווטאר",
                    "hi": "अवतार छिपाएँ",
                    "hu": "Avatar elrejtése",
                    "id": "Sembunyikan Avatar",
                    "it": "Nascondi l'avatar",
                    "ja": "アバターを隠す",
                    "ko": "아바타 숨기기",
                    "ms": "Sembunyikan Avatar",
                    "no": "Skjul Avatar",
                    "pl": "Ukryj awatara",
                    "pt": "Ocultar avatar",
                    "ro": "Ascundeți avatarul",
                    "ru": "Скрыть аватар",
                    "sk": "Skryť Avatara",
                    "es": "Ocultar avatar",
                    "sv": "Göm Avatar",
                    "th": "ซ่อนอวตาร",
                    "tr": "Avatarı Gizle",
                    "uk": "Приховати аватар",
                    "vi": "Ẩn hình đại diện"
                  },
                id: "untrap_you_page_hide_account_avatar",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء اسم القناة",
                    "ca": "Amaga el nom del canal",
                    "zh-CN": "隐藏频道名称",
                    "zh-TW": "隱藏頻道名稱",
                    "hr": "Sakrij naziv kanala",
                    "cs": "Skrýt název kanálu",
                    "da": "Skjul kanalnavn",
                    "nl": "Kanaalnaam verbergen",
                    "en": "Hide Channel Name",
                    "fi": "Piilota kanavan nimi",
                    "fr": "Masquer le nom de la chaîne",
                    "de": "Kanalnamen ausblenden",
                    "el": "Απόκρυψη ονόματος καναλιού",
                    "he": "הסתר את שם הערוץ",
                    "hi": "चैनल का नाम छिपाएँ",
                    "hu": "Csatornanév elrejtése",
                    "id": "Sembunyikan Nama Saluran",
                    "it": "Nascondi nome canale",
                    "ja": "チャンネル名を隠す",
                    "ko": "채널 이름 숨기기",
                    "ms": "Sembunyikan Nama Saluran",
                    "no": "Skjul kanalnavn",
                    "pl": "Ukryj nazwę kanału",
                    "pt": "Ocultar nome do canal",
                    "ro": "Ascunde numele canalului",
                    "ru": "Скрыть название канала",
                    "sk": "Skryť názov kanála",
                    "es": "Ocultar nombre del canal",
                    "sv": "Dölj kanalnamn",
                    "th": "ซ่อนชื่อช่อง",
                    "tr": "Kanal Adını Gizle",
                    "uk": "Приховати назву каналу",
                    "vi": "Ẩn tên kênh"
                  },
                id: "untrap_you_page_hide_channel_name",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء معرف القناة",
                    "ca": "Amaga l'identificador del canal",
                    "zh-CN": "隐藏频道 ID",
                    "zh-TW": "隱藏頻道 ID",
                    "hr": "Sakrij ID kanala",
                    "cs": "Skrýt ID kanálu",
                    "da": "Skjul kanal-id",
                    "nl": "Kanaal-ID verbergen",
                    "en": "Hide Channel ID",
                    "fi": "Piilota kanavatunnus",
                    "fr": "Masquer l'identifiant de la chaîne",
                    "de": "Kanal-ID ausblenden",
                    "el": "Απόκρυψη αναγνωριστικού καναλιού",
                    "he": "הסתר מזהה ערוץ",
                    "hi": "चैनल आईडी छुपाएं",
                    "hu": "Csatornaazonosító elrejtése",
                    "id": "Sembunyikan ID Saluran",
                    "it": "Nascondi ID canale",
                    "ja": "チャンネルIDを隠す",
                    "ko": "채널 ID 숨기기",
                    "ms": "Sembunyikan ID Saluran",
                    "no": "Skjul kanal-ID",
                    "pl": "Ukryj identyfikator kanału",
                    "pt": "Ocultar ID do canal",
                    "ro": "Ascunde ID-ul canalului",
                    "ru": "Скрыть идентификатор канала",
                    "sk": "Skryť ID kanála",
                    "es": "Ocultar ID de canal",
                    "sv": "Dölj kanal-ID",
                    "th": "ซ่อนรหัสช่อง",
                    "tr": "Kanal Kimliğini Gizle",
                    "uk": "Приховати ідентифікатор каналу",
                    "vi": "Ẩn ID kênh"
                  },
                id: "untrap_you_page_hide_channel_id",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء زر 'عرض القناة'",
                    "ca": "Amaga el botó 'Mostra el canal'",
                    "zh-CN": "隐藏“查看频道”按钮",
                    "zh-TW": "隱藏「檢視頻道」按鈕",
                    "hr": "Sakrij gumb 'Prikaži kanal'",
                    "cs": "Skrýt tlačítko 'Zobrazit kanál'",
                    "da": "Skjul knappen 'Se kanal'",
                    "nl": "Knop 'Kanaal bekijken' verbergen",
                    "en": "Hide 'View Channel' Button",
                    "fi": "Piilota 'Näytä kanava' -painike",
                    "fr": "Masquer le bouton « Afficher la chaîne »",
                    "de": "Schaltfläche „Kanal anzeigen“ ausblenden",
                    "el": "Απόκρυψη του κουμπιού 'Προβολή καναλιού'",
                    "he": "הסתר את לחצן 'הצג ערוץ'",
                    "hi": "'चैनल देखें' बटन छिपाएँ",
                    "hu": "A „Csatorna megtekintése” gomb elrejtése",
                    "id": "Sembunyikan Tombol 'Lihat Saluran'",
                    "it": "Nascondi il pulsante 'Visualizza canale'",
                    "ja": "「チャンネルを表示」ボタンを非表示にする",
                    "ko": "'채널 보기' 버튼 숨기기",
                    "ms": "Sembunyikan Butang 'Lihat Saluran'",
                    "no": "Skjul 'Se kanal'-knappen",
                    "pl": "Ukryj przycisk „Wyświetl kanał”",
                    "pt": "Ocultar o botão 'Ver canal'",
                    "ro": "Ascundeți butonul „Vizualizare canal”",
                    "ru": "Скрыть кнопку «Просмотр канала»",
                    "sk": "Skryť tlačidlo „Zobraziť kanál“",
                    "es": "Ocultar el botón 'Ver canal'",
                    "sv": "Dölj 'Visa kanal'-knappen",
                    "th": "ซ่อนปุ่ม 'ดูช่อง'",
                    "tr": "'Kanalı Görüntüle' Düğmesini Gizle",
                    "uk": "Приховати кнопку «Переглянути канал»",
                    "vi": "Ẩn nút 'Xem kênh'"
                  },
                id: "untrap_you_page_hide_view_channel_button",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء زر 'تبديل الحساب'",
                    "ca": "Amaga el botó 'Canvia de compte'",
                    "zh-CN": "隐藏“切换帐户”按钮",
                    "zh-TW": "隱藏「切換帳戶」按鈕",
                    "hr": "Sakrij gumb 'Promijeni račun'",
                    "cs": "Skrýt tlačítko „Přepnout účet“",
                    "da": "Skjul knappen 'Skift konto'",
                    "nl": "Knop 'Account wisselen' verbergen",
                    "en": "Hide 'Switch Account' Button",
                    "fi": "Piilota 'Vaihda tiliä' -painike",
                    "fr": "Masquer le bouton « Changer de compte »",
                    "de": "Schaltfläche „Konto wechseln“ ausblenden",
                    "el": "Απόκρυψη του κουμπιού 'Αλλαγή λογαριασμού'",
                    "he": "הסתר את לחצן 'החלף חשבון'",
                    "hi": "'स्विच खाता' बटन छिपाएँ",
                    "hu": "A „Fiókváltás” gomb elrejtése",
                    "id": "Sembunyikan Tombol 'Ganti Akun'",
                    "it": "Nascondi il pulsante 'Cambia account'",
                    "ja": "「アカウントの切り替え」ボタンを非表示にする",
                    "ko": "'계정 전환' 버튼 숨기기",
                    "ms": "Sembunyikan Butang 'Tukar Akaun'",
                    "no": "Skjul 'Bytt konto'-knappen",
                    "pl": "Ukryj przycisk „Przełącz konto”",
                    "pt": "Ocultar o botão 'Alterar conta'",
                    "ro": "Ascundeți butonul „Schimbați contul”",
                    "ru": "Скрыть кнопку «Сменить учетную запись»",
                    "sk": "Skryť tlačidlo „Prepnúť účet“",
                    "es": "Ocultar el botón 'Cambiar de cuenta'",
                    "sv": "Dölj 'Byt konto'-knappen",
                    "th": "ซ่อนปุ่ม 'สลับบัญชี'",
                    "tr": "'Hesap Değiştir' Düğmesini Gizle",
                    "uk": "Приховати кнопку «Змінити обліковий запис»",
                    "vi": "Ẩn nút 'Chuyển tài khoản'"
                  },
                id: "untrap_you_page_hide_switch_account_button",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء زر 'حساب Google'",
                    "ca": "Amaga el botó 'Compte de Google'",
                    "zh-CN": "隐藏“Google 帐户”按钮",
                    "zh-TW": "隱藏「Google 帳戶」按鈕",
                    "hr": "Sakrij gumb 'Google račun'",
                    "cs": "Skrýt tlačítko „Účet Google“",
                    "da": "Skjul knappen 'Google-konto'",
                    "nl": "Knop 'Google-account' verbergen",
                    "en": "Hide 'Google Account' Button",
                    "fi": "Piilota Google-tili-painike",
                    "fr": "Masquer le bouton 'Compte Google'",
                    "de": "Schaltfläche „Google-Konto“ ausblenden",
                    "el": "Απόκρυψη του κουμπιού 'Λογαριασμός Google'",
                    "he": "הסתר את הלחצן 'חשבון גוגל'",
                    "hi": "'Google खाता' बटन छुपाएं",
                    "hu": "A „Google Fiók” gomb elrejtése",
                    "id": "Sembunyikan Tombol 'Akun Google'",
                    "it": "Nascondi il pulsante 'Account Google'",
                    "ja": "「Googleアカウント」ボタンを非表示にする",
                    "ko": "'Google 계정' 버튼 숨기기",
                    "ms": "Sembunyikan Butang 'Akaun Google'",
                    "no": "Skjul 'Google-konto'-knappen",
                    "pl": "Ukryj przycisk „Konto Google”",
                    "pt": "Ocultar o botão 'Conta do Google'",
                    "ro": "Ascundeți butonul „Cont Google”",
                    "ru": "Скрыть кнопку «Аккаунт Google»",
                    "sk": "Skryť tlačidlo „Účet Google“",
                    "es": "Ocultar el botón 'Cuenta de Google'",
                    "sv": "Dölj 'Google-konto'-knappen",
                    "th": "ซ่อนปุ่ม 'บัญชี Google'",
                    "tr": "'Google Hesabı' Düğmesini Gizle",
                    "uk": "Приховати кнопку «Обліковий запис Google»",
                    "vi": "Ẩn nút 'Tài khoản Google'"
                  },
                id: "untrap_you_page_hide_google_account_button",
                defaultValue: false
            }
        ]
    }
];

const youPageMobileGroups_Sections = [
    {
        type: "checkbox",
        name: {
            "ar": "إخفاء الأقسام",
            "ca": "Amaga les seccions",
            "zh-CN": "隐藏部分",
            "zh-TW": "隱藏部分",
            "hr": "Sakrij odjeljke",
            "cs": "Skrýt sekce",
            "da": "Skjul sektioner",
            "nl": "Secties verbergen",
            "en": "Hide Sections",
            "fi": "Piilota osiot",
            "fr": "Masquer les sections",
            "de": "Abschnitte ausblenden",
            "el": "Απόκρυψη ενοτήτων",
            "he": "הסתר קטעים",
            "hi": "अनुभाग छिपाएँ",
            "hu": "Szakaszok elrejtése",
            "id": "Sembunyikan Bagian",
            "it": "Nascondi sezioni",
            "ja": "セクションを非表示にする",
            "ko": "섹션 숨기기",
            "ms": "Sembunyikan Bahagian",
            "no": "Skjul seksjoner",
            "pl": "Ukryj sekcje",
            "pt": "Ocultar seções",
            "ro": "Ascundeți secțiuni",
            "ru": "Скрыть разделы",
            "sk": "Skryť sekcie",
            "es": "Ocultar secciones",
            "sv": "Göm sektioner",
            "th": "ซ่อนส่วนต่างๆ",
            "tr": "Bölümleri Gizle",
            "uk": "Приховати розділи",
            "vi": "Ẩn phần"
          },
        id: "untrap_you_page_hide_all_sections",
        defaultValue: false,
        childOffOptions: [
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء قسم 'التاريخ'",
                    "ca": "Amaga la secció 'Historial'",
                    "zh-CN": "隐藏“历史”部分",
                    "zh-TW": "隱藏「歷史」部分",
                    "hr": "Sakrij odjeljak 'Povijest'",
                    "cs": "Skrýt sekci 'Historie'",
                    "da": "Skjul afsnittet 'Historie'",
                    "nl": "Sectie 'Geschiedenis' verbergen",
                    "en": "Hide 'History' Section",
                    "fi": "Piilota 'Historia'-osio",
                    "fr": "Masquer la section « Historique »",
                    "de": "Abschnitt „Verlauf“ ausblenden",
                    "el": "Απόκρυψη ενότητας 'Ιστορικό'",
                    "he": "הסתר קטע 'היסטוריה'",
                    "hi": "'इतिहास' अनुभाग छिपाएँ",
                    "hu": "Az „Előzmények” szakasz elrejtése",
                    "id": "Sembunyikan Bagian 'Riwayat'",
                    "it": "Nascondi la sezione 'Cronologia'",
                    "ja": "「履歴」セクションを非表示にする",
                    "ko": "'기록' 섹션 숨기기",
                    "ms": "Sembunyikan Bahagian 'Sejarah'",
                    "nb": "Skjul 'Historikk'-delen",
                    "pl": "Ukryj sekcję „Historia”",
                    "pt": "Ocultar a seção 'Histórico'",
                    "ro": "Ascundeți secțiunea „Istoric”",
                    "ru": "Скрыть раздел «История»",
                    "sk": "Skryť sekciu História",
                    "es": "Ocultar la sección 'Historial'",
                    "sv": "Dölj avsnittet 'Historik'",
                    "th": "ซ่อนส่วน 'ประวัติ'",
                    "tr": "'Geçmiş' Bölümünü Gizle",
                    "uk": "Сховати розділ «Історія»",
                    "vi": "Ẩn phần 'Lịch sử'"
                  },
                id: "untrap_you_page_hide_section_history",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء قسم 'قوائم التشغيل'",
                    "ca": "Amaga la secció 'Llistes de reproducció'",
                    "zh-CN": "隐藏“播放列表”部分",
                    "zh-TW": "隱藏“播放清單”部分",
                    "hr": "Sakrij odjeljak 'Popisi za reprodukciju'",
                    "cs": "Skrýt sekci „Seznamy skladeb“",
                    "da": "Skjul sektionen 'Playlister'",
                    "nl": "Sectie 'Afspeellijsten' verbergen",
                    "en": "Hide 'Playlists' Section",
                    "fi": "Piilota Soittolistat-osio",
                    "fr": "Masquer la section « Playlists »",
                    "de": "Abschnitt „Playlists“ ausblenden",
                    "el": "Απόκρυψη ενότητας 'Λίστες αναπαραγωγής'",
                    "he": "הסתר את הקטע 'פלייליסטים'",
                    "hi": "'प्लेलिस्ट' अनुभाग छिपाएँ",
                    "hu": "A „Lejátszási listák” szakasz elrejtése",
                    "id": "Sembunyikan Bagian 'Daftar Putar'",
                    "it": "Nascondi la sezione 'Playlist'",
                    "ja": "「プレイリスト」セクションを非表示にする",
                    "ko": "'재생 목록' 섹션 숨기기",
                    "ms": "Sembunyikan Bahagian 'Senarai Main'",
                    "nb": "Skjul delen 'Spillelister'",
                    "pl": "Ukryj sekcję „Playlisty”",
                    "pt": "Ocultar a seção 'Playlists'",
                    "ro": "Ascundeți secțiunea „Playlisturi”",
                    "ru": "Скрыть раздел «Плейлисты»",
                    "sk": "Skryť sekciu Zoznamy skladieb",
                    "es": "Ocultar la sección 'Listas de reproducción'",
                    "sv": "Dölj avsnittet 'Spellistor'",
                    "th": "ซ่อนส่วน 'เพลย์ลิสต์'",
                    "tr": "'Oynatma Listeleri' Bölümünü Gizle",
                    "uk": "Сховати розділ «Списки відтворення»",
                    "vi": "Ẩn phần 'Danh sách phát'"
                  },
                id: "untrap_you_page_hide_section_playlists",
                defaultValue: false
            }
        ]
    }
];

const youPageMobileGroups_Buttons = [
    {
        type: "checkbox",
        name: {
            "ar": "أزرار اخفاء",
            "ca": "Oculta botons",
            "zh-CN": "隐藏按钮",
            "zh-TW": "隱藏按鈕",
            "hr": "Sakrij gumbe",
            "cs": "Skrýt tlačítka",
            "da": "Skjul knapper",
            "nl": "Knoppen verbergen",
            "en": "Hide Buttons",
            "fi": "Piilota painikkeet",
            "fr": "Masquer les boutons",
            "de": "Verstecken tasten",
            "el": "Απόκρυψη κουμπιών",
            "he": "הסתר כפתורים",
            "hi": "बटन छिपाएँ",
            "hu": "Gombok elrejtése",
            "id": "Sembunyikan Tombol",
            "it": "Nascondi pulsanti",
            "ja": "ボタンを隠す",
            "ko": "버튼 숨기기",
            "ms": "Sembunyikan Butang",
            "no": "Skjul knapper",
            "pl": "Ukryj przyciski",
            "pt": "Ocultar botões",
            "ro": "Ascunde butoanele",
            "ru": "Скрыть кнопки",
            "sk": "Skryť tlačidlá",
            "es": "Ocultar botones",
            "sv": "Dölj knappar",
            "th": "ซ่อนปุ่ม",
            "tr": "Düğmeleri gizle",
            "uk": "Приховати кнопки",
            "vi": "Ẩn nút"
          },
        id: "untrap_you_page_hide_footer_buttons",
        defaultValue: false,
        childOffOptions: [
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء زر 'مقاطع الفيديو الخاصة بك'",
                    "ca": "Amaga el botó 'Els teus vídeos'",
                    "zh-CN": "隐藏“您的视频”按钮",
                    "zh-TW": "隱藏“您的影片”按鈕",
                    "hr": "Sakrij gumb 'Vaši videozapisi'",
                    "cs": "Skrýt tlačítko „Vaše videa“",
                    "da": "Skjul knappen 'Dine videoer'",
                    "nl": "Verberg de knop 'Je video's'",
                    "en": "Hide 'Your Videos' Button",
                    "fi": "Piilota 'Omat videosi' -painike",
                    "fr": "Masquer le bouton « Vos vidéos »",
                    "de": "Schaltfläche „Deine Videos“ ausblenden",
                    "el": "Απόκρυψη του κουμπιού 'Τα βίντεό σας'",
                    "he": "הסתר את כפתור 'הסרטונים שלך'",
                    "hi": "'अपने वीडियो' बटन छुपाएं",
                    "hu": "A 'Saját videóid' gomb elrejtése",
                    "id": "Sembunyikan Tombol 'Video Anda'",
                    "it": "Nascondi il pulsante 'I tuoi video'",
                    "ja": "「あなたのビデオ」ボタンを非表示にする",
                    "ko": "'내 동영상' 버튼 숨기기",
                    "ms": "Sembunyikan Butang 'Video Anda'",
                    "no": "Skjul 'Dine videoer'-knappen",
                    "pl": "Ukryj przycisk „Twoje filmy”",
                    "pt": "Ocultar o botão 'Seus vídeos'",
                    "ro": "Ascunde butonul „Videoclipurile tale”",
                    "ru": "Скрыть кнопку «Ваши видео»",
                    "sk": "Skryť tlačidlo „Vaše videá“",
                    "es": "Ocultar el botón 'Tus vídeos'",
                    "sv": "Dölj knappen 'Dina videor'",
                    "th": "ซ่อนปุ่ม 'วิดีโอของคุณ'",
                    "tr": "'Videolarınız' Düğmesini Gizle",
                    "uk": "Приховати кнопку «Ваші відео»",
                    "vi": "Ẩn nút 'Video của bạn'"
                  },
                id: "untrap_you_page_hide_section_your_videos",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء زر 'أفلامك'",
                    "ca": "Amaga el botó 'Les teves pel·lícules'",
                    "zh-CN": "隐藏“您的电影”按钮",
                    "zh-TW": "隱藏“您的電影”按鈕",
                    "hr": "Sakrij gumb 'Vaši filmovi'",
                    "cs": "Skrýt tlačítko „Vaše filmy“",
                    "da": "Skjul knappen 'Dine film'",
                    "nl": "Knop 'Uw films' verbergen",
                    "en": "Hide 'Your Movies' Button",
                    "fi": "Piilota 'Omat elokuvat' -painike",
                    "fr": "Masquer le bouton « Vos films »",
                    "de": "Schaltfläche „Deine Filme“ ausblenden",
                    "el": "Απόκρυψη του κουμπιού 'Οι ταινίες σας'",
                    "he": "הסתר את לחצן 'הסרטים שלך'",
                    "hi": "'आपकी फिल्में' बटन छुपाएं",
                    "hu": "A „Saját filmek” gomb elrejtése",
                    "id": "Sembunyikan Tombol 'Film Anda'",
                    "it": "Nascondi il pulsante 'I tuoi film'",
                    "ja": "「あなたの映画」ボタンを非表示にする",
                    "ko": "'내 영화' 버튼 숨기기",
                    "ms": "Sembunyikan Butang 'Filem Anda'",
                    "no": "Skjul 'Dine filmer'-knappen",
                    "pl": "Ukryj przycisk „Twoje filmy”",
                    "pt": "Ocultar o botão 'Seus filmes'",
                    "ro": "Ascunde butonul „Filmele tale”",
                    "ru": "Скрыть кнопку «Ваши фильмы»",
                    "sk": "Skryť tlačidlo „Vaše filmy“",
                    "es": "Ocultar el botón 'Tus películas'",
                    "sv": "Dölj 'Dina filmer'-knappen",
                    "th": "ซ่อนปุ่ม 'ภาพยนตร์ของคุณ'",
                    "tr": "'Filmleriniz' Düğmesini Gizle",
                    "uk": "Приховати кнопку «Ваші фільми»",
                    "vi": "Ẩn nút 'Phim của bạn'"
                  },
                id: "untrap_you_page_hide_section_your_movies",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء زر 'الحصول على YouTube Premium'",
                    "ca": "Amaga el botó 'Obtén YouTube Premium'",
                    "zh-CN": "隐藏“获取 YouTube Premium”按钮",
                    "zh-TW": "隱藏「取得 YouTube Premium」按鈕",
                    "hr": "Sakrij gumb 'Nabavite YouTube Premium'",
                    "cs": "Skryjte tlačítko „Získat YouTube Premium“",
                    "da": "Skjul knappen 'Få YouTube Premium'",
                    "nl": "Verberg de knop 'Krijg YouTube Premium'",
                    "en": "Hide 'Get YouTube Premium' Button",
                    "fi": "Piilota Hanki YouTube Premium -painike",
                    "fr": "Masquer le bouton « Obtenir YouTube Premium »",
                    "de": "Schaltfläche „YouTube Premium herunterladen“ ausblenden",
                    "el": "Απόκρυψη του κουμπιού 'Λήψη YouTube Premium'",
                    "he": "הסתר את הלחצן 'קבל YouTube Premium'",
                    "hi": "'यूट्यूब प्रीमियम प्राप्त करें' बटन छुपाएं",
                    "hu": "A „YouTube Premium beszerzése” gomb elrejtése",
                    "id": "Sembunyikan Tombol 'Dapatkan YouTube Premium'",
                    "it": "Nascondi il pulsante 'Ottieni YouTube Premium'",
                    "ja": "「YouTube Premium を取得」ボタンを非表示にする",
                    "ko": "'YouTube Premium 가입' 버튼 숨기기",
                    "ms": "Sembunyikan Butang 'Dapatkan YouTube Premium'",
                    "no": "Skjul «Få YouTube Premium»-knappen",
                    "pl": "Ukryj przycisk „Pobierz YouTube Premium”",
                    "pt": "Ocultar o botão 'Obter YouTube Premium'",
                    "ro": "Ascundeți butonul „Obțineți YouTube Premium”",
                    "ru": "Скрыть кнопку «Получить YouTube Premium»",
                    "sk": "Skryť tlačidlo „Získať YouTube Premium“",
                    "es": "Ocultar el botón 'Obtener YouTube Premium'",
                    "sv": "Dölj 'Hämta YouTube Premium'-knappen",
                    "th": "ซ่อนปุ่ม 'รับ YouTube Premium'",
                    "tr": "'YouTube Premium'u Edinin' Düğmesini Gizle",
                    "uk": "Сховати кнопку «Отримати YouTube Premium»",
                    "vi": "Ẩn nút 'Tải YouTube Premium'"
                  },
                id: "untrap_you_page_hide_button_premium",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء زر 'المساعدة'",
                    "ca": "Amaga el botó 'Ajuda'",
                    "zh-CN": "隐藏“帮助”按钮",
                    "zh-TW": "隱藏「幫助」按鈕",
                    "hr": "Sakrij gumb 'Pomoć'",
                    "cs": "Skrýt tlačítko 'Nápověda'",
                    "da": "Skjul knappen 'Hjælp'",
                    "nl": "Knop 'Help' verbergen",
                    "en": "Hide 'Help' Button",
                    "fi": "Piilota 'Ohje'-painike",
                    "fr": "Masquer le bouton « Aide »",
                    "de": "Schaltfläche „Hilfe“ ausblenden",
                    "el": "Απόκρυψη κουμπιού 'Βοήθεια'",
                    "he": "הסתר את כפתור 'עזרה'",
                    "hi": "'सहायता' बटन छुपाएं",
                    "hu": "A „Súgó” gomb elrejtése",
                    "id": "Sembunyikan Tombol 'Bantuan'",
                    "it": "Nascondi il pulsante 'Aiuto'",
                    "ja": "「ヘルプ」ボタンを非表示にする",
                    "ko": "'도움말' 버튼 숨기기",
                    "ms": "Sembunyikan Butang 'Bantuan'",
                    "no": "Skjul 'Hjelp'-knappen",
                    "pl": "Ukryj przycisk „Pomoc”",
                    "pt": "Ocultar botão 'Ajuda'",
                    "ro": "Ascundeți butonul „Ajutor”",
                    "ru": "Скрыть кнопку «Помощь»",
                    "sk": "Skryť tlačidlo „Pomoc“",
                    "es": "Ocultar el botón 'Ayuda'",
                    "sv": "Dölj 'Hjälp'-knappen",
                    "th": "ซ่อนปุ่ม 'ช่วยเหลือ'",
                    "tr": "'Yardım' Düğmesini Gizle",
                    "uk": "Сховати кнопку «Довідка»",
                    "vi": "Ẩn nút 'Trợ giúp'"
                  },
                id: "untrap_you_page_hide_button_help",
                defaultValue: false
            },
            {
                type: "checkbox",
                name: {
                    "ar": "إخفاء زر 'التعليقات'",
                    "ca": "Amaga el botó 'Comentaris'",
                    "zh-CN": "隐藏“反馈”按钮",
                    "zh-TW": "隱藏「回饋」按鈕",
                    "hr": "Sakrij gumb 'Povratne informacije'",
                    "cs": "Skrýt tlačítko 'Zpětná vazba'",
                    "da": "Skjul knappen 'Feedback'",
                    "nl": "Knop 'Feedback' verbergen",
                    "en": "Hide 'Feedback' Button",
                    "fi": "Piilota 'Palaute'-painike",
                    "fr": "Masquer le bouton « Commentaires »",
                    "de": "Schaltfläche „Feedback“ ausblenden",
                    "el": "Απόκρυψη κουμπιού 'Σχόλια'",
                    "he": "הסתר כפתור 'משוב'",
                    "hi": "'फ़ीडबैक' बटन छिपाएँ",
                    "hu": "A „Visszajelzés” gomb elrejtése",
                    "id": "Sembunyikan Tombol 'Umpan Balik'",
                    "it": "Nascondi il pulsante 'Feedback'",
                    "ja": "「フィードバック」ボタンを非表示にする",
                    "ko": "'피드백' 버튼 숨기기",
                    "ms": "Sembunyikan Butang 'Maklum Balas'",
                    "no": "Skjul 'Tilbakemelding'-knappen",
                    "pl": "Ukryj przycisk „Prześlij opinię”",
                    "pt": "Ocultar botão 'Feedback'",
                    "ro": "Ascundeți butonul „Feedback”",
                    "ru": "Скрыть кнопку «Отзыв»",
                    "sk": "Skryť tlačidlo „Spätná väzba“",
                    "es": "Ocultar el botón 'Comentarios'",
                    "sv": "Dölj 'Feedback'-knappen",
                    "th": "ซ่อนปุ่ม 'คำติชม'",
                    "tr": "'Geri Bildirim' Düğmesini Gizle",
                    "uk": "Сховати кнопку «Відгук»",
                    "vi": "Ẩn nút 'Phản hồi'"
                  },
                id: "untrap_you_page_hide_button_feedback",
                defaultValue: false
            }
        ]
    }
];

// MARK: - Builder

// Desktop

const youPageDesktopGroups = [
    {
        groupName: {
            "ar": "الأقسام",
            "ca": "Seccions",
            "zh-CN": "部分",
            "zh-TW": "部分",
            "hr": "Sekcije",
            "cs": "Sekce",
            "da": "Afsnit",
            "nl": "Secties",
            "en": "Sections",
            "fi": "Osat",
            "fr": "Sections",
            "de": "Abschnitte",
            "el": "Ενότητες",
            "he": "מקטעים",
            "hi": "धारा",
            "hu": "Szakaszok",
            "id": "Bagian",
            "it": "Sezioni",
            "ja": "セクション",
            "ko": "섹션",
            "ms": "Bahagian",
            "nb": "Seksjoner",
            "pl": "Sekcje",
            "pt": "Seções",
            "ro": "Secțiuni",
            "ru": "Разделы",
            "sk": "Sekcie",
            "es": "Secciones",
            "sv": "Avsnitt",
            "th": "ส่วนต่างๆ",
            "tr": "Bölümler",
            "uk": "Розділи",
            "vi": "Phần"
          },
        groupId: "sections",
        parentCategoryId: "youPage",
        options: youPageDesktopGroups_Sections
    }
];

// Mobile

const youPageMobileGroups = [
    {
        groupName: {
            "ar": "معلوماتي",
            "ca": "La meva informació",
            "zh-CN": "我的信息",
            "zh-TW": "我的信息",
            "hr": "Moje informacije",
            "cs": "Moje informace",
            "da": "Min info",
            "nl": "Mijn informatie",
            "en": "My Info",
            "fi": "Omat tiedot",
            "fr": "Mes informations",
            "de": "Meine Information",
            "el": "Οι πληροφορίες μου",
            "he": "המידע שלי",
            "hi": "मेरी जानकारी",
            "hu": "Saját információ",
            "id": "Info saya",
            "it": "Le mie informazioni",
            "ja": "私の情報",
            "ko": "내 정보",
            "ms": "Maklumat Saya",
            "no": "Min info",
            "pl": "Moje informacje",
            "pt": "Minha informação",
            "ro": "Informatia mea",
            "ru": "Моя информация",
            "sk": "Moje informácie",
            "es": "Mi información",
            "sv": "Min info",
            "th": "ข้อมูลของฉัน",
            "tr": "Bilgilerim",
            "uk": "Моя інформація",
            "vi": "Thông tin của tôi"
          },
        groupId: "myInfo",
        parentCategoryId: "youPage",
        options: youPageMobileGroups_MyInfo
    },
    {
        groupName: {
            "ar": "الأقسام",
            "ca": "Seccions",
            "zh-CN": "部分",
            "zh-TW": "部分",
            "hr": "Sekcije",
            "cs": "Sekce",
            "da": "Afsnit",
            "nl": "Secties",
            "en": "Sections",
            "fi": "Osat",
            "fr": "Sections",
            "de": "Abschnitte",
            "el": "Ενότητες",
            "he": "מקטעים",
            "hi": "धारा",
            "hu": "Szakaszok",
            "id": "Bagian",
            "it": "Sezioni",
            "ja": "セクション",
            "ko": "섹션",
            "ms": "Bahagian",
            "nb": "Seksjoner",
            "pl": "Sekcje",
            "pt": "Seções",
            "ro": "Secțiuni",
            "ru": "Разделы",
            "sk": "Sekcie",
            "es": "Secciones",
            "sv": "Avsnitt",
            "th": "ส่วนต่างๆ",
            "tr": "Bölümler",
            "uk": "Розділи",
            "vi": "Phần"
          },
        groupId: "sections",
        parentCategoryId: "youPage",
        options: youPageMobileGroups_Sections
    },
    {
        groupName: {
            "ar": "أزرار",
            "ca": "Botons",
            "zh-CN": "纽扣",
            "zh-TW": "羈扣",
            "hr": "Gumbi",
            "cs": "Tlačítka",
            "da": "Knapper",
            "nl": "Toetsen",
            "en": "Buttons",
            "fi": "Painikkeet",
            "fr": "Boutons",
            "de": "Tasten",
            "el": "Κουμπιά",
            "he": "כפתורים",
            "hi": "बटन",
            "hu": "Gombok",
            "id": "Tombol",
            "it": "Pulsanti",
            "ja": "ボタン",
            "ko": "버튼",
            "ms": "Butang",
            "no": "Knapper",
            "pl": "Guziki",
            "pt": "Botões",
            "ro": "Butoane",
            "ru": "Кнопки",
            "sk": "Tlačidlá",
            "es": "Botones",
            "sv": "Knappar",
            "th": "ปุ่ม",
            "tr": "Düğmeler",
            "uk": "Кнопки",
            "vi": "Nút"
          },
        groupId: "sections",
        parentCategoryId: "buttons",
        options: youPageMobileGroups_Buttons
    }
]
